const fs = require('fs');

const newPlaces = [
    // Siwa (5)
    { id: 2001, name: 'واحة سيوة', nameEn: 'Siwa Oasis', city: 'سيوة', cityEn: 'Siwa', category: 'Nature', description: 'واحة ساحرة في قلب الصحراء الغربية تتميز بعيون المياه العذبة وبساتين النخيل.', descriptionEn: 'A magical oasis in the heart of the Western Desert featuring freshwater springs and palm groves.', image: '🌴', imageUrl: 'https://images.unsplash.com/photo-1505691938895-1758d7feb511?w=800&q=80', rating: 4.9, duration: '2-3 days', price: 'Free', highlights: ['Salt Lakes', 'Fatnas Island', 'Desert Safari'], tip: "Don't miss swimming in the salt lakes, you will float effortlessly.", lat: 29.2032, lng: 25.5195 },
    { id: 2002, name: 'حمام كليوباترا', nameEn: 'Cleopatra\'s Pool', city: 'سيوة', cityEn: 'Siwa', category: 'Medical', description: 'عين مياه طبيعية دافئة يقال إن الملكة كليوباترا كانت تسبح فيها.', descriptionEn: 'A natural warm water spring where Queen Cleopatra is said to have swum.', image: '♨️', imageUrl: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800&q=80', rating: 4.6, duration: '1-2 hours', price: 'Free', highlights: ['Natural Spring', 'Cafes nearby', 'Relaxation'], tip: 'It can be crowded during the day, try to visit early morning.', lat: 29.2132, lng: 25.5321 },
    { id: 2003, name: 'قلعة شالي', nameEn: 'Shali Fortress', city: 'سيوة', cityEn: 'Siwa', category: 'Cultural', description: 'بقايا مدينة مبنية من الكرشيف (مزيج الملح والطين) توفر إطلالة بانورامية على الواحة.', descriptionEn: 'Ruins of a city built from kershef (salt and mud mix) offering a panoramic view of the oasis.', image: '🏰', imageUrl: 'https://images.unsplash.com/photo-1628151015968-3a4429e9ef04?w=800&q=80', rating: 4.7, duration: '1-2 hours', price: 'Free', highlights: ['Historic Ruins', 'Sunset View', 'Traditional Architecture'], tip: 'Climb to the top just before sunset for a breathtaking view.', lat: 29.2036, lng: 25.5199 },
    { id: 2004, name: 'جبل الموتى', nameEn: 'Mountain of the Dead', city: 'سيوة', cityEn: 'Siwa', category: 'Pharaonic', description: 'جبل صخري يضم آلاف المقابر المنحوتة التي تعود للعصور الفرعونية واليونانية الرومانية.', descriptionEn: 'A rocky mountain featuring thousands of carved tombs dating back to the Pharaonic and Greco-Roman eras.', image: '⛰️', imageUrl: 'https://images.unsplash.com/photo-1590727265930-b3861fb16a1c?w=800&q=80', rating: 4.6, duration: '1-2 hours', price: '100 EGP', highlights: ['Ancient Tombs', 'Wall Paintings', 'Oasis View'], tip: 'The tomb of Si-Amun has the most beautiful and well-preserved paintings.', lat: 29.2135, lng: 25.5255 },
    { id: 2005, name: 'بحر الرمال الأعظم', nameEn: 'Great Sand Sea', city: 'سيوة', cityEn: 'Siwa', category: 'Nature', description: 'مساحة شاسعة من الكثبان الرملية الذهبية مثالية لرحلات السفاري والتزلج على الرمال.', descriptionEn: 'A vast expanse of golden sand dunes perfect for safaris and sandboarding.', image: '🏜️', imageUrl: 'https://images.unsplash.com/photo-1587061949409-02df41d5e562?w=800&q=80', rating: 4.8, duration: 'Half Day', price: 'Variable', highlights: ['Sandboarding', '4x4 Safari', 'Hot Springs'], tip: 'Book a 4x4 safari with a local guide and enjoy tea at the hot springs.', lat: 28.9833, lng: 25.4333 },

    // Luxor (4)
    { id: 2006, name: 'وادي الملكات', nameEn: 'Valley of the Queens', city: 'الأقصر', cityEn: 'Luxor', category: 'Pharaonic', description: 'موقع الدفن لزوجات الفراعنة، يضم مقبرة الملكة نفرتاري الساحرة.', descriptionEn: 'The burial site for pharaohs\' wives, featuring the stunning tomb of Queen Nefertari.', image: '🪦', imageUrl: 'https://images.unsplash.com/photo-1590727265930-b3861fb16a1c?w=800&q=80', rating: 4.8, duration: '1-2 hours', price: '150 EGP', highlights: ['Tomb of Nefertari', 'Colorful Hieroglyphs', 'Quiet Atmosphere'], tip: 'The Nefertari tomb requires an extra ticket but is considered the most beautiful tomb in Egypt.', lat: 25.7282, lng: 32.5936 },
    { id: 2007, name: 'معبد الرامسيوم', nameEn: 'Ramesseum', city: 'الأقصر', cityEn: 'Luxor', category: 'Pharaonic', description: 'المعبد الجنائزي العظيم لرمسيس الثاني، يشتهر بتمثاله الضخم الساقط.', descriptionEn: 'The great mortuary temple of Ramses II, famous for its fallen colossal statue.', image: '🏛️', imageUrl: 'https://images.unsplash.com/photo-1539650116574-8efeb43e2b50?w=800&q=80', rating: 4.6, duration: '1-2 hours', price: '120 EGP', highlights: ['Fallen Colossus', 'Osiride Pillars', 'Battle of Kadesh Reliefs'], tip: 'It is less crowded than other temples, offering a peaceful experience.', lat: 25.7277, lng: 32.6105 },
    { id: 2008, name: 'تمثالا ممنون', nameEn: 'Colossi of Memnon', city: 'الأقصر', cityEn: 'Luxor', category: 'Pharaonic', description: 'تمثالان ضخمان للملك أمنحتب الثالث يقفان كحراس لمدخل معبده الجنائزي.', descriptionEn: 'Two massive stone statues of Amenhotep III standing as guards to his mortuary temple.', image: '🗿', imageUrl: 'https://images.unsplash.com/photo-1600521605604-001083422002?w=800&q=80', rating: 4.5, duration: '30 mins', price: 'Free', highlights: ['Giant Statues', 'Historical Significance', 'Photo Stop'], tip: 'A quick and free stop on your way to the West Bank tombs.', lat: 25.7206, lng: 32.6101 },
    { id: 2009, name: 'فيلوكة في النيل بالأقصر', nameEn: 'Felucca Ride in Luxor', city: 'الأقصر', cityEn: 'Luxor', category: 'Nature', description: 'رحلة استرخاء في قارب شراعي تقليدي على نهر النيل، مثالية وقت الغروب.', descriptionEn: 'A relaxing trip on a traditional sailboat on the Nile, perfect at sunset.', image: '⛵', imageUrl: 'https://images.unsplash.com/photo-1577083464535-430c72719277?w=800&q=80', rating: 4.7, duration: '1-2 hours', price: '200 EGP', highlights: ['Sunset View', 'Nile Breeze', 'Banana Island Trip'], tip: 'Negotiate the price before boarding and ask for a trip to Banana Island.', lat: 25.7000, lng: 32.6350 },

    // Aswan (4)
    { id: 2010, name: 'السد العالي', nameEn: 'Aswan High Dam', city: 'أسوان', cityEn: 'Aswan', category: 'Cultural', description: 'إنجاز هندسي عظيم في القرن العشرين يتحكم في فيضان النيل ويولد الكهرباء.', descriptionEn: 'A great 20th-century engineering feat that controls the Nile floods and generates electricity.', image: '🏗️', imageUrl: 'https://images.unsplash.com/photo-1543888361-b753f2c53a29?w=800&q=80', rating: 4.4, duration: '1 hour', price: '150 EGP', highlights: ['Engineering Marvel', 'Lake Nasser View', 'Friendship Monument'], tip: 'Bring a hat and sunglasses, as there is very little shade on the dam.', lat: 23.9697, lng: 32.8797 },
    { id: 2011, name: 'جزيرة إلفنتين والقرية النوبية', nameEn: 'Elephantine & Nubian Village', city: 'أسوان', cityEn: 'Aswan', category: 'Cultural', description: 'جولة للتعرف على الثقافة النوبية الأصيلة في بيوتها الملونة وتراثها الفريد.', descriptionEn: 'A tour to discover authentic Nubian culture, colorful houses, and unique heritage.', image: '🛖', imageUrl: 'https://images.unsplash.com/photo-1605156510344-984365792437?w=800&q=80', rating: 4.8, duration: '2-3 hours', price: 'Free / Boat Ride', highlights: ['Colorful Houses', 'Local Spices', 'Pet Crocodiles'], tip: 'Try the traditional Nubian tea and buy some fresh spices from the local market.', lat: 24.0883, lng: 32.8872 },
    { id: 2012, name: 'المسلة الناقصة', nameEn: 'Unfinished Obelisk', city: 'أسوان', cityEn: 'Aswan', category: 'Pharaonic', description: 'أكبر مسلة فرعونية معروفة، لا تزال متصلة بصخور الجرانيت التي قطعت منها.', descriptionEn: 'The largest known ancient obelisk, still attached to the granite bedrock from which it was carved.', image: '⛏️', imageUrl: 'https://images.unsplash.com/photo-1590727265930-b3861fb16a1c?w=800&q=80', rating: 4.3, duration: '1 hour', price: '120 EGP', highlights: ['Ancient Stone Quarry', 'Stone-working techniques', 'Massive Scale'], tip: 'Best visited early to avoid the heat radiating from the granite rocks.', lat: 24.0768, lng: 32.8953 },
    { id: 2013, name: 'معبد كوم أمبو', nameEn: 'Kom Ombo Temple', city: 'أسوان', cityEn: 'Aswan', category: 'Pharaonic', description: 'معبد فريد مخصص لإلهين معاً: سوبك (التمساح) وحورس (الصقر).', descriptionEn: 'A unique temple dedicated to two gods: Sobek (the crocodile) and Horus (the falcon).', image: '🐊', imageUrl: 'https://images.unsplash.com/photo-1539650116574-8efeb43e2b50?w=800&q=80', rating: 4.7, duration: '1-2 hours', price: '200 EGP', highlights: ['Double Temple Design', 'Crocodile Museum', 'Medical Instruments Relief'], tip: 'Visit the small but fascinating Crocodile Mummy Museum right next to the temple.', lat: 24.4522, lng: 32.9284 },

    // Alexandria (5)
    { id: 2014, name: 'كورنيش الإسكندرية وستانلي', nameEn: 'Alexandria Corniche & Stanley', city: 'الإسكندرية', cityEn: 'Alexandria', category: 'Beach', description: 'ممشى بحري طويل ينبض بالحياة، يضم كوبري ستانلي الشهير ذو التصميم الكلاسيكي.', descriptionEn: 'A long, lively waterfront promenade featuring the iconic classical-style Stanley Bridge.', image: '🌉', imageUrl: 'https://images.unsplash.com/photo-1605156510344-984365792437?w=800&q=80', rating: 4.8, duration: '2-3 hours', price: 'Free', highlights: ['Stanley Bridge', 'Sea Views', 'Street Corn'], tip: 'Enjoy a walk at sunset and try the roasted corn sold by street vendors.', lat: 31.2351, lng: 29.9515 },
    { id: 2015, name: 'قصر المنتزه وحدائقه', nameEn: 'Montazah Palace Gardens', city: 'الإسكندرية', cityEn: 'Alexandria', category: 'Nature', description: 'حدائق ملكية شاسعة تحيط بقصر الحرملك وتطل على ساحل البحر الأبيض المتوسط.', descriptionEn: 'Vast royal gardens surrounding the Haramlek Palace, overlooking the Mediterranean coast.', image: '🌲', imageUrl: 'https://images.unsplash.com/photo-1563804863830-ec38c4c78103?w=800&q=80', rating: 4.6, duration: '2-3 hours', price: '50 EGP', highlights: ['Royal Palace Exterior', 'Pine Trees', 'Quiet Beaches'], tip: 'Great place for a family picnic. The palace itself is usually closed to the public.', lat: 31.2886, lng: 30.0159 },
    { id: 2016, name: 'المسرح الروماني', nameEn: 'Roman Amphitheatre', city: 'الإسكندرية', cityEn: 'Alexandria', category: 'Pharaonic', description: 'المسرح الروماني الوحيد في مصر، يضم مدرجات رخامية وفيلات مزينة بالفسيفساء.', descriptionEn: 'The only Roman amphitheatre in Egypt, featuring marble seating and mosaic-decorated villas.', image: '🏛️', imageUrl: 'https://images.unsplash.com/photo-1590727265930-b3861fb16a1c?w=800&q=80', rating: 4.5, duration: '1 hour', price: '100 EGP', highlights: ['Marble Seats', 'Villa of the Birds', 'Roman Baths'], tip: 'Stand in the center of the stage and test the perfect ancient acoustics.', lat: 31.1927, lng: 29.9044 },
    { id: 2017, name: 'مقابر كوم الشقافة', nameEn: 'Catacombs of Kom el Shoqafa', city: 'الإسكندرية', cityEn: 'Alexandria', category: 'Pharaonic', description: 'عجيبة معمارية تحت الأرض تمزج بين الفنون المصرية واليونانية والرومانية.', descriptionEn: 'An underground architectural wonder blending Egyptian, Greek, and Roman art styles.', image: '🕳️', imageUrl: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800&q=80', rating: 4.7, duration: '1 hour', price: '120 EGP', highlights: ['Spiral Staircase', 'Triclinium', 'Caracal Hall'], tip: 'It can be a bit humid underground; wear comfortable shoes for the spiral stairs.', lat: 31.1786, lng: 29.8931 },
    { id: 2018, name: 'سيدي عبد الرحمن', nameEn: 'Sidi Abdel Rahman', city: 'الساحل الشمالي', cityEn: 'North Coast', category: 'Beach', description: 'شاطئ ذو رمال بيضاء نقية ومياه فيروزية صافية، يعتبر من أجمل شواطئ الساحل الشمالي.', descriptionEn: 'A pristine white sand beach with clear turquoise waters, considered one of the best on the North Coast.', image: '🏖️', imageUrl: 'https://images.unsplash.com/photo-1473496169904-658ba7c44d8a?w=800&q=80', rating: 4.9, duration: 'Full Day', price: 'Variable', highlights: ['White Sands', 'Crystal Water', 'Upscale Resorts'], tip: 'Best visited during the summer months (June to September).', lat: 30.9333, lng: 28.7167 },

    // Sharm El Sheikh (4)
    { id: 2019, name: 'خليج نعمة', nameEn: 'Naama Bay', city: 'شرم الشيخ', cityEn: 'Sharm El Sheikh', category: 'Beach', description: 'المركز السياحي النابض بالحياة في شرم الشيخ، مليء بالمقاهي والمطاعم والشواطئ الرملية.', descriptionEn: 'The vibrant tourist center of Sharm, filled with cafes, restaurants, and sandy beaches.', image: '🌴', imageUrl: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&q=80', rating: 4.5, duration: '3-4 hours', price: 'Free', highlights: ['Promenade', 'Shisha Cafes', 'Nightlife'], tip: 'Perfect for a lively evening walk; be prepared for active restaurant promoters.', lat: 27.9158, lng: 34.3299 },
    { id: 2020, name: 'جزيرة تيران', nameEn: 'Tiran Island', city: 'شرم الشيخ', cityEn: 'Sharm El Sheikh', category: 'Diving', description: 'موقع غوص عالمي يشتهر بالشعاب المرجانية البكر وحطام السفن الغارقة.', descriptionEn: 'A world-class diving site known for pristine coral reefs and shipwrecks.', image: '🤿', imageUrl: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800&q=80', rating: 4.8, duration: 'Full Day', price: '800 EGP', highlights: ['Snorkeling', 'Gordon Reef', 'Shipwreck View'], tip: 'Book a yacht trip; the waters can be slightly choppy, so bring motion sickness pills if needed.', lat: 27.9542, lng: 34.5683 },
    { id: 2021, name: 'محمية نبق', nameEn: 'Nabq Nature Reserve', city: 'شرم الشيخ', cityEn: 'Sharm El Sheikh', category: 'Nature', description: 'محمية طبيعية فريدة تجمع بين غابات المانجروف والكثبان الرملية والشعاب المرجانية.', descriptionEn: 'A unique nature reserve combining mangrove forests, sand dunes, and coral reefs.', image: '🌿', imageUrl: 'https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=800&q=80', rating: 4.6, duration: '4-5 hours', price: '150 EGP', highlights: ['Mangroves', 'Bird Watching', 'Bedouin Culture'], tip: 'A guided quad bike or 4x4 tour is the best way to explore the reserve.', lat: 28.1633, lng: 34.4283 },
    { id: 2022, name: 'خليج القرش', nameEn: 'Shark\'s Bay', city: 'شرم الشيخ', cityEn: 'Sharm El Sheikh', category: 'Diving', description: 'منطقة هادئة وراقية تتميز بمواقع سنوركلينج ممتازة ومطاعم تطل على البحر.', descriptionEn: 'A quiet, upscale area featuring excellent snorkeling sites and sea-view restaurants.', image: '🦈', imageUrl: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=800&q=80', rating: 4.7, duration: 'Half Day', price: 'Free', highlights: ['Snorkeling', 'Soho Square nearby', 'Relaxed Vibe'], tip: 'Despite the name, there are no sharks! The reef drop-off is stunning.', lat: 27.9572, lng: 34.3941 },

    // Hurghada (3)
    { id: 2023, name: 'أكواريوم الغردقة', nameEn: 'Hurghada Grand Aquarium', city: 'الغردقة', cityEn: 'Hurghada', category: 'Cultural', description: 'نافذة مذهلة على الحياة البحرية في البحر الأحمر بدون الحاجة للغوص.', descriptionEn: 'An amazing window into the Red Sea marine life without the need to dive.', image: '🐠', imageUrl: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=800&q=80', rating: 4.4, duration: '2-3 hours', price: '600 EGP', highlights: ['Shark Tunnel', 'Rainforest Area', 'Mini Zoo'], tip: 'Great for families with children. Try to catch the shark feeding time.', lat: 27.1353, lng: 33.8242 },
    { id: 2024, name: 'مارينا الغردقة', nameEn: 'Hurghada Marina', city: 'الغردقة', cityEn: 'Hurghada', category: 'Cultural', description: 'ممشي سياحي أنيق يضم يخوت فاخرة ومجموعة متنوعة من المطاعم والكافيهات.', descriptionEn: 'An elegant promenade featuring luxury yachts, restaurants, and cafes.', image: '⛵', imageUrl: 'https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?w=800&q=80', rating: 4.7, duration: '2-3 hours', price: 'Free', highlights: ['Yacht Views', 'Dining', 'Live Music'], tip: 'A perfect spot for a romantic dinner or a relaxed evening stroll.', lat: 27.2272, lng: 33.8406 },
    { id: 2025, name: 'جزيرة أورنج بيتش', nameEn: 'Orange Bay Island', city: 'الغردقة', cityEn: 'Hurghada', category: 'Beach', description: 'جزيرة استوائية ساحرة تشبه جزر المالديف بمياهها الضحلة ومرافقها الخشبية.', descriptionEn: 'A magical tropical island resembling the Maldives with shallow waters and wooden structures.', image: '🏝️', imageUrl: 'https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?w=800&q=80', rating: 4.6, duration: 'Full Day', price: '900 EGP', highlights: ['Swings in water', 'Bean Bags', 'Snorkeling Stops'], tip: 'The water is very shallow, making it incredibly safe for young kids.', lat: 27.2210, lng: 33.9000 },

    // Fayoum (3)
    { id: 2026, name: 'وادي الحيتان', nameEn: 'Wadi El Hitan', city: 'الفيوم', cityEn: 'Fayoum', category: 'Nature', description: 'موقع تراث عالمي يضم هياكل عظمية متحجرة لحيتان ما قبل التاريخ في قلب الصحراء.', descriptionEn: 'A World Heritage site featuring fossilized skeletons of prehistoric whales in the desert.', image: '🐋', imageUrl: 'https://images.unsplash.com/photo-1587061949409-02df41d5e562?w=800&q=80', rating: 4.9, duration: '3-4 hours', price: '150 EGP', highlights: ['Whale Fossils', 'Open Air Museum', 'Stargazing'], tip: 'It gets very hot in summer, so autumn/winter is the best time to visit.', lat: 29.2667, lng: 30.0458 },
    { id: 2027, name: 'بحيرة قارون', nameEn: 'Lake Qarun', city: 'الفيوم', cityEn: 'Fayoum', category: 'Nature', description: 'بحيرة تاريخية كبيرة تعتبر ملاذاً للطيور المهاجرة ومكاناً رائعاً للاسترخاء.', descriptionEn: 'A large historical lake serving as a haven for migratory birds and a great place to relax.', image: '🦆', imageUrl: 'https://images.unsplash.com/photo-1505691938895-1758d7feb511?w=800&q=80', rating: 4.3, duration: '1-2 hours', price: 'Free', highlights: ['Bird Watching', 'Boat Rides', 'Seafood Restaurants'], tip: 'Try the local lake fish at one of the rustic restaurants on the shore.', lat: 29.4750, lng: 30.6500 },
    { id: 2028, name: 'شلالات وادي الريان', nameEn: 'Wadi El Rayan Waterfalls', city: 'الفيوم', cityEn: 'Fayoum', category: 'Nature', description: 'الشلالات الطبيعية الوحيدة في مصر، تربط بين بحيرتين وسط الكثبان الرملية.', descriptionEn: 'The only natural waterfalls in Egypt, connecting two lakes amidst sand dunes.', image: '🌊', imageUrl: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800&q=80', rating: 4.6, duration: '2-3 hours', price: '100 EGP', highlights: ['Waterfalls', 'Sandboarding', 'Felucca Ride'], tip: 'Avoid Fridays and national holidays if you prefer a quiet experience.', lat: 29.1300, lng: 30.4000 },

    // Ain Sokhna (3)
    { id: 2029, name: 'بورتو السخنة', nameEn: 'Porto Sokhna', city: 'العين السخنة', cityEn: 'Ain Sokhna', category: 'Beach', description: 'منتجع شهير يضم تلفريك يقدم إطلالة رائعة على الجبال والبحر الأحمر.', descriptionEn: 'A famous resort featuring a cable car with great views of the mountains and Red Sea.', image: '🚠', imageUrl: 'https://images.unsplash.com/photo-1473496169904-658ba7c44d8a?w=800&q=80', rating: 4.4, duration: 'Half Day', price: 'Variable', highlights: ['Cable Car', 'Restaurants', 'Mountain View'], tip: 'Take the cable car at sunset for the best photos.', lat: 29.5667, lng: 32.3333 },
    { id: 2030, name: 'مدينة الجلالة', nameEn: 'Galala City', city: 'العين السخنة', cityEn: 'Ain Sokhna', category: 'Nature', description: 'مدينة جبلية ساحلية حديثة تتميز بالتلفريك والمارينا والأنشطة الترفيهية.', descriptionEn: 'A modern coastal mountain city featuring a cable car, marina, and leisure activities.', image: '🏙️', imageUrl: 'https://images.unsplash.com/photo-1605156510344-984365792437?w=800&q=80', rating: 4.7, duration: 'Half Day', price: 'Free', highlights: ['Galala Marina', 'Waterpark', 'Cable Car'], tip: 'The waterpark here is top-notch and great for escaping the heat.', lat: 29.3833, lng: 32.5000 },
    { id: 2031, name: 'ستيلا دي ماري', nameEn: 'Stella Di Mare', city: 'العين السخنة', cityEn: 'Ain Sokhna', category: 'Beach', description: 'مجمع منتجعات فاخر يوفر شواطئ رملية رائعة وملاعب جولف.', descriptionEn: 'A luxury resort complex offering great sandy beaches and golf courses.', image: '🏖️', imageUrl: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&q=80', rating: 4.5, duration: 'Full Day', price: 'Variable', highlights: ['Golf Course', 'Thalasso Spa', 'Sandy Beach'], tip: 'Book a day-use package to enjoy the pristine beach and spa facilities.', lat: 29.7167, lng: 32.3000 },

    // Ismailia (3)
    { id: 2032, name: 'قناة السويس', nameEn: 'Suez Canal', city: 'الإسماعيلية', cityEn: 'Ismailia', category: 'Cultural', description: 'الممر الملاحي العالمي الذي يربط البحرين الأحمر والمتوسط، مشهد عبور السفن الضخمة مذهل.', descriptionEn: 'The global waterway connecting the Red and Med seas; watching massive ships pass is mesmerizing.', image: '🚢', imageUrl: 'https://images.unsplash.com/photo-1605156510344-984365792437?w=800&q=80', rating: 4.8, duration: '1-2 hours', price: 'Free', highlights: ['Ship Watching', 'Historical Monument', 'Promenade'], tip: 'Sit at a cafe along the canal and watch the giant ships pass silently by.', lat: 30.5833, lng: 32.2667 },
    { id: 2033, name: 'بحيرة التمساح', nameEn: 'Lake Timsah', city: 'الإسماعيلية', cityEn: 'Ismailia', category: 'Nature', description: 'بحيرة هادئة تشتهر بالشواطئ والأندية البحرية والمطاعم التي تقدم أشهى المأكولات البحرية.', descriptionEn: 'A tranquil lake known for beaches, nautical clubs, and excellent seafood restaurants.', image: '🌊', imageUrl: 'https://images.unsplash.com/photo-1505691938895-1758d7feb511?w=800&q=80', rating: 4.5, duration: 'Half Day', price: 'Free', highlights: ['Seafood', 'Boat Clubs', 'Relaxing Vibe'], tip: 'Try the famous local Ismailia seafood, especially the grilled fish.', lat: 30.5667, lng: 32.2833 },
    { id: 2034, name: 'متحف الإسماعيلية', nameEn: 'Ismailia Museum', city: 'الإسماعيلية', cityEn: 'Ismailia', category: 'Cultural', description: 'متحف إقليمي يعرض آثاراً من عصور مختلفة اكتشفت أثناء حفر قناة السويس.', descriptionEn: 'A regional museum displaying artifacts from various eras discovered during the canal excavation.', image: '🏺', imageUrl: 'https://images.unsplash.com/photo-1628151015968-3a4429e9ef04?w=800&q=80', rating: 4.3, duration: '1 hour', price: '40 EGP', highlights: ['Mosaic Floors', 'Pharaonic Artifacts', 'Canal History'], tip: 'A small but very well-maintained museum, perfect for a quick historical dose.', lat: 30.6000, lng: 32.2667 },

    // Port Said (3)
    { id: 2035, name: 'شارع التجاري / المنطقة الحرة', nameEn: 'El Gomhoureya Street / Free Zone', city: 'بورسعيد', cityEn: 'Port Said', category: 'Cultural', description: 'منطقة تسوق شهيرة تتميز بالبضائع المستوردة والملابس بأسعار معقولة.', descriptionEn: 'A famous shopping area featuring imported goods and affordable clothing.', image: '🛍️', imageUrl: 'https://images.unsplash.com/photo-1563804863830-ec38c4c78103?w=800&q=80', rating: 4.4, duration: '2-3 hours', price: 'Free', highlights: ['Shopping', 'Bazaar', 'Imported Goods'], tip: 'Bargaining is essential here to get the best deals.', lat: 31.2667, lng: 32.3000 },
    { id: 2036, name: 'فنار بورسعيد', nameEn: 'Port Said Lighthouse', city: 'بورسعيد', cityEn: 'Port Said', category: 'Cultural', description: 'أقدم مبنى خرساني في العالم ومن المعالم التاريخية البارزة في المدينة.', descriptionEn: 'The oldest concrete building in the world and a prominent historical landmark in the city.', image: '🗼', imageUrl: 'https://images.unsplash.com/photo-1543888361-b753f2c53a29?w=800&q=80', rating: 4.6, duration: '30 mins', price: 'Free', highlights: ['Architecture', 'Historical Significance', 'Photo Op'], tip: 'It is not open for climbing, but makes for a great architectural photo.', lat: 31.2625, lng: 32.3083 },
    { id: 2037, name: 'شاطئ بورسعيد', nameEn: 'Port Said Beach', city: 'بورسعيد', cityEn: 'Port Said', category: 'Beach', description: 'شاطئ شعبي واسع يطل على البحر المتوسط حيث تتجمع العائلات.', descriptionEn: 'A wide popular beach on the Mediterranean where families gather.', image: '⛱️', imageUrl: 'https://images.unsplash.com/photo-1473496169904-658ba7c44d8a?w=800&q=80', rating: 4.2, duration: 'Half Day', price: 'Variable', highlights: ['Family Friendly', 'Sea Shells', 'Cafes'], tip: 'Rent a beach chair and watch the massive ships entering the canal.', lat: 31.2750, lng: 32.3000 },

    // El Gouna (3)
    { id: 2038, name: 'مارينا أبو تيج', nameEn: 'Abu Tig Marina', city: 'الجونة', cityEn: 'El Gouna', category: 'Cultural', description: 'مارينا راقية تتميز باليخوت الفاخرة والمطاعم والمتاجر الأنيقة.', descriptionEn: 'An upscale marina featuring luxury yachts, restaurants, and chic boutiques.', image: '🛥️', imageUrl: 'https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?w=800&q=80', rating: 4.8, duration: '2-3 hours', price: 'Free', highlights: ['Luxury Yachts', 'Fine Dining', 'Boutiques'], tip: 'Visit on Friday afternoons for the lively Marina street festival.', lat: 27.3917, lng: 33.6750 },
    { id: 2039, name: 'شاطئ مانجروفي', nameEn: 'Mangroovy Beach', city: 'الجونة', cityEn: 'El Gouna', category: 'Beach', description: 'الشاطئ الأشهر في الجونة ومركز رياضات التزلج الشراعي على الماء (Kitesurfing).', descriptionEn: 'The most famous beach in El Gouna and a hub for kitesurfing.', image: '🪁', imageUrl: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&q=80', rating: 4.7, duration: 'Half Day', price: 'Variable', highlights: ['Kitesurfing', 'Beach Club', 'Parties'], tip: 'Take a beginner kitesurfing lesson; the shallow water makes it ideal.', lat: 27.4083, lng: 33.6833 },
    { id: 2040, name: 'ملعب الجولف', nameEn: 'El Gouna Golf Club', city: 'الجونة', cityEn: 'El Gouna', category: 'Nature', description: 'ملعب جولف عالمي من 18 حفرة محاط بالبحيرات الزرقاء والجبال.', descriptionEn: 'An 18-hole championship golf course surrounded by blue lagoons and mountains.', image: '⛳', imageUrl: 'https://images.unsplash.com/photo-1587061949409-02df41d5e562?w=800&q=80', rating: 4.6, duration: '4-5 hours', price: '1200 EGP', highlights: ['18 Holes', 'Clubhouse', 'Scenery'], tip: 'Book tee times early in the morning during summer to avoid the heat.', lat: 27.3833, lng: 33.6667 },

    // Sohag (2)
    { id: 2041, name: 'معبد أبيدوس', nameEn: 'Abydos Temple', city: 'سوهاج', cityEn: 'Sohag', category: 'Pharaonic', description: 'أحد أقدس المواقع في مصر القديمة، يتميز بنقوشه البارزة المذهلة وألوانه الباقية.', descriptionEn: 'One of the holiest sites in ancient Egypt, featuring stunning bas-reliefs and preserved colors.', image: '🛕', imageUrl: 'https://images.unsplash.com/photo-1590727265930-b3861fb16a1c?w=800&q=80', rating: 4.9, duration: '2-3 hours', price: '100 EGP', highlights: ['Temple of Seti I', 'Abydos King List', 'Osireion'], tip: 'The reliefs in the Temple of Seti I are considered the finest in all of Egypt.', lat: 26.1847, lng: 31.9189 },
    { id: 2042, name: 'الدير الأبيض', nameEn: 'White Monastery', city: 'سوهاج', cityEn: 'Sohag', category: 'Cultural', description: 'دير قبطي تاريخي بني من الحجر الجيري الأبيض المأخوذ من المعابد الفرعونية القديمة.', descriptionEn: 'A historic Coptic monastery built from white limestone taken from ancient Pharaonic temples.', image: '⛪', imageUrl: 'https://images.unsplash.com/photo-1577083464535-430c72719277?w=800&q=80', rating: 4.5, duration: '1-2 hours', price: 'Free', highlights: ['Ancient Architecture', 'Coptic Heritage', 'Peaceful Vibe'], tip: 'Respect the dress code as it is an active monastery.', lat: 26.5333, lng: 31.6667 },
    
    // Cairo (+5)
    { id: 2043, name: 'كوبري قصر النيل', nameEn: 'Qasr El Nil Bridge', city: 'القاهرة', cityEn: 'Cairo', category: 'Cultural', description: 'أشهر كباري القاهرة التاريخية بنقوشه وتماثيل الأسود الأربعة على مدخليه.', descriptionEn: 'Cairo\'s most famous historical bridge, known for its four lion statues.', image: '🌉', imageUrl: 'https://images.unsplash.com/photo-1605156510344-984365792437?w=800&q=80', rating: 4.5, duration: '1 hour', price: 'Free', highlights: ['Lion Statues', 'Nile View', 'Evening Walk'], tip: 'A popular spot for young Egyptians to walk at sunset.', lat: 30.0433, lng: 31.2267 },
    { id: 2044, name: 'حديقة الأزهر', nameEn: 'Al-Azhar Park', city: 'القاهرة', cityEn: 'Cairo', category: 'Nature', description: 'أكبر حدائق القاهرة بتصميم إسلامي فريد وإطلالة رائعة على القلعة ومآذن المدينة.', descriptionEn: 'Cairo\'s largest park with unique Islamic design and a great view of the Citadel.', image: '🌳', imageUrl: 'https://images.unsplash.com/photo-1563804863830-ec38c4c78103?w=800&q=80', rating: 4.8, duration: '2-3 hours', price: '40 EGP', highlights: ['Panoramic View', 'Islamic Gardens', 'Lakeside Cafe'], tip: 'Visit late afternoon to enjoy a picnic and watch the sunset behind the Citadel.', lat: 30.0400, lng: 31.2650 },
    { id: 2045, name: 'برج القاهرة', nameEn: 'Cairo Tower', city: 'القاهرة', cityEn: 'Cairo', category: 'Cultural', description: 'برج شاهق على شكل زهرة اللوتس يقدم إطلالة 360 درجة على العاصمة.', descriptionEn: 'A towering structure shaped like a lotus flower offering 360-degree views of the capital.', image: '🗼', imageUrl: 'https://images.unsplash.com/photo-1605156510344-984365792437?w=800&q=80', rating: 4.6, duration: '1-2 hours', price: '250 EGP', highlights: ['Panoramic Views', 'Revolving Restaurant', 'Lotus Design'], tip: 'Best time to go is right before sunset to see the city in both daylight and nighttime.', lat: 30.0459, lng: 31.2243 },
    { id: 2046, name: 'قصر عابدين', nameEn: 'Abdeen Palace', city: 'القاهرة', cityEn: 'Cairo', category: 'Cultural', description: 'أحد أفخم القصور الرئاسية ويضم متاحف تعرض الأسلحة والأوسمة والهدايا الرئاسية.', descriptionEn: 'One of the most luxurious presidential palaces, housing museums of weapons, medals, and presidential gifts.', image: '🏰', imageUrl: 'https://images.unsplash.com/photo-1563804863830-ec38c4c78103?w=800&q=80', rating: 4.7, duration: '2-3 hours', price: '100 EGP', highlights: ['Royal Collections', 'Weaponry Museum', 'Palace Architecture'], tip: 'A hidden gem in Cairo. Photography is restricted in some areas.', lat: 30.0414, lng: 31.2464 },
    { id: 2047, name: 'دار الأوبرا المصرية', nameEn: 'Cairo Opera House', city: 'القاهرة', cityEn: 'Cairo', category: 'Cultural', description: 'المركز الثقافي الرئيسي في مصر، يستضيف عروض الأوبرا والباليه والموسيقى الكلاسيكية.', descriptionEn: 'The main cultural venue in Egypt, hosting opera, ballet, and classical music performances.', image: '🎭', imageUrl: 'https://images.unsplash.com/photo-1514525253344-991c0575d04a?w=800&q=80', rating: 4.8, duration: '3-4 hours', price: 'Variable', highlights: ['Ballet Performances', 'Art Galleries', 'Main Hall'], tip: 'Check the schedule online and book tickets in advance. Dress code is formal.', lat: 30.0416, lng: 31.2229 }
];

let content = fs.readFileSync('src/constants/placesData.js', 'utf8');

// 1. Fix city names
content = content.replace(/city: 'شرم الشيخ',\s*cityEn: 'Sharm'/g, "city: 'شرم الشيخ',\n        cityEn: 'Sharm El Sheikh'");
content = content.replace(/city: 'مرسى مطروح',\s*cityEn: 'Matrouh'/g, "city: 'مرسى مطروح',\n        cityEn: 'Marsa Matrouh'");

// 2. Insert new places into the array
const closingBracketIndex = content.lastIndexOf('];');
if (closingBracketIndex !== -1) {
    const placesString = newPlaces.map(p => {
        let str = '    {\n';
        for (const [key, value] of Object.entries(p)) {
            if (key === 'highlights') {
                str += `        ${key}: [${value.map(v => "'" + v.replace(/'/g, "\\'") + "'").join(', ')}],\n`;
            } else if (typeof value === 'string') {
                str += `        ${key}: '${value.replace(/'/g, "\\'")}',\n`;
            } else {
                str += `        ${key}: ${value},\n`;
            }
        }
        str += '    }';
        return str;
    }).join(',\\n');
    
    // Inject right before the last bracket
    content = content.substring(0, closingBracketIndex) + ',\\n' + placesString + '\\n' + content.substring(closingBracketIndex);
    fs.writeFileSync('src/constants/placesData.js', content, 'utf8');
    console.log('Successfully injected ' + newPlaces.length + ' new places into placesData.js');
} else {
    console.error('Could not find the end of the places array.');
}
