export const expandedPlaces = [
    // --- SIWA OASIS ---
    {
        id: 2001,
        name: 'واحة سيوة',
        nameEn: 'Siwa Oasis',
        city: 'سيوة',
        cityEn: 'Siwa',
        category: 'Nature',
        description: 'واحة خضراء ساحرة في قلب الصحراء الغربية تشتهر بعيون المياه والبحيرات المالحة.',
        descriptionEn: 'A magical green oasis in the Western Desert famous for its water springs and salt lakes.',
        image: '🌴',
        imageUrl: 'https://images.unsplash.com/photo-1574691456108-a55e0a6d0c24?w=800&q=80',
        rating: 4.9,
        duration: '4-6 hours',
        price: 'Free',
        highlights: ['Salt Lakes', 'Palm Trees', 'Desert Safari'],
        tip: 'Bring your swimsuit to float in the salt lakes. It is an unforgettable experience.',
        lat: 29.2032,
        lng: 25.5195,
    },
    {
        id: 2002,
        name: 'حمام كليوباترا',
        nameEn: 'Cleopatra\'s Bath',
        city: 'سيوة',
        cityEn: 'Siwa',
        category: 'Medical',
        description: 'عين مياه طبيعية دافئة يُقال إن الملكة كليوباترا كانت تسبح فيها.',
        descriptionEn: 'A natural warm water spring where Queen Cleopatra is said to have bathed.',
        image: '♨️',
        imageUrl: 'https://images.unsplash.com/photo-1626074966606-5a4ce835ebc1?w=800&q=80',
        rating: 4.6,
        duration: '1-2 hours',
        price: 'Free',
        highlights: ['Natural Spring', 'Cafes nearby', 'Swimming'],
        tip: 'Best visited in the early morning to avoid the crowds.',
        lat: 29.2045,
        lng: 25.5255,
    },
    {
        id: 2003,
        name: 'قلعة شالي',
        nameEn: 'Shali Fortress',
        city: 'سيوة',
        cityEn: 'Siwa',
        category: 'Cultural',
        description: 'بقايا قلعة تاريخية مبنية من الطين والملح (الكرشيف) تتوسط الواحة.',
        descriptionEn: 'The ruins of a historical fortress built from mud and salt (kershef) in the center of the oasis.',
        image: '🏰',
        imageUrl: 'https://images.unsplash.com/photo-1601614748197-2002d2fc59b6?w=800&q=80',
        rating: 4.8,
        duration: '1-2 hours',
        price: 'Free',
        highlights: ['Historical Ruins', 'Panoramic Views', 'Traditional Architecture'],
        tip: 'Climb to the top for a spectacular sunset view over the entire oasis.',
        lat: 29.2016,
        lng: 25.5186,
    },
    {
        id: 2004,
        name: 'جبل الموتى',
        nameEn: 'Mountain of the Dead',
        city: 'سيوة',
        cityEn: 'Siwa',
        category: 'Pharaonic',
        description: 'جبل مخروطي يضم آلاف المقابر المنحوتة في الصخر تعود للعصور الفرعونية واليونانية.',
        descriptionEn: 'A conical mountain featuring thousands of rock-cut tombs from the Pharaonic and Greco-Roman eras.',
        image: '⛰️',
        imageUrl: 'https://images.unsplash.com/photo-1626074966468-450ef7583626?w=800&q=80',
        rating: 4.7,
        duration: '1-2 hours',
        price: '40 EGP',
        highlights: ['Ancient Tombs', 'Wall Paintings', 'Desert Views'],
        tip: 'Don\'t miss the Tomb of Si-Amun, known for its beautiful colorful frescoes.',
        lat: 29.2136,
        lng: 25.5226,
    },
    {
        id: 2005,
        name: 'بحر الرمال الأعظم',
        nameEn: 'Great Sand Sea',
        city: 'سيوة',
        cityEn: 'Siwa',
        category: 'Nature',
        description: 'امتداد شاسع من الكثبان الرملية الذهبية مثالي لرحلات السفاري والتزلج على الرمال.',
        descriptionEn: 'A vast expanse of golden sand dunes perfect for desert safaris and sandboarding.',
        image: '🏜️',
        imageUrl: 'https://images.unsplash.com/photo-1542384701-c0e46e0eda04?w=800&q=80',
        rating: 4.9,
        duration: '4-6 hours',
        price: '800 EGP',
        highlights: ['Sandboarding', '4x4 Safari', 'Bedouin Tea'],
        tip: 'Book a 4x4 safari with a local guide. The sunset from the dunes is breathtaking.',
        lat: 29.1000,
        lng: 25.4000,
    },

    // --- LUXOR (Additional) ---
    {
        id: 2006,
        name: 'وادي الملكات',
        nameEn: 'Valley of the Queens',
        city: 'الأقصر',
        cityEn: 'Luxor',
        category: 'Pharaonic',
        description: 'وادي يضم مقابر زوجات الفراعنة والأمراء، أبرزها مقبرة الملكة نفرتاري.',
        descriptionEn: 'A valley containing the tombs of pharaohs\' wives and princes, most notably Queen Nefertari.',
        image: '👑',
        imageUrl: 'https://images.unsplash.com/photo-1580974582391-a6649c82a85f?w=800&q=80',
        rating: 4.8,
        duration: '2-3 hours',
        price: '100 EGP',
        highlights: ['Nefertari Tomb', 'Ancient Art', 'Historical Tombs'],
        tip: 'The tomb of Nefertari requires an extra, expensive ticket, but it is considered the most beautiful tomb in Egypt.',
        lat: 25.7288,
        lng: 32.5932,
    },
    {
        id: 2007,
        name: 'معبد الرامسيوم',
        nameEn: 'Ramesseum Temple',
        city: 'الأقصر',
        cityEn: 'Luxor',
        category: 'Pharaonic',
        description: 'المعبد الجنائزي الضخم للملك رمسيس الثاني في البر الغربي.',
        descriptionEn: 'The massive mortuary temple of Ramses II on the West Bank of Luxor.',
        image: '🏛️',
        imageUrl: 'https://images.unsplash.com/photo-1600521605338-9cb525996b27?w=800&q=80',
        rating: 4.7,
        duration: '1-2 hours',
        price: '80 EGP',
        highlights: ['Colossal Statues', 'Hieroglyphs', 'Less Crowded'],
        tip: 'A great spot for photography as it is usually less crowded than Karnak.',
        lat: 25.7278,
        lng: 32.6105,
    },
    {
        id: 2008,
        name: 'تمثالا ممنون',
        nameEn: 'Colossi of Memnon',
        city: 'الأقصر',
        cityEn: 'Luxor',
        category: 'Pharaonic',
        description: 'تمثالان ضخمان للفرعون أمنحتب الثالث يبلغ ارتفاعهما 18 متراً.',
        descriptionEn: 'Two massive stone statues of the Pharaoh Amenhotep III reaching 18 meters high.',
        image: '🗿',
        imageUrl: 'https://images.unsplash.com/photo-1596767527632-40f0c0557262?w=800&q=80',
        rating: 4.6,
        duration: '30 mins',
        price: 'Free',
        highlights: ['Massive Statues', 'Quick Stop', 'Photo Op'],
        tip: 'Usually a quick stop on the way to the Valley of the Kings. Best lighting is in the early morning.',
        lat: 25.7205,
        lng: 32.6019,
    },
    {
        id: 2009,
        name: 'فلوكة في النيل',
        nameEn: 'Felucca Ride on the Nile',
        city: 'الأقصر',
        cityEn: 'Luxor',
        category: 'Nature',
        description: 'جولة هادئة في مركب شراعي تقليدي (فلوكة) وقت الغروب في نهر النيل.',
        descriptionEn: 'A peaceful ride on a traditional wooden sailboat (felucca) during sunset on the Nile.',
        image: '⛵',
        imageUrl: 'https://images.unsplash.com/photo-1534063859666-0797175bb8d8?w=800&q=80',
        rating: 4.9,
        duration: '1-2 hours',
        price: '200 EGP',
        highlights: ['Sunset Views', 'Relaxing', 'Traditional Boat'],
        tip: 'Negotiate the price before boarding. Sunset is the absolute best time for this.',
        lat: 25.7000,
        lng: 32.6333,
    },

    // --- ASWAN (Additional) ---
    {
        id: 2010,
        name: 'السد العالي',
        nameEn: 'Aswan High Dam',
        city: 'أسوان',
        cityEn: 'Aswan',
        category: 'Cultural',
        description: 'أحد أعظم المشاريع الهندسية في القرن العشرين، يوفر إطلالة رائعة على بحيرة ناصر.',
        descriptionEn: 'One of the greatest engineering projects of the 20th century, offering a great view of Lake Nasser.',
        image: '🏗️',
        imageUrl: 'https://images.unsplash.com/photo-1572252009286-268acec5ca0a?w=800&q=80',
        rating: 4.5,
        duration: '1 hour',
        price: '100 EGP',
        highlights: ['Lake Nasser View', 'Engineering Marvel', 'Monument of Arab-Soviet Friendship'],
        tip: 'Very windy at the top. Bring a light jacket even in summer.',
        lat: 23.9697,
        lng: 32.8767,
    },
    {
        id: 2011,
        name: 'جزيرة إلفنتين',
        nameEn: 'Elephantine Island',
        city: 'أسوان',
        cityEn: 'Aswan',
        category: 'Cultural',
        description: 'جزيرة نيلية هادئة تضم قرى نوبية ملونة ومتاحف وبقايا أثرية.',
        descriptionEn: 'A peaceful Nile island featuring colorful Nubian villages, museums, and archaeological ruins.',
        image: '🏝️',
        imageUrl: 'https://images.unsplash.com/photo-1627885489814-7d2d0b81804f?w=800&q=80',
        rating: 4.8,
        duration: '3-4 hours',
        price: 'Free',
        highlights: ['Nubian Villages', 'Aswan Museum', 'Nilometer'],
        tip: 'Take a local ferry from the corniche. Wander the colorful streets and have tea at a Nubian house.',
        lat: 24.0864,
        lng: 32.8872,
    },
    {
        id: 2012,
        name: 'المسلة الناقصة',
        nameEn: 'Unfinished Obelisk',
        city: 'أسوان',
        cityEn: 'Aswan',
        category: 'Pharaonic',
        description: 'أكبر مسلة قديمة معروفة، تركت في محجرها لتوضح طرق قطع الحجارة عند الفراعنة.',
        descriptionEn: 'The largest known ancient obelisk, left in its quarry, showing how pharaohs cut stone.',
        image: '⛏️',
        imageUrl: 'https://images.unsplash.com/photo-1533036923984-d62153ebf03d?w=800&q=80',
        rating: 4.5,
        duration: '1-2 hours',
        price: '80 EGP',
        highlights: ['Ancient Quarry', 'Stone Cutting Techniques', 'Massive Scale'],
        tip: 'It gets very hot in the quarry; visit early morning or late afternoon.',
        lat: 24.0768,
        lng: 32.8953,
    },
    {
        id: 2013,
        name: 'معبد كوم أمبو',
        nameEn: 'Kom Ombo Temple',
        city: 'أسوان',
        cityEn: 'Aswan',
        category: 'Pharaonic',
        description: 'معبد مزدوج فريد مخصص للإلهين سوبيك (التمساح) وحورس (الصقر).',
        descriptionEn: 'A unique double temple dedicated to two gods: Sobek (the crocodile) and Horus (the falcon).',
        image: '🐊',
        imageUrl: 'https://images.unsplash.com/photo-1596767527632-40f0c0557262?w=800&q=80', // Using a generic pharaonic for now
        rating: 4.7,
        duration: '2-3 hours',
        price: '140 EGP',
        highlights: ['Crocodile Museum', 'Medical Instruments Carvings', 'Nile View'],
        tip: 'The adjacent Crocodile Museum displaying mummified crocodiles is included in the ticket.',
        lat: 24.4522,
        lng: 32.9281,
    },

    // --- ALEXANDRIA (Additional) ---
    {
        id: 2014,
        name: 'كوبري ستانلي',
        nameEn: 'Stanley Bridge',
        city: 'الإسكندرية',
        cityEn: 'Alexandria',
        category: 'Cultural',
        description: 'كوبري خلاب فوق البحر المتوسط يتميز بتصميمه المعماري الإسلامي الحديث.',
        descriptionEn: 'A picturesque bridge over the Mediterranean featuring modern Islamic architecture.',
        image: '🌉',
        imageUrl: 'https://images.unsplash.com/photo-1601614748197-2002d2fc59b6?w=800&q=80', // Placeholder
        rating: 4.8,
        duration: '1 hour',
        price: 'Free',
        highlights: ['Sea Views', 'Night Illumination', 'Photography'],
        tip: 'Beautiful at night when fully illuminated. A great spot for a walk.',
        lat: 31.2355,
        lng: 29.9482,
    },
    {
        id: 2015,
        name: 'قصر وحدائق المنتزه',
        nameEn: 'Montaza Palace and Gardens',
        city: 'الإسكندرية',
        cityEn: 'Alexandria',
        category: 'Nature',
        description: 'مجمع ملكي سابق يتميز بحدائق واسعة وشواطئ هادئة وقصور فخمة.',
        descriptionEn: 'A former royal complex featuring extensive gardens, quiet beaches, and lavish palaces.',
        image: '🌲',
        imageUrl: 'https://images.unsplash.com/photo-1589808608453-61b6c0054371?w=800&q=80', // Placeholder
        rating: 4.7,
        duration: '3-4 hours',
        price: '25 EGP',
        highlights: ['Royal Gardens', 'Al Haramlik Palace', 'Private Beaches'],
        tip: 'Great for a family picnic. The main palace is closed to the public but the gardens are beautiful.',
        lat: 31.2889,
        lng: 30.0152,
    },
    {
        id: 2016,
        name: 'المسرح الروماني',
        nameEn: 'Roman Amphitheatre',
        city: 'الإسكندرية',
        cityEn: 'Alexandria',
        category: 'Pharaonic', // Greco-Roman fits best here or Cultural
        description: 'المسرح الروماني الوحيد في مصر، يضم مدرجات رخامية وفيلات رومانية مزينة بالفسيفساء.',
        descriptionEn: 'The only Roman amphitheatre in Egypt, featuring marble seating and mosaic-decorated villas.',
        image: '🏛️',
        imageUrl: 'https://images.unsplash.com/photo-1600521605338-9cb525996b27?w=800&q=80',
        rating: 4.6,
        duration: '1-2 hours',
        price: '80 EGP',
        highlights: ['Marble Amphitheatre', 'Villa of the Birds', 'Ancient Baths'],
        tip: 'Don\'t miss the "Villa of the Birds" nearby which has excellently preserved mosaics.',
        lat: 31.1945,
        lng: 29.9052,
    },
    {
        id: 2017,
        name: 'مقابر كوم الشقافة',
        nameEn: 'Catacombs of Kom el Shoqafa',
        city: 'الإسكندرية',
        cityEn: 'Alexandria',
        category: 'Pharaonic',
        description: 'إحدى عجائب الدنيا في العصور الوسطى، مقابر تحت الأرض تدمج الفن المصري واليوناني والروماني.',
        descriptionEn: 'A medieval wonder of the world, underground tombs blending Egyptian, Greek, and Roman art.',
        image: '🏺',
        imageUrl: 'https://images.unsplash.com/photo-1596767527632-40f0c0557262?w=800&q=80',
        rating: 4.8,
        duration: '1-2 hours',
        price: '80 EGP',
        highlights: ['Underground Tombs', 'Mixed Art Styles', 'Spiral Staircase'],
        tip: 'Photography inside the catacombs is usually restricted or requires an extra ticket.',
        lat: 31.1786,
        lng: 29.8931,
    },

    // --- SHARM EL SHEIKH (Additional) ---
    {
        id: 2018,
        name: 'خليج نعمة',
        nameEn: 'Naama Bay',
        city: 'شرم الشيخ',
        cityEn: 'Sharm El Sheikh',
        category: 'Beach',
        description: 'المركز النابض بالحياة في شرم الشيخ، يمتلئ بالشواطئ الرملية والمقاهي والمطاعم.',
        descriptionEn: 'The vibrant center of Sharm, filled with sandy beaches, cafes, and restaurants.',
        image: '⛱️',
        imageUrl: 'https://images.unsplash.com/photo-1510414842594-a61c69b5ae57?w=800&q=80',
        rating: 4.7,
        duration: '3-5 hours',
        price: 'Free',
        highlights: ['Sandy Beach', 'Water Sports', 'Nightlife Nearby'],
        tip: 'Great for a walk in the evening. The beaches here are gently sloping, good for kids.',
        lat: 27.9150,
        lng: 34.3300,
    },
    {
        id: 2019,
        name: 'جزيرة تيران',
        nameEn: 'Tiran Island',
        city: 'شرم الشيخ',
        cityEn: 'Sharm El Sheikh',
        category: 'Diving',
        description: 'جزيرة تتميز بمياه فيروزية وشعاب مرجانية خلابة، وجهة مثالية للغوص والغطس.',
        descriptionEn: 'An island featuring turquoise waters and stunning coral reefs, an ideal diving and snorkeling destination.',
        image: '🤿',
        imageUrl: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800&q=80',
        rating: 4.9,
        duration: 'Full Day',
        price: '800 EGP',
        highlights: ['Boat Trip', 'Snorkeling', 'Shipwrecks'],
        tip: 'Book a full-day boat trip. Keep an eye out for dolphins on the way!',
        lat: 27.9500,
        lng: 34.5500,
    },
    {
        id: 2020,
        name: 'محمية نبق',
        nameEn: 'Nabq Nature Reserve',
        city: 'شرم الشيخ',
        cityEn: 'Sharm El Sheikh',
        category: 'Nature',
        description: 'محمية طبيعية خلابة تجمع بين أشجار المانجروف والصحراء والشعاب المرجانية.',
        descriptionEn: 'A beautiful nature reserve combining mangrove forests, desert, and coral reefs.',
        image: '🌳',
        imageUrl: 'https://images.unsplash.com/photo-1534063859666-0797175bb8d8?w=800&q=80',
        rating: 4.6,
        duration: '4-6 hours',
        price: '50 EGP',
        highlights: ['Mangrove Forests', 'Bird Watching', 'Quiet Beaches'],
        tip: 'Hire a local Bedouin guide to show you the best spots. Great for off-roading.',
        lat: 28.2167,
        lng: 34.4167,
    },
    
    // --- HURGHADA (Additional) ---
    {
        id: 2021,
        name: 'أكواريوم الغردقة',
        nameEn: 'Hurghada Grand Aquarium',
        city: 'الغردقة',
        cityEn: 'Hurghada',
        category: 'Cultural',
        description: 'أحد أكبر أحواض السمك في أفريقيا، يضم نفقاً مائياً ومجموعة متنوعة من أسماك البحر الأحمر.',
        descriptionEn: 'One of Africa\'s largest aquariums, featuring a glass tunnel and diverse Red Sea marine life.',
        image: '🐟',
        imageUrl: 'https://images.unsplash.com/photo-1582967788606-a171c1080cb0?w=800&q=80',
        rating: 4.5,
        duration: '2-3 hours',
        price: '300 EGP',
        highlights: ['Glass Tunnel', 'Shark Feeding', 'Mini Zoo'],
        tip: 'Great for families with children. Try to catch the scheduled feeding times.',
        lat: 27.1400,
        lng: 33.8200,
    },
    {
        id: 2022,
        name: 'مارينا الغردقة',
        nameEn: 'Hurghada Marina',
        city: 'الغردقة',
        cityEn: 'Hurghada',
        category: 'Cultural',
        description: 'ممشى راقٍ مليء باليخوت الفاخرة والمقاهي والمطاعم المتنوعة.',
        descriptionEn: 'An upscale promenade lined with luxury yachts, cafes, and diverse restaurants.',
        image: '⛵',
        imageUrl: 'https://images.unsplash.com/photo-1580974582391-a6649c82a85f?w=800&q=80', // Placeholder
        rating: 4.7,
        duration: '2-3 hours',
        price: 'Free',
        highlights: ['Yacht Views', 'Fine Dining', 'Evening Walk'],
        tip: 'The best place in Hurghada for a nice dinner by the water.',
        lat: 27.2300,
        lng: 33.8400,
    },

    // --- FAYOUM (Additional) ---
    {
        id: 2023,
        name: 'وادي الحيتان',
        nameEn: 'Wadi El Hitan (Whale Valley)',
        city: 'الفيوم',
        cityEn: 'Fayoum',
        category: 'Nature',
        description: 'موقع تراث عالمي يضم حفريات قيمة لحيتان منقرضة وسط تكوينات صخرية مذهلة.',
        descriptionEn: 'A UNESCO World Heritage site containing invaluable fossils of extinct whales amidst stunning rock formations.',
        image: '🐋',
        imageUrl: 'https://images.unsplash.com/photo-1626074966468-450ef7583626?w=800&q=80',
        rating: 4.9,
        duration: '4-5 hours',
        price: '40 EGP',
        highlights: ['Whale Fossils', 'Open Air Museum', 'Desert Landscape'],
        tip: 'Best visited with a 4x4 from Tunis Village. Combine it with the Magic Lake.',
        lat: 29.2667,
        lng: 30.0500,
    },
    {
        id: 2024,
        name: 'شلالات وادي الريان',
        nameEn: 'Wadi El Rayan Waterfalls',
        city: 'الفيوم',
        cityEn: 'Fayoum',
        category: 'Nature',
        description: 'الشلالات الطبيعية الوحيدة في مصر، تربط بين بحيرتين في قلب الصحراء.',
        descriptionEn: 'The only natural waterfalls in Egypt, connecting two lakes in the heart of the desert.',
        image: '🌊',
        imageUrl: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800&q=80',
        rating: 4.6,
        duration: '2-3 hours',
        price: '20 EGP',
        highlights: ['Waterfalls', 'Lake Views', 'Bird Watching'],
        tip: 'Can be crowded on national holidays. Try to visit on a weekday.',
        lat: 29.1333,
        lng: 30.4000,
    },

    // --- AIN SOKHNA ---
    {
        id: 2025,
        name: 'جبل الجلالة',
        nameEn: 'Galala Mountain',
        city: 'العين السخنة',
        cityEn: 'Ain Sokhna',
        category: 'Nature',
        description: 'منتجع جبلي شاهق يوفر تلفريك وإطلالات مذهلة على البحر الأحمر.',
        descriptionEn: 'A towering mountain resort offering a cable car ride and stunning Red Sea views.',
        image: '🚠',
        imageUrl: 'https://images.unsplash.com/photo-1534063859666-0797175bb8d8?w=800&q=80',
        rating: 4.7,
        duration: '3-4 hours',
        price: 'Variable',
        highlights: ['Cable Car', 'Sea View', 'Modern Marina'],
        tip: 'Take the cable car at sunset for the most magical views.',
        lat: 29.3800,
        lng: 32.3200,
    },

    // --- ISMAILIA ---
    {
        id: 2026,
        name: 'بحيرة التمساح',
        nameEn: 'Lake Timsah',
        city: 'الإسماعيلية',
        cityEn: 'Ismailia',
        category: 'Nature',
        description: 'بحيرة هادئة تشكل جزءاً من قناة السويس، مثالية للاسترخاء ومشاهدة السفن.',
        descriptionEn: 'A peaceful lake forming part of the Suez Canal, perfect for relaxing and ship watching.',
        image: '🦆',
        imageUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&q=80',
        rating: 4.5,
        duration: '2-3 hours',
        price: 'Free',
        highlights: ['Ship Watching', 'Seafood', 'Quiet Clubs'],
        tip: 'Have lunch at one of the lakeside clubs while watching giant ships pass by.',
        lat: 30.5667,
        lng: 32.2833,
    },

    // --- PORT SAID ---
    {
        id: 2027,
        name: 'ممشى ديليسبس',
        nameEn: 'De Lesseps Promenade',
        city: 'بورسعيد',
        cityEn: 'Port Said',
        category: 'Cultural',
        description: 'ممشى جميل على مدخل قناة السويس يتميز بالمباني ذات الطراز المعماري الأوروبي القديم.',
        descriptionEn: 'A beautiful promenade at the entrance of the Suez Canal featuring old European architecture.',
        image: '🛳️',
        imageUrl: 'https://images.unsplash.com/photo-1601614748197-2002d2fc59b6?w=800&q=80',
        rating: 4.6,
        duration: '1-2 hours',
        price: 'Free',
        highlights: ['Canal View', 'Old Architecture', 'Ferry Ride'],
        tip: 'Take the free ferry across to Port Fouad to feed the seagulls mid-crossing.',
        lat: 31.2653,
        lng: 32.3019,
    }
];
