export const HOTELS = [
    // --- LUXURY HOTELS ---
    {
        id: 1,
        name: 'Four Seasons Cairo at Nile Plaza',
        city: 'Cairo',
        category: 'luxury',
        rating: 4.9,
        price: 12500,
        image: 'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=800&q=80',
        amenities: ['Nile View', 'Rooftop Pool', 'Luxury Spa', 'Fine Dining'],
    },
    {
        id: 2,
        name: 'The Ritz-Carlton, Cairo',
        city: 'Cairo',
        category: 'luxury',
        rating: 4.8,
        price: 11000,
        image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=800&q=80',
        amenities: ['Nile View', 'Outdoor Pool', 'Historic Setting'],
    },
    {
        id: 3,
        name: 'Steigenberger Alcazar',
        city: 'Sharm El Sheikh',
        category: 'luxury',
        rating: 4.9,
        price: 9800,
        image: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=800&q=80',
        amenities: ['Ultra All-Inclusive', 'Private Beach', 'Multiple Pools'],
    },
    {
        id: 4,
        name: 'Lazib Inn Resort & Spa',
        city: 'Fayoum',
        category: 'luxury',
        rating: 4.9,
        price: 7500,
        image: 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?auto=format&fit=crop&w=800&q=80',
        amenities: ['Boutique Design', 'Desert View', 'Premium Spa'],
    },
    {
        id: 5,
        name: 'Rixos Sharm El Sheikh',
        city: 'Sharm El Sheikh',
        category: 'luxury',
        rating: 4.9,
        price: 11500,
        image: 'https://images.unsplash.com/photo-1544124499-183636bc9d9d?auto=format&fit=crop&w=800&q=80',
        amenities: ['Adults Only', 'Ultra Luxury', 'Gourmet Dining'],
    },
    {
        id: 6,
        name: 'Sofitel Legend Old Cataract',
        city: 'Aswan',
        category: 'luxury',
        rating: 4.9,
        price: 14000,
        image: 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?auto=format&fit=crop&w=800&q=80',
        amenities: ['Historic Palace', 'Nile View', 'Royal Suite'],
    },
    {
        id: 7,
        name: 'Marriott Mena House',
        city: 'Giza',
        category: 'luxury',
        rating: 4.8,
        price: 9000,
        image: 'https://images.unsplash.com/photo-1512918766671-ad650b9b732d?auto=format&fit=crop&w=800&q=80',
        amenities: ['Pyramids View', 'Historic Garden', 'Outdoor Pool'],
    },

    // --- MID-RANGE HOTELS ---
    {
        id: 50,
        name: 'Kempinski Nile Hotel',
        city: 'Cairo',
        category: 'mid-range',
        rating: 4.6,
        price: 5500,
        image: 'https://images.unsplash.com/photo-1564501049412-61c2a3083791?auto=format&fit=crop&w=800&q=80',
        amenities: ['Nile View', 'Pool', 'Business Center'],
    },
    {
        id: 51,
        name: 'Mercure Hurghada Hotel',
        city: 'Hurghada',
        category: 'mid-range',
        rating: 4.3,
        price: 3200,
        image: 'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?auto=format&fit=crop&w=800&q=80',
        amenities: ['Beach Access', 'Pool', 'Restaurant'],
    },

    // --- HOSTELS & BUDGET ---
    {
        id: 101,
        name: 'Life Pyramids Inn',
        city: 'Giza',
        category: 'hostel',
        rating: 4.7,
        price: 1800,
        image: 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?auto=format&fit=crop&w=800&q=80',
        amenities: ['Pyramids View', 'Rooftop Breakfast', 'Airport Shuttle'],
    },
    {
        id: 102,
        name: 'Marvel Stone Hotel',
        city: 'Giza',
        category: 'hostel',
        rating: 4.3,
        price: 1200,
        image: 'https://images.unsplash.com/photo-1560185007-c5ca9d2c014d?auto=format&fit=crop&w=800&q=80',
        amenities: ['Sphinx View', 'Rooftop Terrace', 'Budget Friendly'],
    },
    {
        id: 201,
        name: 'Heritage Hostel Cairo',
        city: 'Cairo',
        category: 'hostel',
        rating: 4.6,
        price: 600,
        image: 'https://images.unsplash.com/photo-1555854877-bab0e564b8d5?auto=format&fit=crop&w=800&q=80',
        amenities: ['Social Vibe', 'City Center', 'Shared Kitchen'],
    },
    {
        id: 202,
        name: 'Cairo Hub',
        city: 'Cairo',
        category: 'hostel',
        rating: 4.5,
        price: 750,
        image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=800&q=80',
        amenities: ['Modern Design', 'Near Zamalek', 'WiFi'],
    },
    {
        id: 301,
        name: 'Rafiki Hostels - Dahab',
        city: 'Dahab',
        category: 'hostel',
        rating: 4.8,
        price: 1500,
        image: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=800&q=80',
        amenities: ['Pool', 'Garden', 'Social Events'],
    },
    {
        id: 302,
        name: 'Basata Eco-Lodge',
        city: 'Nuweiba',
        category: 'budget',
        rating: 4.9,
        price: 1200,
        image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?auto=format&fit=crop&w=800&q=80',
        amenities: ['Eco-Friendly', 'Private Beach', 'Peaceful'],
    },
    {
        id: 303,
        name: 'Beit Tolba',
        city: 'Nuweiba',
        category: 'budget',
        rating: 4.8,
        price: 2500,
        image: 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?auto=format&fit=crop&w=800&q=80',
        amenities: ['Sea View', 'Home Cooked Meals', 'Authentic'],
    },
    {
        id: 401,
        name: 'Ithaka Hostel',
        city: 'Alexandria',
        category: 'hostel',
        rating: 4.7,
        price: 800,
        image: 'https://images.unsplash.com/photo-1467269204594-9661b134dd2b?auto=format&fit=crop&w=800&q=80',
        amenities: ['Artistic Decor', 'Central', 'Friendly Staff'],
    },
    {
        id: 501,
        name: 'Pajama Hostel Nile View',
        city: 'Aswan',
        category: 'hostel',
        rating: 4.6,
        price: 1000,
        image: 'https://images.unsplash.com/photo-1508739773434-c26b3d09e071?auto=format&fit=crop&w=800&q=80',
        amenities: ['Nile View', 'Elephantine Island', 'Nubian Style'],
    },
    {
        id: 502,
        name: 'Kato Dool',
        city: 'Aswan',
        category: 'budget',
        rating: 4.9,
        price: 1800,
        image: 'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=800&q=80',
        amenities: ['Nubian House', 'River Access', 'Traditional'],
    },
    {
        id: 601,
        name: 'Sofia Guest House',
        city: 'Luxor',
        category: 'budget',
        rating: 4.5,
        price: 800,
        image: 'https://images.unsplash.com/photo-1568084680786-a84f91d1153c?auto=format&fit=crop&w=800&q=80',
        amenities: ['Pool', 'East Bank', 'Quiet'],
    },
    {
        id: 602,
        name: 'Bob Marley Peace Hotel',
        city: 'Luxor',
        category: 'hostel',
        rating: 4.2,
        price: 400,
        image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=80',
        amenities: ['Social Vibe', 'West Bank', 'Rooftop'],
    },
];
