export const HOTELS = [
    // --- LUXURY HOTELS ---
    {
        id: 1,
        name: 'Four Seasons Cairo at Nile Plaza',
        city: 'Cairo',
        category: 'luxury',
        rating: 4.9,
        price: 12500,
        image: 'https://via.placeholder.com/800x400?text=No+Image+Available',
        amenities: ['Nile View', 'Rooftop Pool', 'Luxury Spa', 'Fine Dining'],
    },
    {
        id: 2,
        name: 'The Ritz-Carlton, Cairo',
        city: 'Cairo',
        category: 'luxury',
        rating: 4.8,
        price: 11000,
        image: 'https://via.placeholder.com/800x400?text=No+Image+Available',
        amenities: ['Nile View', 'Outdoor Pool', 'Historic Setting'],
    },
    {
        id: 3,
        name: 'Steigenberger Alcazar',
        city: 'Sharm El Sheikh',
        category: 'luxury',
        rating: 4.9,
        price: 9800,
        image: 'https://via.placeholder.com/800x400?text=No+Image+Available',
        amenities: ['Ultra All-Inclusive', 'Private Beach', 'Multiple Pools'],
    },
    {
        id: 4,
        name: 'Lazib Inn Resort & Spa',
        city: 'Fayoum',
        category: 'luxury',
        rating: 4.9,
        price: 7500,
        image: 'https://via.placeholder.com/800x400?text=No+Image+Available',
        amenities: ['Boutique Design', 'Desert View', 'Premium Spa'],
    },
    {
        id: 5,
        name: 'Rixos Sharm El Sheikh',
        city: 'Sharm El Sheikh',
        category: 'luxury',
        rating: 4.9,
        price: 11500,
        image: 'https://via.placeholder.com/800x400?text=No+Image+Available',
        amenities: ['Adults Only', 'Ultra Luxury', 'Gourmet Dining'],
    },
    {
        id: 6,
        name: 'Sofitel Legend Old Cataract',
        city: 'Aswan',
        category: 'luxury',
        rating: 4.9,
        price: 14000,
        image: 'https://via.placeholder.com/800x400?text=No+Image+Available',
        amenities: ['Historic Palace', 'Nile View', 'Royal Suite'],
    },
    {
        id: 7,
        name: 'Marriott Mena House',
        city: 'Giza',
        category: 'luxury',
        rating: 4.8,
        price: 9000,
        image: 'https://via.placeholder.com/800x400?text=No+Image+Available',
        amenities: ['Pyramids View', 'Historic Garden', 'Outdoor Pool'],
    },

    // --- MID-RANGE HOTELS ---
    {
        id: 50,
        name: 'Kempinski Nile Hotel',
        city: 'Cairo',
        category: 'mid-range',
        rating: 4.6,
        price: 5500,
        image: 'https://via.placeholder.com/800x400?text=No+Image+Available',
        amenities: ['Nile View', 'Pool', 'Business Center'],
    },
    {
        id: 51,
        name: 'Mercure Hurghada Hotel',
        city: 'Hurghada',
        category: 'mid-range',
        rating: 4.3,
        price: 3200,
        image: 'https://via.placeholder.com/800x400?text=No+Image+Available',
        amenities: ['Beach Access', 'Pool', 'Restaurant'],
    },

    // --- HOSTELS & BUDGET ---
    {
        id: 101,
        name: 'Life Pyramids Inn',
        city: 'Giza',
        category: 'hostel',
        rating: 4.7,
        price: 1800,
        image: 'https://via.placeholder.com/800x400?text=No+Image+Available',
        amenities: ['Pyramids View', 'Rooftop Breakfast', 'Airport Shuttle'],
    },
    {
        id: 102,
        name: 'Marvel Stone Hotel',
        city: 'Giza',
        category: 'hostel',
        rating: 4.3,
        price: 1200,
        image: 'https://via.placeholder.com/800x400?text=No+Image+Available',
        amenities: ['Sphinx View', 'Rooftop Terrace', 'Budget Friendly'],
    },
    {
        id: 201,
        name: 'Heritage Hostel Cairo',
        city: 'Cairo',
        category: 'hostel',
        rating: 4.6,
        price: 600,
        image: 'https://via.placeholder.com/800x400?text=No+Image+Available',
        amenities: ['Social Vibe', 'City Center', 'Shared Kitchen'],
    },
    {
        id: 202,
        name: 'Cairo Hub',
        city: 'Cairo',
        category: 'hostel',
        rating: 4.5,
        price: 750,
        image: 'https://via.placeholder.com/800x400?text=No+Image+Available',
        amenities: ['Modern Design', 'Near Zamalek', 'WiFi'],
    },
    {
        id: 301,
        name: 'Rafiki Hostels - Dahab',
        city: 'Dahab',
        category: 'hostel',
        rating: 4.8,
        price: 1500,
        image: 'https://via.placeholder.com/800x400?text=No+Image+Available',
        amenities: ['Pool', 'Garden', 'Social Events'],
    },
    {
        id: 302,
        name: 'Basata Eco-Lodge',
        city: 'Nuweiba',
        category: 'budget',
        rating: 4.9,
        price: 1200,
        image: 'https://via.placeholder.com/800x400?text=No+Image+Available',
        amenities: ['Eco-Friendly', 'Private Beach', 'Peaceful'],
    },
    {
        id: 303,
        name: 'Beit Tolba',
        city: 'Nuweiba',
        category: 'budget',
        rating: 4.8,
        price: 2500,
        image: 'https://via.placeholder.com/800x400?text=No+Image+Available',
        amenities: ['Sea View', 'Home Cooked Meals', 'Authentic'],
    },
    {
        id: 401,
        name: 'Ithaka Hostel',
        city: 'Alexandria',
        category: 'hostel',
        rating: 4.7,
        price: 800,
        image: 'https://via.placeholder.com/800x400?text=No+Image+Available',
        amenities: ['Artistic Decor', 'Central', 'Friendly Staff'],
    },
    {
        id: 501,
        name: 'Pajama Hostel Nile View',
        city: 'Aswan',
        category: 'hostel',
        rating: 4.6,
        price: 1000,
        image: 'https://via.placeholder.com/800x400?text=No+Image+Available',
        amenities: ['Nile View', 'Elephantine Island', 'Nubian Style'],
    },
    {
        id: 502,
        name: 'Kato Dool',
        city: 'Aswan',
        category: 'budget',
        rating: 4.9,
        price: 1800,
        image: 'https://via.placeholder.com/800x400?text=No+Image+Available',
        amenities: ['Nubian House', 'River Access', 'Traditional'],
    },
    {
        id: 601,
        name: 'Sofia Guest House',
        city: 'Luxor',
        category: 'budget',
        rating: 4.5,
        price: 800,
        image: 'https://via.placeholder.com/800x400?text=No+Image+Available',
        amenities: ['Pool', 'East Bank', 'Quiet'],
    },
    {
        id: 602,
        name: 'Bob Marley Peace Hotel',
        city: 'Luxor',
        category: 'hostel',
        rating: 4.2,
        price: 400,
        image: 'https://via.placeholder.com/800x400?text=No+Image+Available',
        amenities: ['Social Vibe', 'West Bank', 'Rooftop'],
    },
];
