export const NUWEIBA_TABA_DATA = [
    {
        id: 'nuw-1',
        name: 'رأس شيطان',
        nameEn: 'Ras Shitan',
        city: 'نويبع',
        cityEn: 'Nuweiba',
        category: 'Beach',
        description: 'كامبات خشبية على الشاطئ مباشرة مع شعاب مرجانية قريبة ونجوم ساطعة.',
        descriptionEn: 'Wooden camps right on the beach with nearby coral reefs and bright stars.',
        image: '🏕️',
        rating: 4.8,
        lat: 29.1350,
        lng: 34.6850,
    },
    {
        id: 'taba-1',
        name: 'جزيرة فرعون',
        nameEn: "Pharaoh's Island",
        city: 'طابا',
        cityEn: 'Taba',
        category: 'Historical',
        description: 'قلعة صلاح الدين الحجرية محاطة بمياه البحر العميقة.',
        descriptionEn: 'Saladin Citadel surrounded entirely by the deep blue waters.',
        image: '🏰',
        rating: 4.9,
        lat: 29.4920,
        lng: 34.8620,
    },
    {
        id: 'taba-2',
        name: 'فيورد باي',
        nameEn: 'Fjord Bay',
        city: 'طابا',
        cityEn: 'Taba',
        category: 'Nature',
        description: 'خليج ساحر بلون أزرق داكن محاط بجبال سيناء الشاهقة.',
        descriptionEn: 'A magical deep blue bay surrounded by towering Sinai mountains.',
        image: '🌊',
        rating: 4.9,
        lat: 29.3800,
        lng: 34.8250,
    },
    {
        id: 'nuw-2',
        name: 'بساطة إيكو لودج',
        nameEn: 'Basata Eco-Lodge',
        city: 'نويبع',
        cityEn: 'Nuweiba',
        category: 'Beach',
        description: 'منتجع بيئي بسيط وهادئ جداً مبني من الخيزران على البحر.',
        descriptionEn: 'A quiet, eco-friendly lodge built from bamboo on the sea.',
        image: '🌴',
        rating: 4.9,
        lat: 29.1000,
        lng: 34.6700,
    },
    {
        id: 'nuw-3',
        name: 'دايرا كامب',
        nameEn: 'Dayra Camp',
        city: 'نويبع',
        cityEn: 'Nuweiba',
        category: 'Nightlife',
        description: 'كامب بأجواء شبابية وألوان مبهجة على رمال البحر.',
        descriptionEn: 'A boho-style beachfront camp with a young, vibrant vibe.',
        image: '✨',
        rating: 4.8,
        lat: 29.0800,
        lng: 34.6600,
    }
];
