export const NEW_PLACES = [
    // --- DAHAB ---
    {
        id: 901,
        name: 'الثقب الأزرق (بلو هول)',
        nameEn: 'Blue Hole',
        city: 'دهب',
        cityEn: 'Dahab',
        category: 'Diving',
        description: 'أشهر موقع للغوص في العالم، عمق مخيف وشعاب مرجانية مذهلة.',
        descriptionEn: 'World-famous diving site known for its depth and stunning coral reefs.',
        image: require('../../assets/real_images/blue_hole.jpg'),
        imageUrl: '',
        rating: 4.9,
        duration: 'Half Day',
        price: 'Free / Gear Rental',
        highlights: ['Diving', 'Freediving', 'Corals'],
        tip: 'احذر من التيارات وتأكد من الغوص مع مرشد محترف.',
        lat: 28.5714,
        lng: 34.5369,
    },
    {
        id: 902,
        name: 'محمية أبو جالوم',
        nameEn: 'Abu Galoum',
        city: 'دهب',
        cityEn: 'Dahab',
        category: 'Nature',
        description: 'محمية طبيعية خلابة تجمع بين الجبال والبحر.',
        descriptionEn: 'A stunning nature reserve combining mountains and the sea.',
        image: require('../../assets/real_images/abu_galoum.jpg'),
        imageUrl: '',
        rating: 4.8,
        duration: 'Full Day',
        price: 'Variable',
        highlights: ['Hiking', 'Camel Ride', 'Snorkeling'],
        tip: 'يمكن الوصول إليها بالجمال أو القوارب السريعة من البلو هول.',
        lat: 28.6667,
        lng: 34.5333,
    },
    {
        id: 903,
        name: 'الثري بولز',
        nameEn: 'Three Pools',
        city: 'دهب',
        cityEn: 'Dahab',
        category: 'Snorkeling',
        description: 'ثلاثة حمامات سباحة طبيعية متصلة بالشعاب المرجانية.',
        descriptionEn: 'Three natural pools connected by coral reefs, perfect for snorkeling.',
        image: require('../../assets/real_images/seafood.jpg'), 
        imageUrl: '',
        rating: 4.7,
        duration: '3-4 hours',
        price: 'Free',
        highlights: ['Snorkeling', 'Relaxing', 'Corals'],
        tip: 'أفضل وقت للزيارة في الصباح الباكر لروية الأسماك بوضوح.',
        lat: 28.4231,
        lng: 34.4561,
    },
    {
        id: 904,
        name: 'جبل الطويلات',
        nameEn: 'Gabal El Towaylat',
        city: 'دهب',
        cityEn: 'Dahab',
        category: 'Nightlife',
        description: 'سهرات بدوية تحت النجوم مع شاي وحفلات غنائية.',
        descriptionEn: 'Bedouin nights under the stars with tea and music.',
        image: require('../../assets/real_images/ras_shitan.jpg'),
        imageUrl: '',
        rating: 4.6,
        duration: 'Evening',
        price: '150 EGP',
        highlights: ['Stargazing', 'Bedouin Tea', 'Music'],
        tip: 'مكان مثالي للاسترخاء ليلاً بعيداً عن أضواء المدينة.',
        lat: 28.5021,
        lng: 34.4890,
    },
    
    // --- NUWEIBA & TABA ---
    {
        id: 1001,
        name: 'رأس شيطان',
        nameEn: 'Ras Shitan',
        city: 'نويبع',
        cityEn: 'Nuweiba',
        category: 'Nature',
        description: 'المنطقة الأشهر للكامبات البدوية والاسترخاء التام على البحر.',
        descriptionEn: 'The most famous area for Bedouin camps and total relaxation by the sea.',
        image: require('../../assets/real_images/ras_shitan.jpg'),
        imageUrl: '',
        rating: 4.8,
        duration: 'Full Day',
        price: 'Free (Pay at Camps)',
        highlights: ['Camping', 'Stargazing', 'Snorkeling'],
        tip: 'انفصل عن التكنولوجيا واستمتع بالهدوء التام.',
        lat: 29.1350,
        lng: 34.6850,
    },
    {
        id: 1002,
        name: 'قلعة صلاح الدين بجزيرة فرعون',
        nameEn: 'Pharaoh\'s Island Citadel',
        city: 'طابا',
        cityEn: 'Taba',
        category: 'Historical',
        description: 'قلعة تاريخية وسط البحر بخلفية مذهلة للغوص.',
        descriptionEn: 'Historical citadel in the middle of the sea with a stunning background for diving.',
        image: require('../../assets/real_images/fjord_bay.jpg'),
        imageUrl: '',
        rating: 4.7,
        duration: '2-3 hours',
        price: '100 EGP',
        highlights: ['History', 'Sea Views', 'Boat Trip'],
        tip: 'تحتاج إلى قارب للوصول إلى الجزيرة.',
        lat: 29.3833,
        lng: 34.8600,
    },
    {
        id: 1003,
        name: 'فيورد باي',
        nameEn: 'Fjord Bay',
        city: 'طابا',
        cityEn: 'Taba',
        category: 'Nature',
        description: 'خليج ساحر محاط بالجبال، ممتاز للتصوير.',
        descriptionEn: 'A magical bay surrounded by mountains, excellent for photography.',
        image: require('../../assets/real_images/fjord_bay.jpg'),
        imageUrl: '',
        rating: 4.9,
        duration: '1-2 hours',
        price: 'Free',
        highlights: ['Photography', 'Snorkeling', 'Scenery'],
        tip: 'مكان رائع للتوقف لالتقاط الصور أثناء القيادة على طريق طابا.',
        lat: 29.3667,
        lng: 34.8333,
    },

    // --- MARSA MATROUH & NORTH COAST ---
    {
        id: 1101,
        name: 'شاطئ عجيبة',
        nameEn: 'Agiba Beach',
        city: 'مطروح',
        cityEn: 'Matrouh',
        category: 'Beach',
        description: 'شاطئ صخري بمياه متدرجة الألوان تخطف الأنفاس.',
        descriptionEn: 'Rocky beach with breathtaking gradient waters.',
        image: require('../../assets/real_images/agiba.jpg'),
        imageUrl: '',
        rating: 4.8,
        duration: '2-3 hours',
        price: 'Free',
        highlights: ['Scenery', 'Photography', 'Clear Water'],
        tip: 'مزدحم جداً في الصيف، حاول الزيارة مبكراً.',
        lat: 31.4167,
        lng: 27.0000,
    },
    {
        id: 1102,
        name: 'حمام كليوباترا',
        nameEn: 'Cleopatra Bath',
        city: 'مطروح',
        cityEn: 'Matrouh',
        category: 'Historical/Beach',
        description: 'صخرة مجوفة وسط البحر تتدفق إليها المياه.',
        descriptionEn: 'A hollow rock in the sea where water flows through.',
        image: require('../../assets/real_images/agiba.jpg'), 
        imageUrl: '',
        rating: 4.5,
        duration: '1-2 hours',
        price: 'Free',
        highlights: ['History Legend', 'Scenery'],
        tip: 'السباحة غير آمنة داخل الصخرة بسبب التيارات.',
        lat: 31.3700,
        lng: 27.1800,
    },
    {
        id: 1103,
        name: 'سيدي عبد الرحمن',
        nameEn: 'Sidi Abdel Rahman',
        city: 'الساحل',
        cityEn: 'North Coast',
        category: 'Beach',
        description: 'يضم أرقى القرى السياحية والشواطئ الرملية البيضاء.',
        descriptionEn: 'Home to the finest resorts and white sandy beaches.',
        image: require('../../assets/real_images/marassi.jpg'),
        imageUrl: '',
        rating: 4.9,
        duration: 'Full Day',
        price: 'Variable',
        highlights: ['Luxury Resorts', 'Nightlife', 'White Sand'],
        tip: 'تتركز هنا قرى مثل مراسي وهاسيندا.',
        lat: 30.9500,
        lng: 28.7167,
    },

    // --- RAS EL BAR ---
    {
        id: 1201,
        name: 'منطقة اللسان',
        nameEn: 'El Lessan',
        city: 'رأس البر',
        cityEn: 'Ras El Bar',
        category: 'Nature',
        description: 'نقطة التقاء نهر النيل بالبحر المتوسط.',
        descriptionEn: 'The meeting point of the Nile River and the Mediterranean Sea.',
        image: require('../../assets/real_images/lessan.jpg'),
        imageUrl: '',
        rating: 4.8,
        duration: '2-3 hours',
        price: 'Free',
        highlights: ['Sunset', 'Walking', 'Lighthouse'],
        tip: 'أفضل وقت لزيارتها هو وقت الغروب.',
        lat: 31.5167,
        lng: 31.8333,
    },
    {
        id: 1202,
        name: 'شارع النيل',
        nameEn: 'Nile Street',
        city: 'رأس البر',
        cityEn: 'Ras El Bar',
        category: 'Cultural',
        description: 'الممشى الرئيسي المليء بالمطاعم ومحلات الحلويات الدمياطية.',
        descriptionEn: 'The main promenade full of restaurants and Damietta sweet shops.',
        image: require('../../assets/real_images/sweets.jpg'),
        imageUrl: '',
        rating: 4.7,
        duration: 'Evening',
        price: 'Free',
        highlights: ['Sweets', 'Shopping', 'Nile View'],
        tip: 'لا تفوت تجربة المشبك الدمياطي الطازج هنا.',
        lat: 31.5100,
        lng: 31.8250,
    }
];

export const NEW_HOTELS_CAMPS = [
    // --- DAHAB CAMPS & HOSTELS ---
    {
        id: 20901,
        name: 'Rafiki Hostels',
        city: 'Dahab',
        category: 'hostel',
        rating: 4.8,
        price: 800,
        image: require('../../assets/real_images/rafiki_hostel.jpg'), 
        amenities: ['Pool', 'Social Vibe', 'Clean Rooms'],
    },
    {
        id: 20902,
        name: 'Penguin Village',
        city: 'Dahab',
        category: 'camp',
        rating: 4.6,
        price: 500,
        image: require('../../assets/real_images/rafiki_hostel.jpg'), 
        amenities: ['Sea View', 'Diving Center', 'Budget'],
    },
    {
        id: 20903,
        name: 'Seven Heaven Camp',
        city: 'Dahab',
        category: 'camp',
        rating: 4.5,
        price: 400,
        image: require('../../assets/real_images/rafiki_hostel.jpg'), 
        amenities: ['Backpackers', 'Diving', 'Central'],
    },
    {
        id: 20904,
        name: 'Le Méridien Dahab Resort',
        city: 'Dahab',
        category: 'luxury',
        rating: 4.8,
        price: 4500,
        image: require('../../assets/real_images/marassi.jpg'), 
        amenities: ['Private Beach', 'Multiple Pools', 'Luxury Spa'],
    },

    // --- NUWEIBA CAMPS ---
    {
        id: 21001,
        name: 'Basata Eco-Lodge',
        city: 'Nuweiba',
        category: 'camp',
        rating: 4.9,
        price: 1200,
        image: require('../../assets/real_images/basata_camp.jpg'), 
        amenities: ['Eco-Friendly', 'Silent Zone', 'Private Beach'],
    },
    {
        id: 21002,
        name: 'Dayra Camp',
        city: 'Nuweiba',
        category: 'camp',
        rating: 4.7,
        price: 900,
        image: require('../../assets/real_images/basata_camp.jpg'), 
        amenities: ['Boho Style', 'Music', 'Sea Front'],
    },
    {
        id: 21003,
        name: 'Rocksea Camp',
        city: 'Nuweiba',
        category: 'camp',
        rating: 4.8,
        price: 850,
        image: require('../../assets/real_images/basata_camp.jpg'), 
        amenities: ['Quiet', 'Snorkeling', 'Family Run'],
    },
    {
        id: 21004,
        name: 'Beit Tolba',
        city: 'Nuweiba',
        category: 'mid-range',
        rating: 4.9,
        price: 2500,
        image: require('../../assets/real_images/basata_camp.jpg'), 
        amenities: ['Home Cooked Meals', 'Luxury Camp', 'Sea View'],
    },

    // --- MATROUH & NORTH COAST ---
    {
        id: 21101,
        name: 'The Address Marassi Golf Resort',
        city: 'North Coast',
        category: 'luxury',
        rating: 4.9,
        price: 15000,
        image: require('../../assets/real_images/marassi.jpg'), 
        amenities: ['Golf Course', 'Ultra Luxury', 'Pools'],
    },
    {
        id: 21102,
        name: 'Jaz Almaza Beach Resort',
        city: 'Matrouh',
        category: 'luxury',
        rating: 4.8,
        price: 6000,
        image: require('../../assets/real_images/marassi.jpg'), 
        amenities: ['White Sand Beach', 'All-Inclusive', 'Family Friendly'],
    },
    {
        id: 21103,
        name: 'Carols Beau Rivage',
        city: 'Matrouh',
        category: 'mid-range',
        rating: 4.6,
        price: 4500,
        image: require('../../assets/real_images/marassi.jpg'), 
        amenities: ['Obayed Beach', 'Spa', 'Pool'],
    },

    // --- RAS EL BAR ---
    {
        id: 21201,
        name: 'Steigenberger Hotel El Lessan',
        city: 'Ras El Bar',
        category: 'luxury',
        rating: 4.9,
        price: 5500,
        image: require('../../assets/real_images/steigenberger_raselbar.jpg'), 
        amenities: ['Nile & Sea View', 'Luxury', 'Infinity Pool'],
    },
    {
        id: 21202,
        name: 'Dolphin Ras El Bar',
        city: 'Ras El Bar',
        category: 'mid-range',
        rating: 4.4,
        price: 2000,
        image: require('../../assets/real_images/steigenberger_raselbar.jpg'), 
        amenities: ['Nile View', 'Restaurant', 'Central'],
    }
];

export const NEW_DINING = [
    { id: 30901, name: "Ralph's German Bakery", city: "Dahab", cuisine: "Bakery/Breakfast", meal: "Breakfast", highlightDish: "Pretzels & Coffee", rating: 4.9, image: require('../../assets/real_images/sweets.jpg'), description: "أفضل مكان للإفطار والمخبوزات الطازجة في دهب." },
    { id: 30902, name: "Ali Baba", city: "Dahab", cuisine: "Seafood", meal: "Dinner", highlightDish: "Grilled Fish", rating: 4.7, image: require('../../assets/real_images/seafood.jpg'), description: "أشهر مطاعم الأسماك على ممشى دهب." },
    { id: 31001, name: "Magdy Seafood", city: "Matrouh", cuisine: "Seafood", meal: "Lunch/Dinner", highlightDish: "Fish & Rice", rating: 4.8, image: require('../../assets/real_images/seafood.jpg'), description: "أسطورة الأسماك في مرسى مطروح." },
    { id: 31002, name: "Sachi by the Sea", city: "North Coast", cuisine: "Fine Dining", meal: "Dinner", highlightDish: "Sushi & Steak", rating: 4.9, image: require('../../assets/real_images/seafood.jpg'), description: "تجربة طعام صيفية فاخرة في هاسيندا." },
    { id: 31201, name: "حلويات البدري", city: "Ras El Bar", cuisine: "Desserts", meal: "Any", highlightDish: "المشبك الدمياطي", rating: 4.9, image: require('../../assets/real_images/sweets.jpg'), description: "أشهر صانعي الحلويات الشرقية والمشبك في دمياط." },
    { id: 31202, name: "خلود النيل", city: "Ras El Bar", cuisine: "Seafood", meal: "Lunch/Dinner", highlightDish: "Mixed Seafood", rating: 4.7, image: require('../../assets/real_images/seafood.jpg'), description: "مطعم سمك شهير يطل على النيل مباشرة." }
];
