export const nightlifeData = [
    {
        id: 401,
        name: 'كايرو جاز كلوب',
        nameEn: 'Cairo Jazz Club',
        city: 'القاهرة',
        cityEn: 'Cairo',
        category: 'Nightlife',
        description: 'أشهر مكان للموسيقى الحية في القاهرة، يقدم عروضاً يومية من الجاز إلى الإلكترونيك.',
        descriptionEn: 'The legendary hub for live music in Cairo, featuring daily shows ranging from jazz to electronic.',
        image: '🎷',
        imageUrl: 'https://images.unsplash.com/photo-1514525253344-991c0575d04a?w=800&q=80',
        rating: 4.9,
        duration: '4-5 hours',
        price: 'Variable',
        highlights: ['Live Bands', 'Signature Cocktails', 'Iconic Vibe'],
        tip: 'Reservations are essential. Dress code is smart casual.',
        lat: 30.0558,
        lng: 31.2115,
    },
    {
        id: 402,
        name: 'ذا تاب',
        nameEn: 'The Tap',
        city: 'القاهرة',
        cityEn: 'Cairo',
        category: 'Nightlife',
        description: 'بار حيوي يشتهر بأجنحة الدجاج والموسيقى المتنوعة من الروك إلى الهيب هوب.',
        descriptionEn: 'A vibrant pub famous for its wings and diverse music nights, from rock to hip-hop.',
        image: '🍺',
        imageUrl: 'https://images.unsplash.com/photo-1514525253344-991c0575d04a?w=800&q=80',
        rating: 4.7,
        duration: '3-4 hours',
        price: 'Moderate',
        highlights: ['Arcade Games', 'Draft Beer', 'Themed Nights'],
        tip: 'Check their schedule for "Game Night" or "Retro Night".',
        lat: 29.9571,
        lng: 31.2581,
    },
    {
        id: 403,
        name: 'ستيج وان',
        nameEn: 'Stage One',
        city: 'القاهرة',
        cityEn: 'Cairo',
        category: 'Nightlife',
        description: 'لاونج فاخر يطل على النيل، يقدم مزيجاً من الموسيقى الشرقية والغربية.',
        descriptionEn: 'An upscale lounge overlooking the Nile, offering a blend of Oriental and Western music.',
        image: '🍸',
        imageUrl: 'https://images.unsplash.com/photo-1514525253344-991c0575d04a?w=800&q=80',
        rating: 4.8,
        duration: '4-5 hours',
        price: 'High',
        highlights: ['Nile View', 'Live Performance', 'Luxury Decor'],
        tip: 'Perfect for a sophisticated night out with a group.',
        lat: 30.0612,
        lng: 31.2285,
    },
    {
        id: 404,
        name: 'جينكو روفتوب',
        nameEn: 'Gingko Rooftop',
        city: 'القاهرة',
        cityEn: 'Cairo',
        category: 'Nightlife',
        description: 'روفتوب بار أنيق يتميز بإطلالة بانورامية على أفق القاهرة والنيل.',
        descriptionEn: 'A chic rooftop bar featuring panoramic views of the Cairo skyline and the Nile.',
        image: '🌇',
        imageUrl: 'https://images.unsplash.com/photo-1514525253344-991c0575d04a?w=800&q=80',
        rating: 4.8,
        duration: '3-4 hours',
        price: 'High',
        highlights: ['Sunset Views', 'Modern Cocktails', 'Outdoor Seating'],
        tip: 'Go just before sunset to catch the golden hour over the Nile.',
        lat: 30.0715,
        lng: 31.2268,
    },
    {
        id: 405,
        name: 'باب 28',
        nameEn: 'Pub 28',
        city: 'القاهرة',
        cityEn: 'Cairo',
        category: 'Nightlife',
        description: 'واحد من أقدم وأشهر البارات في الزمالك، يشتهر بجوه الكلاسيكي الدافئ.',
        descriptionEn: 'One of Cairo\'s oldest and most famous pubs in Zamalek, known for its warm, classic atmosphere.',
        image: '🍷',
        imageUrl: 'https://images.unsplash.com/photo-1514525253344-991c0575d04a?w=800&q=80',
        rating: 4.6,
        duration: '2-3 hours',
        price: 'Moderate',
        highlights: ['Classic Vibe', 'Steak Platter', 'Neighborhood Favorite'],
        tip: 'It gets very crowded on weekends; arrive early if you don\'t have a booking.',
        lat: 30.0615,
        lng: 31.2185,
    },
    {
        id: 406,
        name: 'فارشا كافيه',
        nameEn: 'Farsha Cafe',
        city: 'شرم الشيخ',
        cityEn: 'Sharm El Sheikh',
        category: 'Nightlife',
        description: 'أشهر كافيه بوهيمي في شرم الشيخ، يقع على جرف صخري ويقدم إطلالة ساحرة.',
        descriptionEn: 'The most famous bohemian cafe in Sharm, perched on a cliff with mesmerizing sea views.',
        image: '🏮',
        imageUrl: 'https://images.unsplash.com/photo-1514525253344-991c0575d04a?w=800&q=80',
        rating: 4.9,
        duration: '4-5 hours',
        price: 'Moderate',
        highlights: ['Bohemian Decor', 'Cliff View', 'Shisha & Drinks'],
        tip: 'Visit at night to see the lanterns lit up; it feels like a scene from 1001 Nights.',
        lat: 27.8624,
        lng: 34.3015,
    },
    {
        id: 407,
        name: 'أورورا',
        nameEn: 'Aurora',
        city: 'الجونة',
        cityEn: 'El Gouna',
        category: 'Nightlife',
        description: 'مزيج من لاونج كوكتيلات ونادي ليلي في قلب مارينا أبو تيج.',
        descriptionEn: 'A hybrid of a cocktail lounge and nightclub in the heart of Abu Tig Marina.',
        image: '✨',
        imageUrl: 'https://images.unsplash.com/photo-1514525253344-991c0575d04a?w=800&q=80',
        rating: 4.7,
        duration: '4-5 hours',
        price: 'High',
        highlights: ['Marina View', 'House Music', 'Stylish Crowd'],
        tip: 'Best for late night dancing after a nice dinner in Gouna.',
        lat: 27.3965,
        lng: 33.6821,
    },
    {
        id: 408,
        name: 'باشا شرم الشيخ',
        nameEn: 'Pacha Sharm',
        city: 'شرم الشيخ',
        cityEn: 'Sharm El Sheikh',
        category: 'Nightlife',
        description: 'فرع النادي العالمي الشهير، يقدم حفلات ضخمة مع أشهر الدي جي حول العالم.',
        descriptionEn: 'The Egyptian branch of the world-famous club, hosting massive parties with global DJs.',
        image: '🍒',
        imageUrl: 'https://images.unsplash.com/photo-1514525253344-991c0575d04a?w=800&q=80',
        rating: 4.8,
        duration: 'Full Night',
        price: 'High',
        highlights: ['Open Air Club', 'World-Class Sound', 'Summer Parties'],
        tip: 'Check their summer schedule for international DJ appearances.',
        lat: 27.9135,
        lng: 34.3218,
    },
    {
        id: 409,
        name: 'سبيس شرم',
        nameEn: 'Space Sharm',
        city: 'شرم الشيخ',
        cityEn: 'Sharm El Sheikh',
        category: 'Nightlife',
        description: 'نادي ليلي عملاق يطل على البحر، يتميز بتصميمه العصري وعروض الليزر.',
        descriptionEn: 'A giant nightclub overlooking the sea, featuring modern design and spectacular laser shows.',
        image: '🚀',
        imageUrl: 'https://images.unsplash.com/photo-1514525253344-991c0575d04a?w=800&q=80',
        rating: 4.7,
        duration: 'Full Night',
        price: 'High',
        highlights: ['Large Dance Floor', 'Sea View Terrace', 'Techno Nights'],
        tip: 'A must-visit for electronic music lovers in Sharm.',
        lat: 27.9254,
        lng: 34.3365,
    },
    {
        id: 410,
        name: 'ليتل بوذا',
        nameEn: 'Little Buddha',
        city: 'الغردقة',
        cityEn: 'Hurghada',
        category: 'Nightlife',
        description: 'مطعم وسهرة فاخرة يجمع بين الأكل الآسيوي والأجواء الموسيقية الراقية.',
        descriptionEn: 'A luxury dining and nightlife spot combining Asian cuisine with upscale musical vibes.',
        image: '🏮',
        imageUrl: 'https://images.unsplash.com/photo-1514525253344-991c0575d04a?w=800&q=80',
        rating: 4.8,
        duration: '4-5 hours',
        price: 'High',
        highlights: ['Asian Fusion', 'Buddha Statue', 'Classy Bar'],
        tip: 'The sushi here is excellent, followed by a great bar scene after 11 PM.',
        lat: 27.1854,
        lng: 33.8214,
    },
    {
        id: 411,
        name: 'سي جيه سي 610',
        nameEn: 'CJC 610',
        city: 'الشيخ زايد',
        cityEn: 'Sheikh Zayed',
        category: 'Nightlife',
        description: 'النسخة الأكبر والأحدث من كايرو جاز كلوب، مساحة واسعة وتراس رائع.',
        descriptionEn: 'The larger, newer version of Cairo Jazz Club with a spacious indoor area and a great terrace.',
        image: '🎶',
        imageUrl: 'https://images.unsplash.com/photo-1514525253344-991c0575d04a?w=800&q=80',
        rating: 4.9,
        duration: '4-5 hours',
        price: 'High',
        highlights: ['Outdoor Terrace', 'Big Stage', 'Craft Cocktails'],
        tip: 'Their brunch on weekends is also very popular.',
        lat: 30.0125,
        lng: 30.9854,
    },
    {
        id: 412,
        name: 'راوي',
        nameEn: 'Rawi',
        city: 'القاهرة',
        cityEn: 'Cairo',
        category: 'Nightlife',
        description: 'سهرة شرقية فاخرة في فندق الريتز كارلتون، تجمع بين الموسيقى الحية والأجواء العربية.',
        descriptionEn: 'A luxury Oriental nightlife experience at the Ritz Carlton, featuring live music and Arabic vibes.',
        image: '🎻',
        imageUrl: 'https://images.unsplash.com/photo-1514525253344-991c0575d04a?w=800&q=80',
        rating: 4.8,
        duration: '4-5 hours',
        price: 'High',
        highlights: ['Live Takht', 'Nile View', 'Gourmet Mezze'],
        tip: 'Dress code is formal or elegant casual.',
        lat: 30.0465,
        lng: 31.2335,
    },
    {
        id: 413,
        name: 'هاريز باب',
        nameEn: 'Harry\'s Pub',
        city: 'القاهرة',
        cityEn: 'Cairo',
        category: 'Nightlife',
        description: 'بار إنجليزي تقليدي في فندق ماريوت الزمالك، يشتهر بالجو الدافئ والخدمة الممتازة.',
        descriptionEn: 'A traditional English pub at the Cairo Marriott, known for its cozy atmosphere and excellent service.',
        image: '🇬🇧',
        imageUrl: 'https://images.unsplash.com/photo-1514525253344-991c0575d04a?w=800&q=80',
        rating: 4.6,
        duration: '2-3 hours',
        price: 'Moderate',
        highlights: ['Darts', 'Football Screens', 'Classic Pub Food'],
        tip: 'A great place for a quiet drink in a historic setting.',
        lat: 30.0574,
        lng: 31.2245,
    },
    {
        id: 414,
        name: 'أوديون بالاس روفتوب',
        nameEn: 'Odeon Palace Rooftop',
        city: 'القاهرة',
        cityEn: 'Cairo',
        category: 'Nightlife',
        description: 'بار في وسط البلد يجمع بين البساطة والإطلالة الرائعة على المباني القديمة.',
        descriptionEn: 'A Downtown bar combining simplicity with a great view of historic buildings.',
        image: '🌇',
        imageUrl: 'https://images.unsplash.com/photo-1514525253344-991c0575d04a?w=800&q=80',
        rating: 4.3,
        duration: '2-3 hours',
        price: 'Budget',
        highlights: ['Downtown Vibe', 'Old Cairo View', 'Casual Setting'],
        tip: 'Very popular with students and artists; great for a casual beer.',
        lat: 30.0524,
        lng: 31.2415,
    },
    {
        id: 415,
        name: 'سبت فاير',
        nameEn: 'Spitfire',
        city: 'الإسكندرية',
        cityEn: 'Alexandria',
        category: 'Nightlife',
        description: 'أقدم بار في الإسكندرية، جدرانه مغطاة بالذكريات والصور من جميع أنحاء العالم.',
        descriptionEn: 'The oldest bar in Alexandria, its walls covered with memories and photos from around the world.',
        image: '⚓',
        imageUrl: 'https://images.unsplash.com/photo-1514525253344-991c0575d04a?w=800&q=80',
        rating: 4.7,
        duration: '2-3 hours',
        price: 'Moderate',
        highlights: ['Historic Memorabilia', 'Rock Music', 'Sailor Vibe'],
        tip: 'It\'s a piece of history; definitely check out the stickers and photos on the walls.',
        lat: 31.1985,
        lng: 29.8965,
    },
    {
        id: 416,
        name: 'كاب دور',
        nameEn: 'Cap D\'Or',
        city: 'الإسكندرية',
        cityEn: 'Alexandria',
        category: 'Nightlife',
        description: 'بار تاريخي في الإسكندرية يشتهر بجوه اليوناني القديم.',
        descriptionEn: 'A historic bar in Alexandria famous for its old Greek atmosphere.',
        image: '🍷',
        imageUrl: 'https://images.unsplash.com/photo-1514525253344-991c0575d04a?w=800&q=80',
        rating: 4.6,
        duration: '2-3 hours',
        price: 'Moderate',
        highlights: ['Old Decor', 'Greek Vibe', 'Historic Location'],
        tip: 'Try their local appetizers with your drink.',
        lat: 31.1982,
        lng: 29.8942,
    },
    {
        id: 417,
        name: 'لا بوديجا',
        nameEn: 'La Bodega',
        city: 'القاهرة',
        cityEn: 'Cairo',
        category: 'Nightlife',
        description: 'بار ومطعم أنيق في الزمالك يقع في مبنى تاريخي.',
        descriptionEn: 'An elegant bar and restaurant in Zamalek located in a historic building.',
        image: '🍴',
        imageUrl: 'https://images.unsplash.com/photo-1514525253344-991c0575d04a?w=800&q=80',
        rating: 4.7,
        duration: '3-4 hours',
        price: 'High',
        highlights: ['Classic Architecture', 'Fine Dining', 'Bistro Vibe'],
        tip: 'Perfect for a quiet, upscale evening.',
        lat: 30.0585,
        lng: 31.2165,
    },
    {
        id: 418,
        name: 'ديلز',
        nameEn: 'Deals',
        city: 'القاهرة',
        cityEn: 'Cairo',
        category: 'Nightlife',
        description: 'بار رياضي شهير في الزمالك، مكان رائع لمشاهدة المباريات.',
        descriptionEn: 'A popular sports bar in Zamalek, great place to watch matches.',
        image: '⚽',
        imageUrl: 'https://images.unsplash.com/photo-1514525253344-991c0575d04a?w=800&q=80',
        rating: 4.4,
        duration: '2-3 hours',
        price: 'Moderate',
        highlights: ['Sports Screens', 'Casual Vibe', 'Pub Food'],
        tip: 'Very busy during big football matches; arrive early.',
        lat: 30.0622,
        lng: 31.2201,
    },
    {
        id: 419,
        name: 'جونيز كاريوكي',
        nameEn: 'Johnnys Karaoke',
        city: 'القاهرة',
        cityEn: 'Cairo',
        category: 'Nightlife',
        description: 'أشهر مكان للكاريوكي في القاهرة، يقع داخل مركب لو باشا.',
        descriptionEn: 'The most famous karaoke spot in Cairo, located inside Le Pacha 1901 boat.',
        image: '🎤',
        imageUrl: 'https://images.unsplash.com/photo-1514525253344-991c0575d04a?w=800&q=80',
        rating: 4.5,
        duration: '4-5 hours',
        price: 'High',
        highlights: ['Karaoke Nights', 'Nile View', 'Lively Crowd'],
        tip: 'Book a table in advance for karaoke nights.',
        lat: 30.0615,
        lng: 31.2288,
    },
    {
        id: 420,
        name: 'سموكري بيتش',
        nameEn: 'Smokery Beach',
        city: 'الجونة',
        cityEn: 'El Gouna',
        category: 'Nightlife',
        description: 'بار شاطئي فاخر يقدم حفلات رائعة على الرمال.',
        descriptionEn: 'A luxury beach bar offering great parties on the sand.',
        image: '🏖️',
        imageUrl: 'https://images.unsplash.com/photo-1514525253344-991c0575d04a?w=800&q=80',
        rating: 4.8,
        duration: 'Full Night',
        price: 'High',
        highlights: ['Beach Party', 'Sushi Bar', 'Sunset Vibe'],
        tip: 'Dress code is beach chic.',
        lat: 27.4012,
        lng: 33.6855,
    },
    {
        id: 421,
        name: 'إليمنتس شرم',
        nameEn: 'Elements Sharm',
        city: 'شرم الشيخ',
        cityEn: 'Sharm El Sheikh',
        category: 'Nightlife',
        description: 'نادي ليلي عصري في خليج نعمة يتميز بالموسيقى العالمية.',
        descriptionEn: 'A modern nightclub in Naama Bay featuring international music.',
        image: '🔥',
        imageUrl: 'https://images.unsplash.com/photo-1514525253344-991c0575d04a?w=800&q=80',
        rating: 4.6,
        duration: 'Full Night',
        price: 'High',
        highlights: ['LED Shows', 'Guest DJs', 'Modern Sound'],
        tip: 'Look out for special themed party nights.',
        lat: 27.9155,
        lng: 34.3255,
    },
    {
        id: 422,
        name: 'باس ستوب الغردقة',
        nameEn: 'Bus Stop Hurghada',
        city: 'الغردقة',
        cityEn: 'Hurghada',
        category: 'Nightlife',
        description: 'بار وحانة حيوية في الغردقة، مكان مفضل للسياح والمقيمين.',
        descriptionEn: 'A lively bar and pub in Hurghada, a favorite for tourists and expats.',
        image: '🚌',
        imageUrl: 'https://images.unsplash.com/photo-1514525253344-991c0575d04a?w=800&q=80',
        rating: 4.5,
        duration: '3-4 hours',
        price: 'Moderate',
        highlights: ['Live Music', 'Pool Table', 'Social Vibe'],
        tip: 'Great for meeting new people and social evenings.',
        lat: 27.2215,
        lng: 33.8355,
    },
    {
        id: 423,
        name: 'باباس بيتش',
        nameEn: 'Papas Beach',
        city: 'الغردقة',
        cityEn: 'Hurghada',
        category: 'Nightlife',
        description: 'نادي شاطئي شهير يقدم حفلات ليلية وعروضاً ترفيهية.',
        descriptionEn: 'A famous beach club offering night parties and entertainment shows.',
        image: '🌊',
        imageUrl: 'https://images.unsplash.com/photo-1514525253344-991c0575d04a?w=800&q=80',
        rating: 4.7,
        duration: 'Full Night',
        price: 'Moderate',
        highlights: ['Foam Parties', 'Fire Shows', 'Open Air'],
        tip: 'Don\'t miss their weekend beach parties.',
        lat: 27.2355,
        lng: 33.8422,
    },
    {
        id: 424,
        name: 'كاريبيان بار',
        nameEn: 'Caribbean Bar',
        city: 'القاهرة',
        cityEn: 'Cairo',
        category: 'Nightlife',
        description: 'بار هادئ في المعادي يتميز بالديكور الاستوائي.',
        descriptionEn: 'A relaxed bar in Maadi featuring tropical decor.',
        image: '🌴',
        imageUrl: 'https://images.unsplash.com/photo-1514525253344-991c0575d04a?w=800&q=80',
        rating: 4.4,
        duration: '2-3 hours',
        price: 'Moderate',
        highlights: ['Tropical Cocktails', 'Outdoor Area', 'Chill Vibe'],
        tip: 'Great for a quiet drink with friends in Maadi.',
        lat: 29.9622,
        lng: 31.2515,
    },
    {
        id: 425,
        name: 'روف توب الزمالك',
        nameEn: 'Rooftop Zamalek',
        city: 'القاهرة',
        cityEn: 'Cairo',
        category: 'Nightlife',
        description: 'واحد من أجمل الروفتوب بارات في الزمالك، إطلالة مباشرة على النيل.',
        descriptionEn: 'One of the most beautiful rooftop bars in Zamalek, direct Nile view.',
        image: '🌉',
        imageUrl: 'https://images.unsplash.com/photo-1514525253344-991c0575d04a?w=800&q=80',
        rating: 4.5,
        duration: '3-4 hours',
        price: 'Moderate',
        highlights: ['Panoramic Nile View', 'Casual Decor', 'Sunset Spot'],
        tip: 'Located on top of the Nile Hotel; follow the signs to the roof.',
        lat: 30.0655,
        lng: 31.2222,
    }
];
