export const CATEGORIES = [
    { id: 'Pharaonic', name: 'فرعوني', nameEn: 'Pharaonic', icon: '🏛️' },
    { id: 'Islamic', name: 'إسلامي', nameEn: 'Islamic', icon: '🕌' },
    { id: 'Beach', name: 'شواطئ', nameEn: 'Beach', icon: '🏖️' },
    { id: 'Nature', name: 'طبيعة', nameEn: 'Nature', icon: '🌵' },
    { id: 'Diving', name: 'غوص', nameEn: 'Diving', icon: '🤿' },
    { id: 'Medical', name: 'علاجي', nameEn: 'Medical', icon: '♨️' },
    { id: 'Nightlife', name: 'سهر', nameEn: 'Nightlife', icon: '🪩' },
    { id: 'Cultural', name: 'ثقافي', nameEn: 'Cultural', icon: '🎭' },
];

export const places = [
    {
        id: 1,
        name: 'أهرامات الجيزة',
        nameEn: 'Giza Pyramids',
        city: 'الجيزة',
        cityEn: 'Giza',
        category: 'Pharaonic',
        description: 'آخر عجائب الدنيا السبع القديمة الباقية، وتعتبر رمزاً للحضارة المصرية القديمة.',
        descriptionEn: 'Perhaps the most recognizable among the Seven Wonders of the World, these majestic pyramids continue to spark debate and awe as a testament to ancient engineering.',
        image: '🔺',
        imageUrl: 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/1a/5c/d5/9c/caption.jpg?w=600&h=400&s=1', 
        rating: 4.6,
        duration: '3-4 hours',
        price: '540 EGP',
        highlights: ['Great Pyramid of Khufu', 'Great Sphinx', 'Panoramic View'],
        tip: 'Go early (8:00 AM) to avoid the massive crowds and the intense midday heat. Beware of over-persistent camel ride vendors.',
        lat: 29.9792,
        lng: 31.1342,
    },
    {
        id: 2,
        name: 'معبد الكرنك',
        nameEn: 'Karnak Temple',
        city: 'الأقصر',
        cityEn: 'Luxor',
        category: 'Pharaonic',
        description: 'أكبر دار للعبادة بنيت على وجه الأرض، يضم مجموعة مذهلة من المعابد والأعمدة.',
        descriptionEn: 'A vast open-air museum and the largest religious complex ever built, featuring the breathtaking Great Hypostyle Hall with its 134 massive columns.',
        image: '🏛️',
        imageUrl: 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/01/17/2a/3a/karnak-temple.jpg?w=600&h=400&s=1', 
        rating: 4.8,
        duration: '2-3 hours',
        price: '450 EGP',
        highlights: ['Hypostyle Hall', 'Sacred Lake', 'Obelisks'],
        tip: 'Stay for the evening Sound and Light show for a different perspective on the history of the complex.',
        lat: 25.7188,
        lng: 32.6586,
    },
    {
        id: 3,
        name: 'المتحف المصري بوسط البلد',
        nameEn: 'Egyptian Museum',
        city: 'القاهرة',
        cityEn: 'Cairo',
        category: 'Cultural',
        description: 'يضم أكبر مجموعة من الآثار المصرية القديمة في العالم، بما في ذلك كنوز توت عنخ آمون.',
        descriptionEn: 'Home to the world\'s most extensive collection of pharaonic antiquities, including the iconic golden mask and treasures of Tutankhamun.',
        image: '🏺',
        imageUrl: 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/05/7d/5d/79/the-egyptian-museum-in.jpg?w=600&h=400&s=1',
        rating: 4.5,
        duration: '2-3 hours',
        price: '450 EGP',
        highlights: ['Tutankhamun Mask', 'Royal Mummies', 'Rosetta Stone Replica'],
        tip: 'Consider hiring a certified guide at the entrance; the museum is vast and many artifacts lack detailed English labels.',
        lat: 30.0478,
        lng: 31.2336,
    },
    {
        id: 4,
        name: 'خان الخليلي',
        nameEn: 'Khan el-Khalili',
        city: 'القاهرة',
        cityEn: 'Cairo',
        category: 'Islamic',
        description: 'أحد أعرق الأسواق في الشرق الأوسط، يفوح بعبق التاريخ والمشغولات التقليدية.',
        descriptionEn: 'A world-famous souq in the historic center of Cairo, offering a sensory overload of spices, perfumes, jewelry, and traditional crafts.',
        image: '🏺',
        imageUrl: 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/1a/5c/d5/9b/caption.jpg?w=600&h=400&s=1', 
        rating: 4.1,
        duration: '2-3 hours',
        price: 'Free',
        highlights: ['Traditional Crafts', 'Spices & Jewelry', 'Historical Coffee Shops'],
        tip: 'Haggling is expected and part of the fun. Start at 50% of the offered price and meet in the middle. Enjoy a tea at the famous Fishawy’s Cafe.',
        lat: 30.0476,
        lng: 31.2622,
    },
    {
        id: 5,
        name: 'محمية رأس محمد',
        nameEn: 'Ras Mohammed',
        city: 'شرم الشيخ',
        cityEn: 'Sharm',
        category: 'Beach',
        description: 'أول محمية طبيعية في مصر، تحمي نظاماً بيئياً بحرياً مذهلاً.',
        descriptionEn: 'Egypt\'s first national park, protecting a stunning marine ecosystem with some of the world\'s most vibrant coral reefs.',
        image: '🏖️',
        imageUrl: 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/05/7d/5d/7c/ras-mohamed-national.jpg?w=600&h=400&s=1', 
        rating: 4.8,
        duration: '4-6 hours',
        price: '250 EGP',
        highlights: ['Coral Reefs', 'Magic Lake', 'Mangroves'],
        tip: 'Bring your own high-quality snorkeling gear if possible. Don\'t miss the \'Magic Lake\' and the Mangrove forest.',
        lat: 27.9575,
        lng: 34.3945,
    },
    {
        id: 6,
        name: 'أبو سمبل',
        nameEn: 'Abu Simbel',
        city: 'أسوان',
        cityEn: 'Aswan',
        category: 'Pharaonic',
        description: 'معبد رمسيس الثاني الضخم المنحوت في الجبل، تحفة معمارية وفلكية فريدة.',
        descriptionEn: 'Two massive rock temples commissioned by Ramses II, famous for their four colossal seated statues.',
        image: '🗿',
        imageUrl: 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/01/2b/9d/f6/abu-simbel.jpg?w=600&h=400&s=1', 
        rating: 4.9,
        duration: '2 hours',
        price: '620 EGP',
        highlights: ['Colossal Statues', 'Sun Festival', 'Lake Nasser Views'],
        tip: 'The flight from Aswan is fast but expensive; the bus convoy is cheaper but requires a very early 4:00 AM start.',
        lat: 22.3372,
        lng: 31.6258,
    },
    {
        id: 7,
        name: 'وادي الملوك',
        nameEn: 'Valley of the Kings',
        city: 'الأقصر',
        cityEn: 'Luxor',
        category: 'Pharaonic',
        description: 'موقع الدفن الشهير لفراعنة الدولة الحديثة مثل توت عنخ آمون.',
        descriptionEn: 'The final resting place of New Kingdom pharaohs, where you can explore intricately decorated tombs carved deep into the desert rock.',
        image: '🪦',
        imageUrl: 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/1a/5c/d5/7c/caption.jpg?w=600&h=400&s=1', 
        rating: 4.7,
        duration: '2-3 hours',
        price: '750 EGP',
        highlights: ['Tomb of Tutankhamun', 'Tomb of Ramses VI', 'Colorful Wall Paintings'],
        tip: 'Your standard ticket includes 3 tombs. Ramses IV is highly recommended for its vibrant colors. Tutankhamun\'s tomb requires an extra fee.',
        lat: 25.7402,
        lng: 32.6014,
    },
    {
        id: 8,
        name: 'معبد الأقصر',
        nameEn: 'Luxor Temple',
        city: 'الأقصر',
        cityEn: 'Luxor',
        category: 'Pharaonic',
        description: 'مجمع معابد رائع يقع في قلب مدينة الأقصر، مخصص لتجديد الملكية.',
        descriptionEn: 'A strikingly elegant temple complex located in the heart of Luxor city, dedicated to the rejuvenation of kingship.',
        image: '🏛️',
        imageUrl: 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/01/2d/5a/6a/luxor-temple.jpg?w=600&h=400&s=1', 
        rating: 4.7,
        duration: '1-2 hours',
        price: '370 EGP',
        highlights: ['Avenue of Sphinxes', 'Colossal Statues', 'Night Illumination'],
        tip: 'Visit at sunset. The temple is beautifully illuminated at night, creating a magical atmosphere against the dark sky.',
        lat: 25.7005,
        lng: 32.6391,
    },
    {
        id: 9,
        name: 'الثقب الأزرق',
        nameEn: 'Blue Hole Dahab',
        city: 'دهب',
        cityEn: 'Dahab',
        category: 'Diving',
        description: 'أحد أشهر مواقع الغوص في العالم المشهورة بالشعاب المرجانية وأعماقها المخيفة.',
        descriptionEn: 'One of the most famous and challenging diving sites globally, known for coral reefs and deep drop-offs.',
        image: '🤿',
        imageUrl: 'https://images.pexels.com/photos/1001965/pexels-photo-1001965.jpeg', 
        rating: 4.9,
        duration: 'Half Day',
        price: 'Free / Gear Rental',
        highlights: ['Scuba Diving', 'Free Diving', 'Coral Reefs'],
        tip: 'Even if you don\'t dive, the snorkeling here is world-class. Be careful with currents and always go with a buddy.',
        lat: 28.5714,
        lng: 34.5369,
    },
    {
        id: 10,
        name: 'جزيرة المحمية',
        nameEn: 'Mahmya Island',
        city: 'الغردقة',
        cityEn: 'Hurghada',
        category: 'Beach',
        description: 'جنة السياحة البيئية في جزيرة جفتون، تشتهر برمالها البيضاء ومياهها الفيروزية.',
        descriptionEn: 'An eco-tourism haven on Giftun Island, known for its pristine white sands and crystal-clear turquoise waters teeming with fish.',
        image: '🏖️',
        imageUrl: 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/02/1b/9d/f6/mahmya-beach.jpg?w=600&h=400&s=1', 
        rating: 4.5,
        duration: '6-8 hours',
        price: '1800 EGP',
        highlights: ['Pristine Beach', 'Snorkeling', 'Island Lunch'],
        tip: 'Book a full-day boat trip. The island is protected, so it\'s much cleaner and quieter than the public beaches in Hurghada.',
        lat: 27.2215,
        lng: 33.8547,
    }
];
