export const CATEGORIES = [
    { id: 'Pharaonic', name: 'فرعوني', nameEn: 'Pharaonic', icon: '🏛️' },
    { id: 'Islamic', name: 'إسلامي', nameEn: 'Islamic', icon: '🕌' },
    { id: 'Beach', name: 'شواطئ', nameEn: 'Beach', icon: '🏖️' },
    { id: 'Nature', name: 'طبيعة', nameEn: 'Nature', icon: '🌵' },
    { id: 'Diving', name: 'غوص', nameEn: 'Diving', icon: '🤿' },
    { id: 'Medical', name: 'علاجي', nameEn: 'Medical', icon: '♨️' },
    { id: 'Nightlife', name: 'سهر', nameEn: 'Nightlife', icon: '🪩' },
    { id: 'Cultural', name: 'ثقافي', nameEn: 'Cultural', icon: '🎭' },
];

export const places = [
    {
        id: 1,
        name: 'أهرامات الجيزة',
        nameEn: 'Giza Pyramids',
        city: 'الجيزة',
        cityEn: 'Giza',
        category: 'Pharaonic',
        description: 'آخر عجائب الدنيا السبع القديمة الباقية، وتعتبر رمزاً للحضارة المصرية القديمة.',
        descriptionEn: 'Perhaps the most recognizable among the Seven Wonders of the World, these majestic pyramids continue to spark debate and awe as a testament to ancient engineering.',
        image: '🔺',
        imageUrl: 'https://i0.wp.com/upload.wikimedia.org/wikipedia/commons/thumb/a/af/All_Gizah_Pyramids.jpg/800px-All_Gizah_Pyramids.jpg?quality=80&w=1000&strip=all', 
        rating: 4.6,
        duration: '3-4 hours',
        price: '540 EGP',
        highlights: ['Great Pyramid of Khufu', 'Great Sphinx', 'Panoramic View'],
        tip: 'Go early (8:00 AM) to avoid the massive crowds and the intense midday heat. Beware of over-persistent camel ride vendors.',
        lat: 29.9792,
        lng: 31.1342,
    },
    {
        id: 2,
        name: 'معبد الكرنك',
        nameEn: 'Karnak Temple',
        city: 'الأقصر',
        cityEn: 'Luxor',
        category: 'Pharaonic',
        description: 'أكبر دار للعبادة بنيت على وجه الأرض، يضم مجموعة مذهلة من المعابد والأعمدة.',
        descriptionEn: 'A vast open-air museum and the largest religious complex ever built, featuring the breathtaking Great Hypostyle Hall with its 134 massive columns.',
        image: '🏛️',
        imageUrl: 'https://i0.wp.com/upload.wikimedia.org/wikipedia/commons/thumb/1/10/Karnak_Temple_Complex_2005.jpg/800px-Karnak_Temple_Complex_2005.jpg?quality=80&w=1000&strip=all', 
        rating: 4.8,
        duration: '2-3 hours',
        price: '450 EGP',
        highlights: ['Hypostyle Hall', 'Sacred Lake', 'Obelisks'],
        tip: 'Stay for the evening Sound and Light show for a different perspective on the history of the complex.',
        lat: 25.7188,
        lng: 32.6586,
    },
    {
        id: 3,
        name: 'المتحف المصري بوسط البلد',
        nameEn: 'Egyptian Museum',
        city: 'القاهرة',
        cityEn: 'Cairo',
        category: 'Cultural',
        description: 'يضم أكبر مجموعة من الآثار المصرية القديمة في العالم، بما في ذلك كنوز توت عنخ آمون.',
        descriptionEn: 'Home to the world\'s most extensive collection of pharaonic antiquities, including the iconic golden mask and treasures of Tutankhamun.',
        image: '🏺',
        imageUrl: 'https://i0.wp.com/upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Egyptian_Museum_Cairo_2016.jpg/800px-Egyptian_Museum_Cairo_2016.jpg?quality=80&w=1000&strip=all',
        rating: 4.5,
        duration: '2-3 hours',
        price: '450 EGP',
        highlights: ['Tutankhamun Mask', 'Royal Mummies', 'Rosetta Stone Replica'],
        tip: 'Consider hiring a certified guide at the entrance; the museum is vast and many artifacts lack detailed English labels.',
        lat: 30.0478,
        lng: 31.2336,
    },
    {
        id: 4,
        name: 'خان الخليلي',
        nameEn: 'Khan el-Khalili',
        city: 'القاهرة',
        cityEn: 'Cairo',
        category: 'Islamic',
        description: 'أحد أعرق الأسواق في الشرق الأوسط، يفوح بعبق التاريخ والمشغولات التقليدية.',
        descriptionEn: 'A world-famous souq in the historic center of Cairo, offering a sensory overload of spices, perfumes, jewelry, and traditional crafts.',
        image: '🏺',
        imageUrl: 'https://i0.wp.com/upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Cairo_Khan_el-Khalili_BW_13.jpg/800px-Cairo_Khan_el-Khalili_BW_13.jpg?quality=80&w=1000&strip=all', 
        rating: 4.1,
        duration: '2-3 hours',
        price: 'Free',
        highlights: ['Traditional Crafts', 'Spices & Jewelry', 'Historical Coffee Shops'],
        tip: 'Haggling is expected and part of the fun. Start at 50% of the offered price and meet in the middle. Enjoy a tea at the famous Fishawy’s Cafe.',
        lat: 30.0476,
        lng: 31.2622,
    },
    {
        id: 5,
        name: 'محمية رأس محمد',
        nameEn: 'Ras Mohammed',
        city: 'شرم الشيخ',
        cityEn: 'Sharm',
        category: 'Beach',
        description: 'أول محمية طبيعية في مصر، تحمي نظاماً بيئياً بحرياً مذهلاً.',
        descriptionEn: 'Egypt\'s first national park, protecting a stunning marine ecosystem with some of the world\'s most vibrant coral reefs.',
        image: '🏖️',
        imageUrl: 'https://i0.wp.com/upload.wikimedia.org/wikipedia/commons/thumb/c/cd/Ras_Mohammed_National_Park.jpg/800px-Ras_Mohammed_National_Park.jpg?quality=80&w=1000&strip=all', 
        rating: 4.8,
        duration: '4-6 hours',
        price: '250 EGP',
        highlights: ['Coral Reefs', 'Magic Lake', 'Mangroves'],
        tip: 'Bring your own high-quality snorkeling gear if possible. Don\'t miss the \'Magic Lake\' and the Mangrove forest.',
        lat: 27.9575,
        lng: 34.3945,
    },
    {
        id: 6,
        name: 'أبو سمبل',
        nameEn: 'Abu Simbel',
        city: 'أسوان',
        cityEn: 'Aswan',
        category: 'Pharaonic',
        description: 'معبد رمسيس الثاني الضخم المنحوت في الجبل، تحفة معمارية وفلكية فريدة.',
        descriptionEn: 'Two massive rock temples commissioned by Ramses II, famous for their four colossal seated statues.',
        image: '🗿',
        imageUrl: 'https://i0.wp.com/upload.wikimedia.org/wikipedia/commons/thumb/4/4b/Abu_Simbel_Temple_of_Ramesses_II.jpg/800px-Abu_Simbel_Temple_of_Ramesses_II.jpg?quality=80&w=1000&strip=all', 
        rating: 4.9,
        duration: '2 hours',
        price: '620 EGP',
        highlights: ['Colossal Statues', 'Sun Festival', 'Lake Nasser Views'],
        tip: 'The flight from Aswan is fast but expensive; the bus convoy is cheaper but requires a very early 4:00 AM start.',
        lat: 22.3372,
        lng: 31.6258,
    },
    {
        id: 7,
        name: 'وادي الملوك',
        nameEn: 'Valley of the Kings',
        city: 'الأقصر',
        cityEn: 'Luxor',
        category: 'Pharaonic',
        description: 'موقع الدفن الشهير لفراعنة الدولة الحديثة مثل توت عنخ آمون.',
        descriptionEn: 'The final resting place of New Kingdom pharaohs, where you can explore intricately decorated tombs carved deep into the desert rock.',
        image: '🪦',
        imageUrl: 'https://i0.wp.com/upload.wikimedia.org/wikipedia/commons/0/0c/Luxor%2C_Tal_der_K%C3%B6nige_%281995%2C_860x605%29.jpg?quality=80&w=1000&strip=all', 
        rating: 4.7,
        duration: '2-3 hours',
        price: '750 EGP',
        highlights: ['Tomb of Tutankhamun', 'Tomb of Ramses VI', 'Colorful Wall Paintings'],
        tip: 'Your standard ticket includes 3 tombs. Ramses IV is highly recommended for its vibrant colors. Tutankhamun\'s tomb requires an extra fee.',
        lat: 25.7402,
        lng: 32.6014,
    },
    {
        id: 8,
        name: 'معبد الأقصر',
        nameEn: 'Luxor Temple',
        city: 'الأقصر',
        cityEn: 'Luxor',
        category: 'Pharaonic',
        description: 'مجمع معابد رائع يقع في قلب مدينة الأقصر، مخصص لتجديد الملكية.',
        descriptionEn: 'A strikingly elegant temple complex located in the heart of Luxor city, dedicated to the rejuvenation of kingship.',
        image: '🏛️',
        imageUrl: 'https://i0.wp.com/upload.wikimedia.org/wikipedia/commons/thumb/8/84/Flickr_-_archer10_%28Dennis%29_-_Egypt-13A-061_%28cropped%29.jpg/960px-Flickr_-_archer10_%28Dennis%29_-_Egypt-13A-061_%28cropped%29.jpg?quality=80&w=1000&strip=all', 
        rating: 4.7,
        duration: '1-2 hours',
        price: '370 EGP',
        highlights: ['Avenue of Sphinxes', 'Colossal Statues', 'Night Illumination'],
        tip: 'Visit at sunset. The temple is beautifully illuminated at night, creating a magical atmosphere against the dark sky.',
        lat: 25.7005,
        lng: 32.6391,
    },
    {
        id: 9,
        name: 'الثقب الأزرق',
        nameEn: 'Blue Hole Dahab',
        city: 'دهب',
        cityEn: 'Dahab',
        category: 'Diving',
        description: 'أحد أشهر مواقع الغوص في العالم المشهورة بالشعاب المرجانية وأعماقها المخيفة.',
        descriptionEn: 'One of the most famous and challenging diving sites globally, known for coral reefs and deep drop-offs.',
        image: '🤿',
        imageUrl: 'https://i0.wp.com/upload.wikimedia.org/wikipedia/commons/thumb/3/34/Blue_Whole%2C_Dahab.jpg/960px-Blue_Whole%2C_Dahab.jpg?quality=80&w=1000&strip=all', 
        rating: 4.9,
        duration: 'Half Day',
        price: 'Free / Gear Rental',
        highlights: ['Scuba Diving', 'Free Diving', 'Coral Reefs'],
        tip: 'Even if you don\'t dive, the snorkeling here is world-class. Be careful with currents and always go with a buddy.',
        lat: 28.5714,
        lng: 34.5369,
    },
    {
        id: 10,
        name: 'جزيرة المحمية',
        nameEn: 'Mahmya Island',
        city: 'الغردقة',
        cityEn: 'Hurghada',
        category: 'Beach',
        description: 'جنة السياحة البيئية في جزيرة جفتون، تشتهر برمالها البيضاء ومياهها الفيروزية.',
        descriptionEn: 'An eco-tourism haven on Giftun Island, known for its pristine white sands and crystal-clear turquoise waters teeming with fish.',
        image: '🏖️',
        imageUrl: 'https://i0.wp.com/upload.wikimedia.org/wikipedia/commons/thumb/1/1e/Mahmya_Beach_Hurghada.jpg/800px-Mahmya_Beach_Hurghada.jpg?quality=80&w=1000&strip=all', 
        rating: 4.5,
        duration: '6-8 hours',
        price: '1800 EGP',
        highlights: ['Pristine Beach', 'Snorkeling', 'Island Lunch'],
        tip: 'Book a full-day boat trip. The island is protected, so it\'s much cleaner and quieter than the public beaches in Hurghada.',
        lat: 27.2215,
        lng: 33.8547,
    },
    {
        id: 11,
        name: 'دير سانت كاترين',
        nameEn: 'St. Catherine\'s Monastery',
        city: 'سانت كاترين',
        cityEn: 'St. Catherine',
        category: 'Cultural',
        description: 'أقدم دير مسيحي مأهول في العالم، يقع عند سفح جبل سيناء.',
        descriptionEn: 'The oldest inhabited Christian monastery in the world, built at the foot of Mount Sinai.',
        image: '⛪',
        imageUrl: 'https://i0.wp.com/upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Saint_Catherine_Monastery_Sinai_Egypt.jpg/800px-Saint_Catherine_Monastery_Sinai_Egypt.jpg?quality=80&w=1000&strip=all',
        rating: 4.9,
        duration: '2-3 hours',
        price: 'Free / Donation',
        highlights: ['Burning Bush', 'Icons Collection', 'Justinian Walls'],
        tip: 'The monastery is closed on Fridays and Sundays and during religious holidays. Dress modestly.',
        lat: 28.5559,
        lng: 33.9760,
    },
    {
        id: 12,
        name: 'جبل موسى',
        nameEn: 'Mount Sinai',
        city: 'سانت كاترين',
        cityEn: 'St. Catherine',
        category: 'Nature',
        description: 'الجبل المقدس حيث تلقى النبي موسى الوصايا العشر، يوفر منظراً خلاباً لشروق الشمس.',
        descriptionEn: 'The sacred mountain where Moses received the Ten Commandments, offering breathtaking sunrise views.',
        image: '⛰️',
        imageUrl: 'https://i0.wp.com/upload.wikimedia.org/wikipedia/commons/thumb/2/2b/Mount_Sinai_Summit.jpg/800px-Mount_Sinai_Summit.jpg?quality=80&w=1000&strip=all',
        rating: 4.9,
        duration: '4-6 hours',
        price: 'Free',
        highlights: ['Sunrise Peak', 'Camel Path', 'Steps of Penitence'],
        tip: 'Start the hike at 2:00 AM to reach the summit for sunrise. Bring warm clothes as it gets very cold at the top.',
        lat: 28.5394,
        lng: 33.9749,
    },
    {
        id: 13,
        name: 'القدس العتيقة',
        nameEn: 'Jerusalem Old City',
        city: 'القدس',
        cityEn: 'Jerusalem',
        category: 'Cultural',
        description: 'قلب القدس التاريخي، يضم المسجد الأقصى وكنيسة القيامة وحائط البراق.',
        descriptionEn: 'The historic heart of Jerusalem, home to Al-Aqsa Mosque, the Church of the Holy Sepulchre, and the Wailing Wall.',
        image: '🕍',
        imageUrl: 'https://i0.wp.com/upload.wikimedia.org/wikipedia/commons/thumb/2/20/Jerusalem_Old_City_View.jpg/800px-Jerusalem_Old_City_View.jpg?quality=80&w=1000&strip=all',
        rating: 5.0,
        duration: 'Full Day',
        price: 'Variable',
        highlights: ['Al-Aqsa Mosque', 'Church of Holy Sepulchre', 'Via Dolorosa'],
        tip: 'Hire a local guide to understand the complex layers of history and spiritual significance.',
        lat: 31.7784,
        lng: 35.2354,
    },
    {
        id: 14,
        name: 'البتراء',
        nameEn: 'Petra',
        city: 'البتراء',
        cityEn: 'Petra',
        category: 'Pharaonic',
        description: 'المدينة الوردية المنحوتة في الصخر، أحد عجائب الدنيا السبع الجديدة.',
        descriptionEn: 'The Rose City carved into rock, one of the New Seven Wonders of the World.',
        image: '🏛️',
        imageUrl: 'https://i0.wp.com/upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Petra_Jordan_The_Treasury.jpg/800px-Petra_Jordan_The_Treasury.jpg?quality=80&w=1000&strip=all',
        rating: 4.9,
        duration: 'Full Day',
        price: '50 JOD',
        highlights: ['The Treasury (Al-Khazneh)', 'The Siq', 'The Monastery'],
        tip: 'Wear comfortable walking shoes. It takes at least 4-5 hours to see the main sites.',
        lat: 30.3285,
        lng: 35.4444,
    }
];
