export const CATEGORIES = [
    { id: 'Pharaonic', name: 'فرعوني', nameEn: 'Pharaonic', icon: '🏛️' },
    { id: 'Islamic', name: 'إسلامي', nameEn: 'Islamic', icon: '🕌' },
    { id: 'Beach', name: 'شواطئ', nameEn: 'Beach', icon: '🏖️' },
    { id: 'Nature', name: 'طبيعة', nameEn: 'Nature', icon: '🌵' },
    { id: 'Diving', name: 'غوص', nameEn: 'Diving', icon: '🤿' },
    { id: 'Snorkeling', name: 'سنوركلينج', nameEn: 'Snorkeling', icon: '🐠' },
    { id: 'Historical', name: 'تاريخي', nameEn: 'Historical', icon: '⚔️' },
    { id: 'Medical', name: 'علاجي', nameEn: 'Medical', icon: '♨️' },
    { id: 'Nightlife', name: 'سهر', nameEn: 'Nightlife', icon: '🪩' },
    { id: 'Cultural', name: 'ثقافي', nameEn: 'Cultural', icon: '🎭' },
];

export const places = [
    // --- GIZA ---
    {
        id: 1,
        name: 'أهرامات الجيزة',
        nameEn: 'Giza Pyramids',
        city: 'الجيزة',
        cityEn: 'Giza',
        category: 'Pharaonic',
        description: 'آخر عجائب الدنيا السبع القديمة الباقية، وتعتبر رمزاً للحضارة المصرية القديمة.',
        descriptionEn: 'Perhaps the most recognizable among the Seven Wonders of the World, these majestic pyramids continue to spark debate and awe as a testament to ancient engineering.',
        image: '🔺',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/af/All_Gizah_Pyramids.jpg/800px-All_Gizah_Pyramids.jpg',
        rating: 4.6,
        duration: '3-4 hours',
        price: '540 EGP',
        highlights: ['Great Pyramid of Khufu', 'Great Sphinx', 'Panoramic View'],
        tip: 'Go early (8:00 AM) to avoid the massive crowds and the intense midday heat. Beware of over-persistent camel ride vendors.',
        lat: 29.9792,
        lng: 31.1342,
    },
    {
        id: 24,
        name: 'هرم سقارة المدرج',
        nameEn: 'Saqqara Step Pyramid',
        city: 'الجيزة',
        cityEn: 'Giza',
        category: 'Pharaonic',
        description: 'أقدم بناء حجري ضخم في التاريخ، صممه المهندس المعماري إيمحتب للملك زوسر.',
        descriptionEn: 'The world\'s oldest colossal stone building, designed by the visionary architect Imhotep for King Djoser.',
        image: '📐',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cd/Djoser_Pyramid.jpg/800px-Djoser_Pyramid.jpg',
        rating: 4.8,
        duration: '2-3 hours',
        price: '450 EGP',
        highlights: ['Step Pyramid', 'Serapeum', 'Tomb of Kagemni'],
        tip: 'Don\'t miss the Serapeum (giant granite sarcophagi for Apis bulls), it\'s one of the most mysterious places in Egypt.',
        lat: 29.8713,
        lng: 31.2166,
    },
    {
        id: 26,
        name: 'المتحف المصري الكبير',
        nameEn: 'Grand Egyptian Museum',
        city: 'الجيزة',
        cityEn: 'Giza',
        category: 'Cultural',
        description: 'أكبر متحف في العالم مخصص لحضارة واحدة، يضم المجموعة الكاملة لكنوز توت عنخ آمون.',
        descriptionEn: 'The world\'s largest museum dedicated to a single civilization, housing the complete collection of Tutankhamun\'s treasures.',
        image: '🏛️',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/91/Grand_Egyptian_Museum_2020.jpg/800px-Grand_Egyptian_Museum_2020.jpg',
        rating: 5,
        duration: '4-5 hours',
        price: '1200 EGP',
        highlights: ['Grand Staircase', 'Tutankhamun Collection', 'Statue of Ramses II'],
        tip: 'Book tickets online well in advance. Check for current operating hours as some galleries may have limited access during the soft opening phase.',
        lat: 29.9944,
        lng: 31.1189,
    },
    // --- LUXOR ---
    {
        id: 2,
        name: 'معبد الكرنك',
        nameEn: 'Karnak Temple',
        city: 'الأقصر',
        cityEn: 'Luxor',
        category: 'Pharaonic',
        description: 'أكبر دار للعبادة بنيت على وجه الأرض، يضم مجموعة مذهلة من المعابد والأعمدة.',
        descriptionEn: 'A vast open-air museum and the largest religious complex ever built, featuring the breathtaking Great Hypostyle Hall with its 134 massive columns.',
        image: '🏛️',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Karnak_Temple_Complex_2005.jpg/800px-Karnak_Temple_Complex_2005.jpg',
        rating: 4.8,
        duration: '2-3 hours',
        price: '450 EGP',
        highlights: ['Hypostyle Hall', 'Sacred Lake', 'Obelisks'],
        tip: 'Stay for the evening Sound and Light show for a different perspective on the history of the complex.',
        lat: 25.7188,
        lng: 32.6586,
    },
    {
        id: 7,
        name: 'وادي الملوك',
        nameEn: 'Valley of the Kings',
        city: 'الأقصر',
        cityEn: 'Luxor',
        category: 'Pharaonic',
        description: 'موقع الدفن الشهير لفراعنة الدولة الحديثة مثل توت عنخ آمون.',
        descriptionEn: 'The final resting place of New Kingdom pharaohs, where you can explore intricately decorated tombs carved deep into the desert rock.',
        image: '🪦',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/0/0c/Luxor%2C_Tal_der_K%C3%B6nige_%281995%2C_860x605%29.jpg',
        rating: 4.7,
        duration: '2-3 hours',
        price: '750 EGP',
        highlights: ['Tomb of Tutankhamun', 'Tomb of Ramses VI', 'Colorful Wall Paintings'],
        tip: 'Your standard ticket includes 3 tombs. Ramses IV is highly recommended for its vibrant colors. Tutankhamun\'s tomb requires an extra fee.',
        lat: 25.7402,
        lng: 32.6014,
    },
    {
        id: 8,
        name: 'معبد الأقصر',
        nameEn: 'Luxor Temple',
        city: 'الأقصر',
        cityEn: 'Luxor',
        category: 'Pharaonic',
        description: 'مجمع معابد رائع يقع في قلب مدينة الأقصر، مخصص لتجديد الملكية.',
        descriptionEn: 'A strikingly elegant temple complex located in the heart of Luxor city, dedicated to the rejuvenation of kingship.',
        image: '🏛️',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Flickr_-_archer10_%28Dennis%29_-_Egypt-13A-061_%28cropped%29.jpg/960px-Flickr_-_archer10_%28Dennis%29_-_Egypt-13A-061_%28cropped%29.jpg',
        rating: 4.7,
        duration: '1-2 hours',
        price: '370 EGP',
        highlights: ['Avenue of Sphinxes', 'Colossal Statues', 'Night Illumination'],
        tip: 'Visit at sunset. The temple is beautifully illuminated at night, creating a magical atmosphere against the dark sky.',
        lat: 25.7005,
        lng: 32.6391,
    },
    {
        id: 19,
        name: 'معبد حتشبسوت',
        nameEn: 'Temple of Hatshepsut',
        city: 'الأقصر',
        cityEn: 'Luxor',
        category: 'Pharaonic',
        description: 'معبد الملكة حتشبسوت المهيب المحفور في الجبل بتصميم معماري فريد من ثلاثة طوابق.',
        descriptionEn: 'The magnificent mortuary temple of Queen Hatshepsut, carved into a cliff face with a unique three-tiered terrace design.',
        image: '⛩️',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/Temple_of_Hatshepsut_2019.jpg/800px-Temple_of_Hatshepsut_2019.jpg',
        rating: 4.7,
        duration: '1-2 hours',
        price: '400 EGP',
        highlights: ['Three-Tiered Architecture', 'Colonnaded Terraces', 'Ancient Reliefs'],
        tip: 'Best visited early morning before the heat. Combine with Valley of the Queens and Deir el-Medina for a full West Bank day.',
        lat: 25.738,
        lng: 32.6068,
    },
    // --- CAIRO ---
    {
        id: 3,
        name: 'المتحف المصري بوسط البلد',
        nameEn: 'Egyptian Museum',
        city: 'القاهرة',
        cityEn: 'Cairo',
        category: 'Cultural',
        description: 'يضم أكبر مجموعة من الآثار المصرية القديمة في العالم، بما في ذلك كنوز توت عنخ آمون.',
        descriptionEn: 'Home to the world\'s most extensive collection of pharaonic antiquities, including the iconic golden mask and treasures of Tutankhamun.',
        image: '🏺',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Egyptian_Museum_Cairo_2016.jpg/800px-Egyptian_Museum_Cairo_2016.jpg',
        rating: 4.5,
        duration: '2-3 hours',
        price: '450 EGP',
        highlights: ['Tutankhamun Mask', 'Royal Mummies', 'Rosetta Stone Replica'],
        tip: 'Consider hiring a certified guide at the entrance; the museum is vast and many artifacts lack detailed English labels.',
        lat: 30.0478,
        lng: 31.2336,
    },
    {
        id: 4,
        name: 'خان الخليلي',
        nameEn: 'Khan el-Khalili',
        city: 'القاهرة',
        cityEn: 'Cairo',
        category: 'Islamic',
        description: 'أحد أعرق الأسواق في الشرق الأوسط، يفوح بعبق التاريخ والمشغولات التقليدية.',
        descriptionEn: 'A world-famous souq in the historic center of Cairo, offering a sensory overload of spices, perfumes, jewelry, and traditional crafts.',
        image: '🏺',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Cairo_Khan_el-Khalili_BW_13.jpg/800px-Cairo_Khan_el-Khalili_BW_13.jpg',
        rating: 4.1,
        duration: '2-3 hours',
        price: 'Free',
        highlights: ['Traditional Crafts', 'Spices & Jewelry', 'Historical Coffee Shops'],
        tip: 'Haggling is expected and part of the fun. Start at 50% of the offered price and meet in the middle. Enjoy a tea at the famous Fishawy’s Cafe.',
        lat: 30.0476,
        lng: 31.2622,
    },
    {
        id: 17,
        name: 'مسجد محمد علي',
        nameEn: 'Muhammad Ali Mosque',
        city: 'القاهرة',
        cityEn: 'Cairo',
        category: 'Islamic',
        description: 'المسجد المسمى بالمسجد الألباستري ويهيمن على الأفق القاهري من فوق قلعة صلاح الدين.',
        descriptionEn: 'Known as the Alabaster Mosque, it dominates Cairo\'s skyline from the Saladin Citadel and is one of Egypt\'s most iconic landmarks.',
        image: '🕌',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/30/Muhammad_Ali_Mosque_Cairo.jpg/800px-Muhammad_Ali_Mosque_Cairo.jpg',
        rating: 4.7,
        duration: '1-2 hours',
        price: '100 EGP',
        highlights: ['Ottoman Architecture', 'Panoramic Cairo Views', 'Alabaster Interior'],
        tip: 'Combine with a visit to the Citadel complex which includes multiple mosques and museums. Dress modestly.',
        lat: 30.0286,
        lng: 31.26,
    },
    {
        id: 21,
        name: 'قلعة صلاح الدين',
        nameEn: 'Saladin Citadel',
        city: 'القاهرة',
        cityEn: 'Cairo',
        category: 'Islamic',
        description: 'قلعة تاريخية عظيمة تطل على القاهرة، بنيت في القرن الثاني عشر وكانت مقر حكم مصر لعدة قرون.',
        descriptionEn: 'A historic fortress overlooking Cairo, built in the 12th century and used as Egypt\'s seat of government for nearly 700 years.',
        image: '⚔️',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/18/Cairo_Citadel_Panorama.jpg/800px-Cairo_Citadel_Panorama.jpg',
        rating: 4.6,
        duration: '2-3 hours',
        price: '180 EGP',
        highlights: ['Muhammad Ali Mosque', 'Military Museum', 'Cairo Panorama'],
        tip: 'The citadel complex contains multiple museums. The view over Cairo from the walls is one of the best in the city.',
        lat: 30.0289,
        lng: 31.2617,
    },
    {
        id: 23,
        name: 'منطقة الحسين والأزهر',
        nameEn: 'Al-Hussein & Al-Azhar Area',
        city: 'القاهرة',
        cityEn: 'Cairo',
        category: 'Islamic',
        description: 'قلب القاهرة الإسلامية الخفاق، حيث مسجد الأزهر العريق وميدان الحسين وحارات الغورية التاريخية.',
        descriptionEn: 'The beating heart of Islamic Cairo, featuring the 1,000-year-old Al-Azhar Mosque, the Hussein Square, and the historic Ghuriya complex.',
        image: '🌙',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/94/Al-Azhar_Mosque_Cairo_2017.jpg/800px-Al-Azhar_Mosque_Cairo_2017.jpg',
        rating: 4.7,
        duration: '2-3 hours',
        price: 'Free',
        highlights: ['Al-Azhar Mosque', 'Ghuriya Complex', 'Street Food'],
        tip: 'Visit on a Thursday evening for the famous Sufi whirling dervish performance at the Ghuriya Wikala.',
        lat: 30.0459,
        lng: 31.2636,
    },
    {
        id: 27,
        name: 'مسجد ابن طولون',
        nameEn: 'Ibn Tulun Mosque',
        city: 'القاهرة',
        cityEn: 'Cairo',
        category: 'Islamic',
        description: 'أقدم مسجد في القاهرة لا يزال محتفظاً بحالته الأصلية، يتميز بمئذنته الفريدة ذات السلالم الخارجية.',
        descriptionEn: 'The oldest mosque in Cairo that survived in its original form, famous for its unique spiral minaret with outer stairs.',
        image: '🕌',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/52/Ibn_Tulun_Mosque_Cairo_Egypt.jpg/800px-Ibn_Tulun_Mosque_Cairo_Egypt.jpg',
        rating: 4.7,
        duration: '1-2 hours',
        price: 'Free',
        highlights: ['Spiral Minaret', 'Sahn (Courtyard)', 'Gayer-Anderson Museum Nearby'],
        tip: 'Climb the minaret for a spectacular panoramic view of Islamic Cairo. Visit the Gayer-Anderson Museum right next door.',
        lat: 30.0287,
        lng: 31.2495,
    },
    {
        id: 28,
        name: 'قصر البارون إمبان',
        nameEn: 'Baron Empain Palace',
        city: 'القاهرة',
        cityEn: 'Cairo',
        category: 'Cultural',
        description: 'تحفة معمارية مستوحاة من العمارة الهندوسية، يقع في قلب ضاحية مصر الجديدة.',
        descriptionEn: 'A stunning architectural masterpiece inspired by Hindu temple design, located in the heart of Heliopolis.',
        image: '🏰',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/Baron_Empain_Palace_Cairo.jpg/800px-Baron_Empain_Palace_Cairo.jpg',
        rating: 4.6,
        duration: '1-2 hours',
        price: '180 EGP',
        highlights: ['Exotic Architecture', 'Rooftop View', 'Historical Exhibits'],
        tip: 'The palace has been beautifully restored recently. Go at night to see it brilliantly lit up.',
        lat: 30.0867,
        lng: 31.3298,
    },
    {
        id: 34,
        name: 'مجمع متاحف الحضارة',
        nameEn: 'NMEC Museum',
        city: 'القاهرة',
        cityEn: 'Cairo',
        category: 'Cultural',
        description: 'يضم المومياوات الملكية الشهيرة ويعرض تسلسل الحضارة المصرية من فجر التاريخ حتى اليوم.',
        descriptionEn: 'Home to the famous Royal Mummies, displaying the progression of Egyptian civilization from pre-history to the modern era.',
        image: '🏺',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/87/National_Museum_of_Egyptian_Civilization_2021.jpg/800px-National_Museum_of_Egyptian_Civilization_2021.jpg',
        rating: 4.9,
        duration: '2-3 hours',
        price: '500 EGP',
        highlights: ['Royal Mummies Hall', 'Ain El-Sira Lake', 'Main Gallery'],
        tip: 'The Royal Mummies Hall is the highlight; photos are strictly forbidden there. Visit the lakeside restaurant for a great view of Old Cairo.',
        lat: 30.0075,
        lng: 31.2486,
    },
    {
        id: 35,
        name: 'حي مجمع الأديان',
        nameEn: 'Coptic Cairo',
        city: 'القاهرة',
        cityEn: 'Cairo',
        category: 'Cultural',
        description: 'يضم الكنيسة المعلقة ومعبد بن عزرا اليهودي ومسجد عمرو بن العاص، رمزاً للتسامح التاريخي.',
        descriptionEn: 'A historic area housing the Hanging Church, Ben Ezra Synagogue, and Amr ibn al-As Mosque, a true symbol of religious coexistence.',
        image: '⛪',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/The_Hanging_Church%2C_Cairo%2C_Egypt.jpg/800px-The_Hanging_Church%2C_Cairo%2C_Egypt.jpg',
        rating: 4.7,
        duration: '2-3 hours',
        price: 'Free',
        highlights: ['Hanging Church', 'Cavern Church', 'Coptic Museum'],
        tip: 'Visit early in the morning to avoid crowds. The Coptic Museum has the finest collection of Coptic art in the world.',
        lat: 30.0061,
        lng: 31.2301,
    },
    {
        id: 37,
        name: 'شارع المعز لدين الله',
        nameEn: 'Al-Muizz Street',
        city: 'القاهرة',
        cityEn: 'Cairo',
        category: 'Islamic',
        description: 'أكبر متحف مفتوح للآثار الإسلامية في العالم، يضم أجمل العمارة الفاطمية والمملوكية.',
        descriptionEn: 'The largest open-air museum of Islamic monuments in the world, featuring stunning Fatimid and Mamluk architecture.',
        image: '🏰',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f6/Al-Muizz_Street_at_night.jpg/800px-Al-Muizz_Street_at_night.jpg',
        rating: 4.8,
        duration: '2-3 hours',
        price: 'Free / Sites Paid',
        highlights: ['Qalawun Complex', 'Barquq Madrasa', 'Bab Zuweila'],
        tip: 'Walking the street at night is a magical experience as the monuments are beautifully lit. Start from Bab al-Futuh and walk south.',
        lat: 30.052,
        lng: 31.2618,
    },
    {
        id: 401,
        name: 'كايرو جاز كلوب',
        nameEn: 'Cairo Jazz Club',
        city: 'القاهرة',
        cityEn: 'Cairo',
        category: 'Nightlife',
        description: 'أشهر مكان للموسيقى الحية في القاهرة، يقدم عروضاً يومية من الجاز إلى الإلكترونيك.',
        descriptionEn: 'The legendary hub for live music in Cairo, featuring daily shows ranging from jazz to electronic.',
        image: '🎷',
        imageUrl: 'https://images.unsplash.com/photo-1514525253344-991c0575d04a?w=800&q=80',
        rating: 4.9,
        duration: '4-5 hours',
        price: 'Variable',
        highlights: ['Live Bands', 'Signature Cocktails', 'Iconic Vibe'],
        tip: 'Reservations are essential. Dress code is smart casual.',
        lat: 30.0558,
        lng: 31.2115,
    },
    {
        id: 402,
        name: 'ذا تاب',
        nameEn: 'The Tap',
        city: 'القاهرة',
        cityEn: 'Cairo',
        category: 'Nightlife',
        description: 'بار حيوي يشتهر بأجنحة الدجاج والموسيقى المتنوعة من الروك إلى الهيب هوب.',
        descriptionEn: 'A vibrant pub famous for its wings and diverse music nights, from rock to hip-hop.',
        image: '🍺',
        imageUrl: 'https://images.unsplash.com/photo-1514525253344-991c0575d04a?w=800&q=80',
        rating: 4.7,
        duration: '3-4 hours',
        price: 'Moderate',
        highlights: ['Arcade Games', 'Draft Beer', 'Themed Nights'],
        tip: 'Check their schedule for "Game Night" or "Retro Night".',
        lat: 29.9571,
        lng: 31.2581,
    },
    {
        id: 403,
        name: 'ستيج وان',
        nameEn: 'Stage One',
        city: 'القاهرة',
        cityEn: 'Cairo',
        category: 'Nightlife',
        description: 'لاونج فاخر يطل على النيل، يقدم مزيجاً من الموسيقى الشرقية والغربية.',
        descriptionEn: 'An upscale lounge overlooking the Nile, offering a blend of Oriental and Western music.',
        image: '🍸',
        imageUrl: 'https://images.unsplash.com/photo-1514525253344-991c0575d04a?w=800&q=80',
        rating: 4.8,
        duration: '4-5 hours',
        price: 'High',
        highlights: ['Nile View', 'Live Performance', 'Luxury Decor'],
        tip: 'Perfect for a sophisticated night out with a group.',
        lat: 30.0612,
        lng: 31.2285,
    },
    {
        id: 404,
        name: 'جينكو روفتوب',
        nameEn: 'Gingko Rooftop',
        city: 'القاهرة',
        cityEn: 'Cairo',
        category: 'Nightlife',
        description: 'روفتوب بار أنيق يتميز بإطلالة بانورامية على أفق القاهرة والنيل.',
        descriptionEn: 'A chic rooftop bar featuring panoramic views of the Cairo skyline and the Nile.',
        image: '🌇',
        imageUrl: 'https://images.unsplash.com/photo-1514525253344-991c0575d04a?w=800&q=80',
        rating: 4.8,
        duration: '3-4 hours',
        price: 'High',
        highlights: ['Sunset Views', 'Modern Cocktails', 'Outdoor Seating'],
        tip: 'Go just before sunset to catch the golden hour over the Nile.',
        lat: 30.0715,
        lng: 31.2268,
    },
    {
        id: 405,
        name: 'باب 28',
        nameEn: 'Pub 28',
        city: 'القاهرة',
        cityEn: 'Cairo',
        category: 'Nightlife',
        description: 'واحد من أقدم وأشهر البارات في الزمالك، يشتهر بجوه الكلاسيكي الدافئ.',
        descriptionEn: 'One of Cairo\'s oldest and most famous pubs in Zamalek, known for its warm, classic atmosphere.',
        image: '🍷',
        imageUrl: 'https://images.unsplash.com/photo-1514525253344-991c0575d04a?w=800&q=80',
        rating: 4.6,
        duration: '2-3 hours',
        price: 'Moderate',
        highlights: ['Classic Vibe', 'Steak Platter', 'Neighborhood Favorite'],
        tip: 'It gets very crowded on weekends; arrive early if you don\'t have a booking.',
        lat: 30.0615,
        lng: 31.2185,
    },
    {
        id: 412,
        name: 'راوي',
        nameEn: 'Rawi',
        city: 'القاهرة',
        cityEn: 'Cairo',
        category: 'Nightlife',
        description: 'سهرة شرقية فاخرة في فندق الريتز كارلتون، تجمع بين الموسيقى الحية والأجواء العربية.',
        descriptionEn: 'A luxury Oriental nightlife experience at the Ritz Carlton, featuring live music and Arabic vibes.',
        image: '🎻',
        imageUrl: 'https://images.unsplash.com/photo-1514525253344-991c0575d04a?w=800&q=80',
        rating: 4.8,
        duration: '4-5 hours',
        price: 'High',
        highlights: ['Live Takht', 'Nile View', 'Gourmet Mezze'],
        tip: 'Dress code is formal or elegant casual.',
        lat: 30.0465,
        lng: 31.2335,
    },
    {
        id: 413,
        name: 'هاريز باب',
        nameEn: 'Harry\'s Pub',
        city: 'القاهرة',
        cityEn: 'Cairo',
        category: 'Nightlife',
        description: 'بار إنجليزي تقليدي في فندق ماريوت الزمالك، يشتهر بالجو الدافئ والخدمة الممتازة.',
        descriptionEn: 'A traditional English pub at the Cairo Marriott, known for its cozy atmosphere and excellent service.',
        image: '🇬🇧',
        imageUrl: 'https://images.unsplash.com/photo-1514525253344-991c0575d04a?w=800&q=80',
        rating: 4.6,
        duration: '2-3 hours',
        price: 'Moderate',
        highlights: ['Darts', 'Football Screens', 'Classic Pub Food'],
        tip: 'A great place for a quiet drink in a historic setting.',
        lat: 30.0574,
        lng: 31.2245,
    },
    {
        id: 414,
        name: 'أوديون بالاس روفتوب',
        nameEn: 'Odeon Palace Rooftop',
        city: 'القاهرة',
        cityEn: 'Cairo',
        category: 'Nightlife',
        description: 'بار في وسط البلد يجمع بين البساطة والإطلالة الرائعة على المباني القديمة.',
        descriptionEn: 'A Downtown bar combining simplicity with a great view of historic buildings.',
        image: '🌇',
        imageUrl: 'https://images.unsplash.com/photo-1514525253344-991c0575d04a?w=800&q=80',
        rating: 4.3,
        duration: '2-3 hours',
        price: 'Budget',
        highlights: ['Downtown Vibe', 'Old Cairo View', 'Casual Setting'],
        tip: 'Very popular with students and artists; great for a casual beer.',
        lat: 30.0524,
        lng: 31.2415,
    },
    {
        id: 417,
        name: 'لا بوديجا',
        nameEn: 'La Bodega',
        city: 'القاهرة',
        cityEn: 'Cairo',
        category: 'Nightlife',
        description: 'بار ومطعم أنيق في الزمالك يقع في مبنى تاريخي.',
        descriptionEn: 'An elegant bar and restaurant in Zamalek located in a historic building.',
        image: '🍴',
        imageUrl: 'https://images.unsplash.com/photo-1514525253344-991c0575d04a?w=800&q=80',
        rating: 4.7,
        duration: '3-4 hours',
        price: 'High',
        highlights: ['Classic Architecture', 'Fine Dining', 'Bistro Vibe'],
        tip: 'Perfect for a quiet, upscale evening.',
        lat: 30.0585,
        lng: 31.2165,
    },
    {
        id: 418,
        name: 'ديلز',
        nameEn: 'Deals',
        city: 'القاهرة',
        cityEn: 'Cairo',
        category: 'Nightlife',
        description: 'بار رياضي شهير في الزمالك، مكان رائع لمشاهدة المباريات.',
        descriptionEn: 'A popular sports bar in Zamalek, great place to watch matches.',
        image: '⚽',
        imageUrl: 'https://images.unsplash.com/photo-1514525253344-991c0575d04a?w=800&q=80',
        rating: 4.4,
        duration: '2-3 hours',
        price: 'Moderate',
        highlights: ['Sports Screens', 'Casual Vibe', 'Pub Food'],
        tip: 'Very busy during big football matches; arrive early.',
        lat: 30.0622,
        lng: 31.2201,
    },
    {
        id: 419,
        name: 'جونيز كاريوكي',
        nameEn: 'Johnnys Karaoke',
        city: 'القاهرة',
        cityEn: 'Cairo',
        category: 'Nightlife',
        description: 'أشهر مكان للكاريوكي في القاهرة، يقع داخل مركب لو باشا.',
        descriptionEn: 'The most famous karaoke spot in Cairo, located inside Le Pacha 1901 boat.',
        image: '🎤',
        imageUrl: 'https://images.unsplash.com/photo-1514525253344-991c0575d04a?w=800&q=80',
        rating: 4.5,
        duration: '4-5 hours',
        price: 'High',
        highlights: ['Karaoke Nights', 'Nile View', 'Lively Crowd'],
        tip: 'Book a table in advance for karaoke nights.',
        lat: 30.0615,
        lng: 31.2288,
    },
    {
        id: 424,
        name: 'كاريبيان بار',
        nameEn: 'Caribbean Bar',
        city: 'القاهرة',
        cityEn: 'Cairo',
        category: 'Nightlife',
        description: 'بار هادئ في المعادي يتميز بالديكور الاستوائي.',
        descriptionEn: 'A relaxed bar in Maadi featuring tropical decor.',
        image: '🌴',
        imageUrl: 'https://images.unsplash.com/photo-1514525253344-991c0575d04a?w=800&q=80',
        rating: 4.4,
        duration: '2-3 hours',
        price: 'Moderate',
        highlights: ['Tropical Cocktails', 'Outdoor Area', 'Chill Vibe'],
        tip: 'Great for a quiet drink with friends in Maadi.',
        lat: 29.9622,
        lng: 31.2515,
    },
    {
        id: 425,
        name: 'روف توب الزمالك',
        nameEn: 'Rooftop Zamalek',
        city: 'القاهرة',
        cityEn: 'Cairo',
        category: 'Nightlife',
        description: 'واحد من أجمل الروفتوب بارات في الزمالك، إطلالة مباشرة على النيل.',
        descriptionEn: 'One of the most beautiful rooftop bars in Zamalek, direct Nile view.',
        image: '🌉',
        imageUrl: 'https://images.unsplash.com/photo-1514525253344-991c0575d04a?w=800&q=80',
        rating: 4.5,
        duration: '3-4 hours',
        price: 'Moderate',
        highlights: ['Panoramic Nile View', 'Casual Decor', 'Sunset Spot'],
        tip: 'Located on top of the Nile Hotel; follow the signs to the roof.',
        lat: 30.0655,
        lng: 31.2222,
    },
    // --- SHARM ---
    {
        id: 5,
        name: 'محمية رأس محمد',
        nameEn: 'Ras Mohammed',
        city: 'شرم الشيخ',
        cityEn: 'Sharm',
        category: 'Beach',
        description: 'أول محمية طبيعية في مصر، تحمي نظاماً بيئياً بحرياً مذهلاً.',
        descriptionEn: 'Egypt\'s first national park, protecting a stunning marine ecosystem with some of the world\'s most vibrant coral reefs.',
        image: '🏖️',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cd/Ras_Mohammed_National_Park.jpg/800px-Ras_Mohammed_National_Park.jpg',
        rating: 4.8,
        duration: '4-6 hours',
        price: '250 EGP',
        highlights: ['Coral Reefs', 'Magic Lake', 'Mangroves'],
        tip: 'Bring your own high-quality snorkeling gear if possible. Don\'t miss the \'Magic Lake\' and the Mangrove forest.',
        lat: 27.9575,
        lng: 34.3945,
    },
    // --- ASWAN ---
    {
        id: 6,
        name: 'أبو سمبل',
        nameEn: 'Abu Simbel',
        city: 'أسوان',
        cityEn: 'Aswan',
        category: 'Pharaonic',
        description: 'معبد رمسيس الثاني الضخم المنحوت في الجبل، تحفة معمارية وفلكية فريدة.',
        descriptionEn: 'Two massive rock temples commissioned by Ramses II, famous for their four colossal seated statues.',
        image: '🗿',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/Abu_Simbel_Temple_of_Ramesses_II.jpg/800px-Abu_Simbel_Temple_of_Ramesses_II.jpg',
        rating: 4.9,
        duration: '2 hours',
        price: '620 EGP',
        highlights: ['Colossal Statues', 'Sun Festival', 'Lake Nasser Views'],
        tip: 'The flight from Aswan is fast but expensive; the bus convoy is cheaper but requires a very early 4:00 AM start.',
        lat: 22.3372,
        lng: 31.6258,
    },
    {
        id: 15,
        name: 'معبد فيلة',
        nameEn: 'Philae Temple',
        city: 'أسوان',
        cityEn: 'Aswan',
        category: 'Pharaonic',
        description: 'معبد الإلهة إيزيس الرائع المبني على جزيرة في النيل، أنقذ من الغرق عند بناء السد العالي.',
        descriptionEn: 'A stunning temple dedicated to goddess Isis, built on an island in the Nile. Rescued from the rising waters of the Aswan Dam.',
        image: '🛕',
        imageUrl: 'https://images.unsplash.com/photo-1553913861-c0fddf2619ee?w=800&q=80',
        rating: 4.8,
        duration: '1-2 hours',
        price: '350 EGP',
        highlights: ['Temple of Isis', 'Sound & Light Show', 'Boat Ride'],
        tip: 'Don\'t miss the evening Sound and Light Show, which tells the story of Isis and Osiris while the temple is beautifully illuminated.',
        lat: 24.0244,
        lng: 32.8831,
    },
    {
        id: 25,
        name: 'معبد إدفو',
        nameEn: 'Edfu Temple',
        city: 'أسوان',
        cityEn: 'Aswan',
        category: 'Pharaonic',
        description: 'أجمل المعابد المصرية القديمة وأكثرها اكتمالاً، مخصص للإله حورس.',
        descriptionEn: 'One of the best-preserved and most majestic ancient Egyptian temples, dedicated to the falcon god Horus.',
        image: '🦅',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Edfu_Temple_01.jpg/800px-Edfu_Temple_01.jpg',
        rating: 4.8,
        duration: '2 hours',
        price: '450 EGP',
        highlights: ['Pylon Towers', 'Mammisi', 'Court of Offerings'],
        tip: 'Most visitors arrive via horse-drawn carriages from the Nile dock; agree on the price clearly before starting.',
        lat: 24.9781,
        lng: 32.8735,
    },
    // --- DAHAB ---
    {
        id: 9,
        name: 'الثقب الأزرق',
        nameEn: 'Blue Hole Dahab',
        city: 'دهب',
        cityEn: 'Dahab',
        category: 'Diving',
        description: 'أحد أشهر مواقع الغوص في العالم المشهورة بالشعاب المرجانية وأعماقها المخيفة.',
        descriptionEn: 'One of the most famous and challenging diving sites globally, known for coral reefs and deep drop-offs.',
        image: '🤿',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/34/Blue_Whole%2C_Dahab.jpg/960px-Blue_Whole%2C_Dahab.jpg',
        rating: 4.9,
        duration: 'Half Day',
        price: 'Free / Gear Rental',
        highlights: ['Scuba Diving', 'Free Diving', 'Coral Reefs'],
        tip: 'Even if you don\'t dive, the snorkeling here is world-class. Be careful with currents and always go with a buddy.',
        lat: 28.5714,
        lng: 34.5369,
    },
    // --- HURGHADA ---
    {
        id: 10,
        name: 'جزيرة المحمية',
        nameEn: 'Mahmya Island',
        city: 'الغردقة',
        cityEn: 'Hurghada',
        category: 'Beach',
        description: 'جنة السياحة البيئية في جزيرة جفتون، تشتهر برمالها البيضاء ومياهها الفيروزية.',
        descriptionEn: 'An eco-tourism haven on Giftun Island, known for its pristine white sands and crystal-clear turquoise waters teeming with fish.',
        image: '🏖️',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1e/Mahmya_Beach_Hurghada.jpg/800px-Mahmya_Beach_Hurghada.jpg',
        rating: 4.5,
        duration: '6-8 hours',
        price: '1800 EGP',
        highlights: ['Pristine Beach', 'Snorkeling', 'Island Lunch'],
        tip: 'Book a full-day boat trip. The island is protected, so it\'s much cleaner and quieter than the public beaches in Hurghada.',
        lat: 27.2215,
        lng: 33.8547,
    },
    {
        id: 31,
        name: 'سهل حشيش',
        nameEn: 'Sahl Hasheesh',
        city: 'الغردقة',
        cityEn: 'Hurghada',
        category: 'Beach',
        description: 'منطقة سياحية راقية تضم أجمل الشواطئ ومواقع الغوص والمدينة الغارقة تحت الماء.',
        descriptionEn: 'An upscale resort area known for its pristine beaches, world-class diving, and a fascinating "Sunken City" offshore.',
        image: '💎',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Sahl_Hasheesh_Bay.jpg/800px-Sahl_Hasheesh_Bay.jpg',
        rating: 4.7,
        duration: 'Full Day',
        price: 'Variable',
        highlights: ['Sunken City', 'Marina Promenade', 'Luxury Resorts'],
        tip: 'Rent a golf cart to explore the 12km beachfront promenade. The snorkeling near the Arrival Piazza is excellent.',
        lat: 27.0506,
        lng: 33.8821,
    },
    {
        id: 410,
        name: 'ليتل بوذا',
        nameEn: 'Little Buddha',
        city: 'الغردقة',
        cityEn: 'Hurghada',
        category: 'Nightlife',
        description: 'مطعم وسهرة فاخرة يجمع بين الأكل الآسيوي والأجواء الموسيقية الراقية.',
        descriptionEn: 'A luxury dining and nightlife spot combining Asian cuisine with upscale musical vibes.',
        image: '🏮',
        imageUrl: 'https://images.unsplash.com/photo-1514525253344-991c0575d04a?w=800&q=80',
        rating: 4.8,
        duration: '4-5 hours',
        price: 'High',
        highlights: ['Asian Fusion', 'Buddha Statue', 'Classy Bar'],
        tip: 'The sushi here is excellent, followed by a great bar scene after 11 PM.',
        lat: 27.1854,
        lng: 33.8214,
    },
    {
        id: 422,
        name: 'باس ستوب الغردقة',
        nameEn: 'Bus Stop Hurghada',
        city: 'الغردقة',
        cityEn: 'Hurghada',
        category: 'Nightlife',
        description: 'بار وحانة حيوية في الغردقة، مكان مفضل للسياح والمقيمين.',
        descriptionEn: 'A lively bar and pub in Hurghada, a favorite for tourists and expats.',
        image: '🚌',
        imageUrl: 'https://images.unsplash.com/photo-1514525253344-991c0575d04a?w=800&q=80',
        rating: 4.5,
        duration: '3-4 hours',
        price: 'Moderate',
        highlights: ['Live Music', 'Pool Table', 'Social Vibe'],
        tip: 'Great for meeting new people and social evenings.',
        lat: 27.2215,
        lng: 33.8355,
    },
    {
        id: 423,
        name: 'باباس بيتش',
        nameEn: 'Papas Beach',
        city: 'الغردقة',
        cityEn: 'Hurghada',
        category: 'Nightlife',
        description: 'نادي شاطئي شهير يقدم حفلات ليلية وعروضاً ترفيهية.',
        descriptionEn: 'A famous beach club offering night parties and entertainment shows.',
        image: '🌊',
        imageUrl: 'https://images.unsplash.com/photo-1514525253344-991c0575d04a?w=800&q=80',
        rating: 4.7,
        duration: 'Full Night',
        price: 'Moderate',
        highlights: ['Foam Parties', 'Fire Shows', 'Open Air'],
        tip: 'Don\'t miss their weekend beach parties.',
        lat: 27.2355,
        lng: 33.8422,
    },
    // --- ST. CATHERINE ---
    {
        id: 11,
        name: 'دير سانت كاترين',
        nameEn: 'St. Catherine\'s Monastery',
        city: 'سانت كاترين',
        cityEn: 'St. Catherine',
        category: 'Cultural',
        description: 'أقدم دير مسيحي مأهول في العالم، يقع عند سفح جبل سيناء.',
        descriptionEn: 'The oldest inhabited Christian monastery in the world, built at the foot of Mount Sinai.',
        image: '⛪',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Saint_Catherine_Monastery_Sinai_Egypt.jpg/800px-Saint_Catherine_Monastery_Sinai_Egypt.jpg',
        rating: 4.9,
        duration: '2-3 hours',
        price: 'Free / Donation',
        highlights: ['Burning Bush', 'Icons Collection', 'Justinian Walls'],
        tip: 'The monastery is closed on Fridays and Sundays and during religious holidays. Dress modestly.',
        lat: 28.5559,
        lng: 33.976,
    },
    {
        id: 12,
        name: 'جبل موسى',
        nameEn: 'Mount Sinai',
        city: 'سانت كاترين',
        cityEn: 'St. Catherine',
        category: 'Nature',
        description: 'الجبل المقدس حيث تلقى النبي موسى الوصايا العشر، يوفر منظراً خلاباً لشروق الشمس.',
        descriptionEn: 'The sacred mountain where Moses received the Ten Commandments, offering breathtaking sunrise views.',
        image: '⛰️',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2b/Mount_Sinai_Summit.jpg/800px-Mount_Sinai_Summit.jpg',
        rating: 4.9,
        duration: '4-6 hours',
        price: 'Free',
        highlights: ['Sunrise Peak', 'Camel Path', 'Steps of Penitence'],
        tip: 'Start the hike at 2:00 AM to reach the summit for sunrise. Bring warm clothes as it gets very cold at the top.',
        lat: 28.5394,
        lng: 33.9749,
    },
    // --- ALEXANDRIA ---
    {
        id: 13,
        name: 'مكتبة الإسكندرية',
        nameEn: 'Bibliotheca Alexandrina',
        city: 'الإسكندرية',
        cityEn: 'Alexandria',
        category: 'Cultural',
        description: 'أحد أعظم الصروح الثقافية في العالم، أُسست لإحياء ذكرى مكتبة الإسكندرية الأسطورية.',
        descriptionEn: 'One of the largest and most significant libraries in the world, built to revive the spirit of the legendary ancient Library of Alexandria.',
        image: '📚',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/14/Bibliotheca_Alexandrina_Exterior.jpg/800px-Bibliotheca_Alexandrina_Exterior.jpg',
        rating: 4.7,
        duration: '2-3 hours',
        price: '50 EGP',
        highlights: ['Planetarium', 'Manuscript Museum', 'Antiquities Museum'],
        tip: 'Visit on a weekday to avoid school groups. The planetarium shows are excellent for all ages.',
        lat: 31.2089,
        lng: 29.9092,
    },
    {
        id: 16,
        name: 'قلعة قايتباي',
        nameEn: 'Citadel of Qaitbay',
        city: 'الإسكندرية',
        cityEn: 'Alexandria',
        category: 'Islamic',
        description: 'قلعة حصينة من القرن الخامس عشر تقع على الطرف الغربي لميناء الإسكندرية الشرقي.',
        descriptionEn: 'A 15th-century defensive fortress built on the exact site of the ancient Lighthouse of Alexandria, one of the Seven Wonders of the Ancient World.',
        image: '🏰',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f6/Alexandria_Citadel_Qaitbay_Egypt.jpg/800px-Alexandria_Citadel_Qaitbay_Egypt.jpg',
        rating: 4.5,
        duration: '1-2 hours',
        price: '120 EGP',
        highlights: ['Sea Views', 'Museum Inside', 'Lighthouse Site'],
        tip: 'Visit at sunset for stunning views over the Mediterranean. The museum inside has artifacts from the original lighthouse.',
        lat: 31.2139,
        lng: 29.8854,
    },
    {
        id: 415,
        name: 'سبت فاير',
        nameEn: 'Spitfire',
        city: 'الإسكندرية',
        cityEn: 'Alexandria',
        category: 'Nightlife',
        description: 'أقدم بار في الإسكندرية، جدرانه مغطاة بالذكريات والصور من جميع أنحاء العالم.',
        descriptionEn: 'The oldest bar in Alexandria, its walls covered with memories and photos from around the world.',
        image: '⚓',
        imageUrl: 'https://images.unsplash.com/photo-1514525253344-991c0575d04a?w=800&q=80',
        rating: 4.7,
        duration: '2-3 hours',
        price: 'Moderate',
        highlights: ['Historic Memorabilia', 'Rock Music', 'Sailor Vibe'],
        tip: 'It\'s a piece of history; definitely check out the stickers and photos on the walls.',
        lat: 31.1985,
        lng: 29.8965,
    },
    {
        id: 416,
        name: 'كاب دور',
        nameEn: 'Cap D\'Or',
        city: 'الإسكندرية',
        cityEn: 'Alexandria',
        category: 'Nightlife',
        description: 'بار تاريخي في الإسكندرية يشتهر بجوه اليوناني القديم.',
        descriptionEn: 'A historic bar in Alexandria famous for its old Greek atmosphere.',
        image: '🍷',
        imageUrl: 'https://images.unsplash.com/photo-1514525253344-991c0575d04a?w=800&q=80',
        rating: 4.6,
        duration: '2-3 hours',
        price: 'Moderate',
        highlights: ['Old Decor', 'Greek Vibe', 'Historic Location'],
        tip: 'Try their local appetizers with your drink.',
        lat: 31.1982,
        lng: 29.8942,
    },
    // --- MATROUH ---
    {
        id: 14,
        name: 'واحة سيوة',
        nameEn: 'Siwa Oasis',
        city: 'مطروح',
        cityEn: 'Matrouh',
        category: 'Nature',
        description: 'جنة صحراوية نائية، تشتهر بعيون المياه الكبريتية وزيت الزيتون والتمور الفاخرة.',
        descriptionEn: 'A remote desert paradise famous for its sulphur springs, olive groves, and exquisite dates. Visited by Alexander the Great.',
        image: '🌴',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Siwa_Oasis_Lakes.jpg/800px-Siwa_Oasis_Lakes.jpg',
        rating: 4.9,
        duration: '2-3 Days',
        price: 'Variable',
        highlights: ['Cleopatra\'s Bath', 'Temple of the Oracle', 'Great Sand Sea'],
        tip: 'Rent a bicycle to explore the oasis. Stay at a traditional mud-brick ecolodge for an authentic experience.',
        lat: 29.2033,
        lng: 25.5195,
    },
    // --- FARAFRA ---
    {
        id: 18,
        name: 'الصحراء البيضاء',
        nameEn: 'White Desert',
        city: 'الفرافرة',
        cityEn: 'Farafra',
        category: 'Nature',
        description: 'مشهد خيالي من الصخور البيضاء المنحوتة بفعل الرياح، يبدو كأنه مستقى من كوكب آخر.',
        descriptionEn: 'A surreal landscape of wind-sculpted white chalk rock formations in the Western Desert, looking like a scene from another planet.',
        image: '🏜️',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Egypt_White_Desert.jpg/800px-Egypt_White_Desert.jpg',
        rating: 4.9,
        duration: '2 Days',
        price: 'Variable',
        highlights: ['Chalk Rock Formations', 'Desert Camping', 'Stargazing'],
        tip: 'Camp overnight in the desert for an unforgettable stargazing experience. Bring warm clothes as desert nights get very cold.',
        lat: 27.32,
        lng: 27.97,
    },
    // --- SOHAG ---
    {
        id: 20,
        name: 'معبد أبيدوس',
        nameEn: 'Abydos Temple',
        city: 'سوهاج',
        cityEn: 'Sohag',
        category: 'Pharaonic',
        description: 'أحد أقدس مواقع مصر الفرعونية، يضم معبد سيتي الأول وأشهر قائمة للملوك.',
        descriptionEn: 'One of the most sacred sites in Ancient Egypt, containing the Temple of Seti I with the famous Abydos Kings List.',
        image: '🗺️',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/Abydos_Temple_Complex.jpg/800px-Abydos_Temple_Complex.jpg',
        rating: 4.8,
        duration: '2-3 hours',
        price: '400 EGP',
        highlights: ['Kings List', 'Seti I Temple', 'Osireion'],
        tip: 'Often missed by tourists, making it a peaceful alternative to busier sites. The wall reliefs here are among the finest preserved in Egypt.',
        lat: 26.1843,
        lng: 31.9193,
    },
    // --- MARSA MATROUH ---
    {
        id: 22,
        name: 'شاطئ سيدي عبد الرحمن',
        nameEn: 'Sidi Abdel Rahman Beach',
        city: 'مرسى مطروح',
        cityEn: 'Marsa Matrouh',
        category: 'Beach',
        description: 'أحد أجمل الشواطئ في العالم بمياهه الفيروزية ورماله البيضاء الناعمة.',
        descriptionEn: 'Considered one of the most beautiful beaches in the world, with turquoise waters and fine white sand.',
        image: '🌊',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/Sidi_Abdel_Rahman_Coast.jpg/800px-Sidi_Abdel_Rahman_Coast.jpg',
        rating: 4.8,
        duration: 'Full Day',
        price: 'Variable',
        highlights: ['Crystal Clear Water', 'White Sand', 'El Alamein Museum Nearby'],
        tip: 'Best visited in June and July. The beach gets crowded in August. Stop by El Alamein War Museum nearby.',
        lat: 30.8272,
        lng: 28.5503,
    },
    {
        id: 30,
        name: 'شاطئ عجيبة',
        nameEn: 'Agiba Beach',
        city: 'مرسى مطروح',
        cityEn: 'Marsa Matrouh',
        category: 'Beach',
        description: 'أحد أجمل شواطئ العالم، يتميز بكهوفه الصخرية ومياهه الفيروزية الساحرة.',
        descriptionEn: 'A breathtaking beach famous for its dramatic rock caves and mesmerizing shades of turquoise water.',
        image: '🏖️',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b5/Agiba_Beach_Marsa_Matrouh_Egypt.jpg/800px-Agiba_Beach_Marsa_Matrouh_Egypt.jpg',
        rating: 4.8,
        duration: 'Full Day',
        price: 'Free',
        highlights: ['Rock Caves', 'Crystal Waters', 'Cliff Views'],
        tip: 'The word "Agiba" means "Miracle." The beach is small and can get very crowded in summer; try to visit early in the morning.',
        lat: 31.4116,
        lng: 27.0017,
    },
    // --- FAYOUM ---
    {
        id: 29,
        name: 'وادي الحيتان',
        nameEn: 'Wadi El-Hitan',
        city: 'الفيوم',
        cityEn: 'Fayoum',
        category: 'Nature',
        description: 'موقع تراث عالمي يضم حفريات نادرة لحيتان منقرضة كانت تعيش قبل ملايين السنين.',
        descriptionEn: 'A UNESCO World Heritage site containing hundreds of rare fossils of extinct whales that lived millions of years ago.',
        image: '🐋',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/25/Wadi_al-Hitan_Egypt.jpg/800px-Wadi_al-Hitan_Egypt.jpg',
        rating: 4.9,
        duration: '4-6 hours',
        price: '200 EGP',
        highlights: ['Whale Fossils', 'Open-Air Museum', 'Desert Scenery'],
        tip: 'Combine this with a visit to the Wadi El-Rayan waterfalls. A 4x4 vehicle is recommended for the desert tracks.',
        lat: 29.2711,
        lng: 30.0436,
    },
    {
        id: 36,
        name: 'محمية وادي الريان',
        nameEn: 'Wadi El-Rayan',
        city: 'الفيوم',
        cityEn: 'Fayoum',
        category: 'Nature',
        description: 'تشتهر بشلالاتها الطبيعية الوحيدة في مصر والبحيرات والرمال الناعمة لممارسة التزلج على الرمال.',
        descriptionEn: 'Famous for Egypt\'s only natural waterfalls, beautiful lakes, and soft dunes perfect for sandboarding.',
        image: '🌊',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Wadi_El-Rayan_Waterfalls_Egypt.jpg/800px-Wadi_El-Rayan_Waterfalls_Egypt.jpg',
        rating: 4.5,
        duration: '4-6 hours',
        price: '50 EGP',
        highlights: ['Waterfalls', 'Sandboarding', 'Magic Lake'],
        tip: 'It\'s a perfect day trip from Cairo. Try sandboarding on the dunes surrounding Magic Lake; it\'s an exhilarating experience.',
        lat: 29.2132,
        lng: 30.4357,
    },
    // --- SAFAGA ---
    {
        id: 32,
        name: 'سفاجا (علاجي)',
        nameEn: 'Safaga Healing',
        city: 'سفاجا',
        cityEn: 'Safaga',
        category: 'Medical',
        description: 'مركز عالمي للسياحة العلاجية، تشتهر برمالها السوداء الغنية بالمعادن لعلاج الأمراض الجلدية والمفاصل.',
        descriptionEn: 'A global hub for medical tourism, famous for its mineral-rich black sands used to treat skin diseases and joint pain.',
        image: '♨️',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/56/Safaga_Bay.jpg/800px-Safaga_Bay.jpg',
        rating: 4.6,
        duration: '3-5 hours',
        price: 'Variable',
        highlights: ['Black Sand Baths', 'Natural UV Therapy', 'Salt Water Springs'],
        tip: 'Safaga has very high salt concentration and pure black sand. It\'s scientifically recognized as a natural clinic for psoriasis.',
        lat: 26.7297,
        lng: 33.9366,
    },
    // --- SOUTH SINAI ---
    {
        id: 33,
        name: 'حمام موسى',
        nameEn: 'Moses Bath (Hammam Musa)',
        city: 'جنوب سيناء',
        cityEn: 'South Sinai',
        category: 'Medical',
        description: 'عيون كبريتية ساخنة تعرف بخصائصها العلاجية، يقال إن النبي موسى استحم فيها.',
        descriptionEn: 'Natural hot sulphur springs known for their therapeutic properties. Tradition holds that Prophet Moses bathed here.',
        image: '♨️',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/56/Safaga_Bay.jpg/800px-Safaga_Bay.jpg',
        rating: 4.4,
        duration: '2-3 hours',
        price: '100 EGP',
        highlights: ['Hot Springs', 'Natural Therapy', 'Desert Setting'],
        tip: 'The water temperature is naturally around 37°C. Bring a towel and swimsuit. Best visited in winter months.',
        lat: 28.0696,
        lng: 33.8766,
    },
    // --- SHARM EL SHEIKH ---
    {
        id: 406,
        name: 'فارشا كافيه',
        nameEn: 'Farsha Cafe',
        city: 'شرم الشيخ',
        cityEn: 'Sharm El Sheikh',
        category: 'Nightlife',
        description: 'أشهر كافيه بوهيمي في شرم الشيخ، يقع على جرف صخري ويقدم إطلالة ساحرة.',
        descriptionEn: 'The most famous bohemian cafe in Sharm, perched on a cliff with mesmerizing sea views.',
        image: '🏮',
        imageUrl: 'https://images.unsplash.com/photo-1514525253344-991c0575d04a?w=800&q=80',
        rating: 4.9,
        duration: '4-5 hours',
        price: 'Moderate',
        highlights: ['Bohemian Decor', 'Cliff View', 'Shisha & Drinks'],
        tip: 'Visit at night to see the lanterns lit up; it feels like a scene from 1001 Nights.',
        lat: 27.8624,
        lng: 34.3015,
    },
    {
        id: 408,
        name: 'باشا شرم الشيخ',
        nameEn: 'Pacha Sharm',
        city: 'شرم الشيخ',
        cityEn: 'Sharm El Sheikh',
        category: 'Nightlife',
        description: 'فرع النادي العالمي الشهير، يقدم حفلات ضخمة مع أشهر الدي جي حول العالم.',
        descriptionEn: 'The Egyptian branch of the world-famous club, hosting massive parties with global DJs.',
        image: '🍒',
        imageUrl: 'https://images.unsplash.com/photo-1514525253344-991c0575d04a?w=800&q=80',
        rating: 4.8,
        duration: 'Full Night',
        price: 'High',
        highlights: ['Open Air Club', 'World-Class Sound', 'Summer Parties'],
        tip: 'Check their summer schedule for international DJ appearances.',
        lat: 27.9135,
        lng: 34.3218,
    },
    {
        id: 409,
        name: 'سبيس شرم',
        nameEn: 'Space Sharm',
        city: 'شرم الشيخ',
        cityEn: 'Sharm El Sheikh',
        category: 'Nightlife',
        description: 'نادي ليلي عملاق يطل على البحر، يتميز بتصميمه العصري وعروض الليزر.',
        descriptionEn: 'A giant nightclub overlooking the sea, featuring modern design and spectacular laser shows.',
        image: '🚀',
        imageUrl: 'https://images.unsplash.com/photo-1514525253344-991c0575d04a?w=800&q=80',
        rating: 4.7,
        duration: 'Full Night',
        price: 'High',
        highlights: ['Large Dance Floor', 'Sea View Terrace', 'Techno Nights'],
        tip: 'A must-visit for electronic music lovers in Sharm.',
        lat: 27.9254,
        lng: 34.3365,
    },
    {
        id: 421,
        name: 'إليمنتس شرم',
        nameEn: 'Elements Sharm',
        city: 'شرم الشيخ',
        cityEn: 'Sharm El Sheikh',
        category: 'Nightlife',
        description: 'نادي ليلي عصري في خليج نعمة يتميز بالموسيقى العالمية.',
        descriptionEn: 'A modern nightclub in Naama Bay featuring international music.',
        image: '🔥',
        imageUrl: 'https://images.unsplash.com/photo-1514525253344-991c0575d04a?w=800&q=80',
        rating: 4.6,
        duration: 'Full Night',
        price: 'High',
        highlights: ['LED Shows', 'Guest DJs', 'Modern Sound'],
        tip: 'Look out for special themed party nights.',
        lat: 27.9155,
        lng: 34.3255,
    },
    // --- EL GOUNA ---
    {
        id: 407,
        name: 'أورورا',
        nameEn: 'Aurora',
        city: 'الجونة',
        cityEn: 'El Gouna',
        category: 'Nightlife',
        description: 'مزيج من لاونج كوكتيلات ونادي ليلي في قلب مارينا أبو تيج.',
        descriptionEn: 'A hybrid of a cocktail lounge and nightclub in the heart of Abu Tig Marina.',
        image: '✨',
        imageUrl: 'https://images.unsplash.com/photo-1514525253344-991c0575d04a?w=800&q=80',
        rating: 4.7,
        duration: '4-5 hours',
        price: 'High',
        highlights: ['Marina View', 'House Music', 'Stylish Crowd'],
        tip: 'Best for late night dancing after a nice dinner in Gouna.',
        lat: 27.3965,
        lng: 33.6821,
    },
    {
        id: 420,
        name: 'سموكري بيتش',
        nameEn: 'Smokery Beach',
        city: 'الجونة',
        cityEn: 'El Gouna',
        category: 'Nightlife',
        description: 'بار شاطئي فاخر يقدم حفلات رائعة على الرمال.',
        descriptionEn: 'A luxury beach bar offering great parties on the sand.',
        image: '🏖️',
        imageUrl: 'https://images.unsplash.com/photo-1514525253344-991c0575d04a?w=800&q=80',
        rating: 4.8,
        duration: 'Full Night',
        price: 'High',
        highlights: ['Beach Party', 'Sushi Bar', 'Sunset Vibe'],
        tip: 'Dress code is beach chic.',
        lat: 27.4012,
        lng: 33.6855,
    },
    // --- SHEIKH ZAYED ---
    {
        id: 411,
        name: 'سي جيه سي 610',
        nameEn: 'CJC 610',
        city: 'الشيخ زايد',
        cityEn: 'Sheikh Zayed',
        category: 'Nightlife',
        description: 'النسخة الأكبر والأحدث من كايرو جاز كلوب، مساحة واسعة وتراس رائع.',
        descriptionEn: 'The larger, newer version of Cairo Jazz Club with a spacious indoor area and a great terrace.',
        image: '🎶',
        imageUrl: 'https://images.unsplash.com/photo-1514525253344-991c0575d04a?w=800&q=80',
        rating: 4.9,
        duration: '4-5 hours',
        price: 'High',
        highlights: ['Outdoor Terrace', 'Big Stage', 'Craft Cocktails'],
        tip: 'Their brunch on weekends is also very popular.',
        lat: 30.0125,
        lng: 30.9854,
    },
    // --- DAHAB ---
    {
        id: 901,
        name: 'الثقب الأزرق (بلو هول)',
        nameEn: 'Blue Hole',
        city: 'دهب',
        cityEn: 'Dahab',
        category: 'Diving',
        description: 'أشهر موقع للغوص في العالم، عمق مخيف وشعاب مرجانية مذهلة.',
        descriptionEn: 'World-famous diving site known for its depth and stunning coral reefs.',
        image: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&q=80&w=800',
        imageUrl: '',
        rating: 4.9,
        duration: 'Half Day',
        price: 'Free / Gear Rental',
        highlights: ['Diving', 'Freediving', 'Corals'],
        tip: 'احذر من التيارات وتأكد من الغوص مع مرشد محترف.',
        lat: 28.5714,
        lng: 34.5369,
    },
    {
        id: 902,
        name: 'محمية أبو جالوم',
        nameEn: 'Abu Galoum',
        city: 'دهب',
        cityEn: 'Dahab',
        category: 'Nature',
        description: 'محمية طبيعية خلابة تجمع بين الجبال والبحر.',
        descriptionEn: 'A stunning nature reserve combining mountains and the sea.',
        image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&q=80&w=800',
        imageUrl: '',
        rating: 4.8,
        duration: 'Full Day',
        price: 'Variable',
        highlights: ['Hiking', 'Camel Ride', 'Snorkeling'],
        tip: 'يمكن الوصول إليها بالجمال أو القوارب السريعة من البلو هول.',
        lat: 28.6667,
        lng: 34.5333,
    },
    {
        id: 903,
        name: 'الثري بولز',
        nameEn: 'Three Pools',
        city: 'دهب',
        cityEn: 'Dahab',
        category: 'Snorkeling',
        description: 'ثلاثة حمامات سباحة طبيعية متصلة بالشعاب المرجانية.',
        descriptionEn: 'Three natural pools connected by coral reefs, perfect for snorkeling.',
        image: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&q=80&w=800', 
        imageUrl: '',
        rating: 4.7,
        duration: '3-4 hours',
        price: 'Free',
        highlights: ['Snorkeling', 'Relaxing', 'Corals'],
        tip: 'أفضل وقت للزيارة في الصباح الباكر لروية الأسماك بوضوح.',
        lat: 28.4231,
        lng: 34.4561,
    },
    {
        id: 904,
        name: 'جبل الطويلات',
        nameEn: 'Gabal El Towaylat',
        city: 'دهب',
        cityEn: 'Dahab',
        category: 'Nightlife',
        description: 'سهرات بدوية تحت النجوم مع شاي وحفلات غنائية.',
        descriptionEn: 'Bedouin nights under the stars with tea and music.',
        image: 'https://images.unsplash.com/photo-1478131143081-80f7f84ca84d?auto=format&fit=crop&q=80&w=800',
        imageUrl: '',
        rating: 4.6,
        duration: 'Evening',
        price: '150 EGP',
        highlights: ['Stargazing', 'Bedouin Tea', 'Music'],
        tip: 'مكان مثالي للاسترخاء ليلاً بعيداً عن أضواء المدينة.',
        lat: 28.5021,
        lng: 34.4890,
    },
    
    // --- NUWEIBA & TABA ---
    {
        id: 1001,
        name: 'رأس شيطان',
        nameEn: 'Ras Shitan',
        city: 'نويبع',
        cityEn: 'Nuweiba',
        category: 'Nature',
        description: 'المنطقة الأشهر للكامبات البدوية والاسترخاء التام على البحر.',
        descriptionEn: 'The most famous area for Bedouin camps and total relaxation by the sea.',
        image: 'https://images.unsplash.com/photo-1478131143081-80f7f84ca84d?auto=format&fit=crop&q=80&w=800',
        imageUrl: '',
        rating: 4.8,
        duration: 'Full Day',
        price: 'Free (Pay at Camps)',
        highlights: ['Camping', 'Stargazing', 'Snorkeling'],
        tip: 'انفصل عن التكنولوجيا واستمتع بالهدوء التام.',
        lat: 29.1350,
        lng: 34.6850,
    },
    {
        id: 1002,
        name: 'قلعة صلاح الدين بجزيرة فرعون',
        nameEn: 'Pharaoh\'s Island Citadel',
        city: 'طابا',
        cityEn: 'Taba',
        category: 'Historical',
        description: 'قلعة تاريخية وسط البحر بخلفية مذهلة للغوص.',
        descriptionEn: 'Historical citadel in the middle of the sea with a stunning background for diving.',
        image: 'https://images.unsplash.com/photo-1519046904884-53103b34b206?auto=format&fit=crop&q=80&w=800',
        imageUrl: '',
        rating: 4.7,
        duration: '2-3 hours',
        price: '100 EGP',
        highlights: ['History', 'Sea Views', 'Boat Trip'],
        tip: 'تحتاج إلى قارب للوصول إلى الجزيرة.',
        lat: 29.3833,
        lng: 34.8600,
    },
    {
        id: 1003,
        name: 'فيورد باي',
        nameEn: 'Fjord Bay',
        city: 'طابا',
        cityEn: 'Taba',
        category: 'Nature',
        description: 'خليج ساحر محاط بالجبال، ممتاز للتصوير.',
        descriptionEn: 'A magical bay surrounded by mountains, excellent for photography.',
        image: 'https://images.unsplash.com/photo-1519046904884-53103b34b206?auto=format&fit=crop&q=80&w=800',
        imageUrl: '',
        rating: 4.9,
        duration: '1-2 hours',
        price: 'Free',
        highlights: ['Photography', 'Snorkeling', 'Scenery'],
        tip: 'مكان رائع للتوقف لالتقاط الصور أثناء القيادة على طريق طابا.',
        lat: 29.3667,
        lng: 34.8333,
    },

    // --- MARSA MATROUH & NORTH COAST ---
    {
        id: 1101,
        name: 'شاطئ عجيبة',
        nameEn: 'Agiba Beach',
        city: 'مطروح',
        cityEn: 'Matrouh',
        category: 'Beach',
        description: 'شاطئ صخري بمياه متدرجة الألوان تخطف الأنفاس.',
        descriptionEn: 'Rocky beach with breathtaking gradient waters.',
        image: 'https://images.unsplash.com/photo-1473496169904-658ba7c44d8a?auto=format&fit=crop&q=80&w=800',
        imageUrl: '',
        rating: 4.8,
        duration: '2-3 hours',
        price: 'Free',
        highlights: ['Scenery', 'Photography', 'Clear Water'],
        tip: 'مزدحم جداً في الصيف، حاول الزيارة مبكراً.',
        lat: 31.4167,
        lng: 27.0000,
    },
    {
        id: 1102,
        name: 'حمام كليوباترا',
        nameEn: 'Cleopatra Bath',
        city: 'مطروح',
        cityEn: 'Matrouh',
        category: 'Historical/Beach',
        description: 'صخرة مجوفة وسط البحر تتدفق إليها المياه.',
        descriptionEn: 'A hollow rock in the sea where water flows through.',
        image: 'https://images.unsplash.com/photo-1473496169904-658ba7c44d8a?auto=format&fit=crop&q=80&w=800', 
        imageUrl: '',
        rating: 4.5,
        duration: '1-2 hours',
        price: 'Free',
        highlights: ['History Legend', 'Scenery'],
        tip: 'السباحة غير آمنة داخل الصخرة بسبب التيارات.',
        lat: 31.3700,
        lng: 27.1800,
    },
    {
        id: 1103,
        name: 'سيدي عبد الرحمن',
        nameEn: 'Sidi Abdel Rahman',
        city: 'الساحل',
        cityEn: 'North Coast',
        category: 'Beach',
        description: 'يضم أرقى القرى السياحية والشواطئ الرملية البيضاء.',
        descriptionEn: 'Home to the finest resorts and white sandy beaches.',
        image: 'https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?auto=format&fit=crop&q=80&w=800',
        imageUrl: '',
        rating: 4.9,
        duration: 'Full Day',
        price: 'Variable',
        highlights: ['Luxury Resorts', 'Nightlife', 'White Sand'],
        tip: 'تتركز هنا قرى مثل مراسي وهاسيندا.',
        lat: 30.9500,
        lng: 28.7167,
    },

    // --- RAS EL BAR ---
    {
        id: 1201,
        name: 'منطقة اللسان',
        nameEn: 'El Lessan',
        city: 'رأس البر',
        cityEn: 'Ras El Bar',
        category: 'Nature',
        description: 'نقطة التقاء نهر النيل بالبحر المتوسط.',
        descriptionEn: 'The meeting point of the Nile River and the Mediterranean Sea.',
        image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&q=80&w=800',
        imageUrl: '',
        rating: 4.8,
        duration: '2-3 hours',
        price: 'Free',
        highlights: ['Sunset', 'Walking', 'Lighthouse'],
        tip: 'أفضل وقت لزيارتها هو وقت الغروب.',
        lat: 31.5167,
        lng: 31.8333,
    },
    {
        id: 1202,
        name: 'شارع النيل',
        nameEn: 'Nile Street',
        city: 'رأس البر',
        cityEn: 'Ras El Bar',
        category: 'Cultural',
        description: 'الممشى الرئيسي المليء بالمطاعم ومحلات الحلويات الدمياطية.',
        descriptionEn: 'The main promenade full of restaurants and Damietta sweet shops.',
        image: 'https://images.unsplash.com/photo-1579372786545-d24232daf58c?auto=format&fit=crop&q=80&w=800',
        imageUrl: '',
        rating: 4.7,
        duration: 'Evening',
        price: 'Free',
        highlights: ['Sweets', 'Shopping', 'Nile View'],
        tip: 'لا تفوت تجربة المشبك الدمياطي الطازج هنا.',
        lat: 31.5100,
        lng: 31.8250,
    }
];
