export const SERVICE_TYPES = [
    {
        id: 'hourly',
        icon: '⏱️',
        nameEn: 'By The Hour',
        nameAr: 'بالساعة',
        descEn: 'Flexible hourly rental with professional driver',
        descAr: 'إيجار مرن بالساعة مع سائق محترف',
        minHours: 1,
        maxHours: 12,
    },
    {
        id: 'half_day',
        icon: '🌤️',
        nameEn: 'Half Day Tour',
        nameAr: 'نصف يوم',
        descEn: '5 hours of guided sightseeing',
        descAr: '5 ساعات جولة سياحية مميزة',
        durationHours: 5,
    },
    {
        id: 'full_day',
        icon: '☀️',
        nameEn: 'Full Day Tour',
        nameAr: 'يوم كامل',
        descEn: '10 hours with lunch stop included',
        descAr: '10 ساعات مع وقفة غداء',
        durationHours: 10,
    },
    {
        id: 'fixed_trip',
        icon: '📍',
        nameEn: 'Popular Routes',
        nameAr: 'رحلات محددة',
        descEn: 'Pre-planned popular tourist routes',
        descAr: 'مسارات سياحية شهيرة محددة مسبقاً',
    },
    {
        id: 'airport',
        icon: '✈️',
        nameEn: 'Airport Transfer',
        nameAr: 'نقل المطار',
        descEn: 'To/from airport with meet & greet',
        descAr: 'من/إلى المطار مع خدمة الاستقبال',
    },
    {
        id: 'multi_day',
        icon: '🗓️',
        nameEn: 'Multi-Day Package',
        nameAr: 'باقة أيام',
        descEn: '2–7 day packages with 10–20% discount',
        descAr: 'باقات 2-7 أيام بخصم 10-20%',
        minDays: 2,
        maxDays: 7,
    },
];

export const VEHICLE_TYPES = [
    {
        id: 'sedan',
        nameEn: 'Sedan',
        nameAr: 'سيدان',
        icon: '🚗',
        passengers: '1–3',
        luggage: '2 bags',
        priceMultiplier: 1.0,
        features: ['A/C', 'Wi-Fi', 'Water Bottle'],
        badge: null,
    },
    {
        id: 'suv',
        nameEn: 'SUV / 4x4',
        nameAr: 'دفع رباعي',
        icon: '🚙',
        passengers: '1–5',
        luggage: '4 bags',
        priceMultiplier: 1.4,
        features: ['A/C', 'Wi-Fi', 'Water', 'USB Charging'],
        badge: 'Popular',
    },
    {
        id: 'van',
        nameEn: 'Van / Minibus',
        nameAr: 'فان / ميني باص',
        icon: '🚐',
        passengers: '6–12',
        luggage: '8 bags',
        priceMultiplier: 2.0,
        features: ['A/C', 'Wi-Fi', 'Water', 'Group Friendly'],
        badge: 'Groups',
    },
    {
        id: 'luxury',
        nameEn: 'Luxury / VIP',
        nameAr: 'فاخرة / VIP',
        icon: '🏎️',
        passengers: '1–3',
        luggage: '3 bags',
        priceMultiplier: 2.5,
        features: ['A/C', 'Wi-Fi', 'Snacks', 'Leather Seats', 'Tinted Windows'],
        badge: 'VIP',
    },
];

export const FIXED_TRIPS = [
    {
        id: 'cairo-pyramids',
        nameEn: 'Pyramids & Sphinx Tour',
        nameAr: 'جولة الأهرامات وأبو الهول',
        from: 'Cairo',
        to: 'Giza',
        durationHours: 5,
        distanceKm: 15,
        basePrice: 1200,
        stops: ['Giza Pyramids', 'Great Sphinx', 'Panoramic Viewpoint', 'Papyrus Museum'],
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/af/All_Gizah_Pyramids.jpg/800px-All_Gizah_Pyramids.jpg',
        rating: 4.8,
        reviewCount: 342,
        category: 'Pharaonic',
    },
    {
        id: 'cairo-islamic',
        nameEn: 'Islamic Cairo Tour',
        nameAr: 'جولة القاهرة الإسلامية',
        from: 'Cairo',
        to: 'Cairo',
        durationHours: 4,
        distanceKm: 10,
        basePrice: 900,
        stops: ['Saladin Citadel', 'Muhammad Ali Mosque', 'Khan el-Khalili', 'Al-Azhar Mosque'],
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c8/Khan_el-Khalili.jpg/800px-Khan_el-Khalili.jpg',
        rating: 4.7,
        reviewCount: 218,
        category: 'Islamic',
    },
    {
        id: 'luxor-east',
        nameEn: 'Luxor East Bank',
        nameAr: 'البر الشرقي بالأقصر',
        from: 'Luxor',
        to: 'Luxor',
        durationHours: 4,
        distanceKm: 8,
        basePrice: 800,
        stops: ['Karnak Temple', 'Luxor Temple', 'Avenue of Sphinxes'],
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Karnak_Temple_Complex_2005.jpg/800px-Karnak_Temple_Complex_2005.jpg',
        rating: 4.9,
        reviewCount: 187,
        category: 'Pharaonic',
    },
    {
        id: 'luxor-west',
        nameEn: 'Luxor West Bank',
        nameAr: 'البر الغربي بالأقصر',
        from: 'Luxor',
        to: 'Luxor',
        durationHours: 5,
        distanceKm: 12,
        basePrice: 1000,
        stops: ['Valley of the Kings', 'Hatshepsut Temple', 'Colossi of Memnon'],
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/0/0c/Luxor%2C_Tal_der_K%C3%B6nige_%281995%2C_860x605%29.jpg',
        rating: 4.9,
        reviewCount: 256,
        category: 'Pharaonic',
    },
    {
        id: 'cairo-alex',
        nameEn: 'Cairo → Alexandria Day Trip',
        nameAr: 'يوم كامل للإسكندرية',
        from: 'Cairo',
        to: 'Alexandria',
        durationHours: 12,
        distanceKm: 220,
        basePrice: 2500,
        stops: ['Bibliotheca Alexandrina', 'Qaitbay Citadel', 'Seafood Lunch', 'Corniche Walk'],
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/82/Alexandria_Corniche_1.jpg/800px-Alexandria_Corniche_1.jpg',
        rating: 4.6,
        reviewCount: 134,
        category: 'Cultural',
    },
    {
        id: 'aswan-abu-simbel',
        nameEn: 'Abu Simbel Day Trip',
        nameAr: 'رحلة يوم لأبو سمبل',
        from: 'Aswan',
        to: 'Abu Simbel',
        durationHours: 10,
        distanceKm: 290,
        basePrice: 3000,
        stops: ['Abu Simbel Temples', 'Ramses II Colossi', 'Lake Nasser Viewpoint'],
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/Abu_Simbel_Temple_of_Ramesses_II.jpg/800px-Abu_Simbel_Temple_of_Ramesses_II.jpg',
        rating: 4.9,
        reviewCount: 421,
        category: 'Pharaonic',
    },
    {
        id: 'hurghada-luxor',
        nameEn: 'Hurghada → Luxor Day Trip',
        nameAr: 'الغردقة → الأقصر يوم كامل',
        from: 'Hurghada',
        to: 'Luxor',
        durationHours: 14,
        distanceKm: 300,
        basePrice: 3500,
        stops: ['Valley of the Kings', 'Hatshepsut Temple', 'Karnak Temple', 'Egyptian Lunch'],
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Flickr_-_archer10_%28Dennis%29_-_Egypt-13A-061_%28cropped%29.jpg/960px-Flickr_-_archer10_%28Dennis%29_-_Egypt-13A-061_%28cropped%29.jpg',
        rating: 4.5,
        reviewCount: 98,
        category: 'Pharaonic',
    },
    {
        id: 'sharm-dahab',
        nameEn: 'Sharm → Dahab Blue Hole',
        nameAr: 'شرم → الثقب الأزرق بدهب',
        from: 'Sharm El Sheikh',
        to: 'Dahab',
        durationHours: 8,
        distanceKm: 90,
        basePrice: 1800,
        stops: ['Blue Hole Snorkeling', 'Bedouin Lunch', 'Dahab Promenade', 'Canyon Dive Site'],
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/34/Blue_Whole%2C_Dahab.jpg/960px-Blue_Whole%2C_Dahab.jpg',
        rating: 4.8,
        reviewCount: 167,
        category: 'Diving',
    },
];

export const CITY_BASE_RATES = {
    'Cairo':           { hourly: 350, halfDay: 1200, fullDay: 2000, airportTransfer: 600 },
    'Giza':            { hourly: 350, halfDay: 1200, fullDay: 2000, airportTransfer: 700 },
    'Luxor':           { hourly: 300, halfDay: 1000, fullDay: 1800, airportTransfer: 400 },
    'Aswan':           { hourly: 300, halfDay: 1000, fullDay: 1800, airportTransfer: 400 },
    'Sharm El Sheikh': { hourly: 400, halfDay: 1400, fullDay: 2200, airportTransfer: 500 },
    'Hurghada':        { hourly: 350, halfDay: 1200, fullDay: 2000, airportTransfer: 450 },
    'Alexandria':      { hourly: 300, halfDay: 1000, fullDay: 1800, airportTransfer: 500 },
    'Dahab':           { hourly: 300, halfDay: 1000, fullDay: 1800, airportTransfer: 600 },
    'Marsa Matrouh':   { hourly: 280, halfDay: 900,  fullDay: 1600, airportTransfer: 450 },
};

export const AIRPORTS = [
    { id: 'CAI', nameEn: 'Cairo International', nameAr: 'مطار القاهرة الدولي', city: 'Cairo' },
    { id: 'LXR', nameEn: 'Luxor Airport', nameAr: 'مطار الأقصر', city: 'Luxor' },
    { id: 'HRG', nameEn: 'Hurghada Airport', nameAr: 'مطار الغردقة', city: 'Hurghada' },
    { id: 'SSH', nameEn: 'Sharm El Sheikh Airport', nameAr: 'مطار شرم الشيخ', city: 'Sharm El Sheikh' },
    { id: 'HBE', nameEn: 'Alexandria Borg El Arab', nameAr: 'مطار الإسكندرية', city: 'Alexandria' },
    { id: 'ASW', nameEn: 'Aswan Airport', nameAr: 'مطار أسوان', city: 'Aswan' },
];

export const INCLUDED_FEATURES = [
    { icon: 'car-outline', textEn: 'Professional licensed driver', textAr: 'سائق محترف ومرخص' },
    { icon: 'thermometer-outline', textEn: 'Air-conditioned vehicle', textAr: 'سيارة مكيفة' },
    { icon: 'water-outline', textEn: 'Complimentary water', textAr: 'مياه مجانية' },
    { icon: 'wifi-outline', textEn: 'Free Wi-Fi on board', textAr: 'واي فاي مجاني' },
    { icon: 'close-circle-outline', textEn: 'Free cancellation 24h before', textAr: 'إلغاء مجاني قبل 24 ساعة' },
    { icon: 'shield-checkmark-outline', textEn: 'Fully insured vehicle', textAr: 'سيارة مؤمنة بالكامل' },
];
